import { describe,expect,it } from 'vitest';
import {readFileSync} from 'node:fs';
import {agreementTemplateHash,internalAgreementSource} from '../src/shared/agreement.js';
import { agreementDocumentHash, AGREEMENT_RENDERER_VERSION, renderAgreementDocument } from '../src/shared/agreementRenderer.js';
import {agreementPdfHash,AGREEMENT_PDF_RENDERER_VERSION,bytesToBase64,renderAgreementPdf,verifiedAgreementPdfBytes} from '../src/shared/agreementPdf.js';
import {canonicalAgreementMarkdown} from '../src/legal/canonicalAgreement.generated.js';

async function input(){const hash=await agreementTemplateHash(internalAgreementSource);return{agreement:{template_id:1,template_version:internalAgreementSource.sourceVersion,template_hash:hash,renter_snapshot_json:'{"legalName":"Synthetic Long Renter Name","email":"renter@example.test","phone":"480-555-0100"}',reservation_snapshot_json:'{"confirmationCode":"TEST-1","equipmentDescription":"14 ft Tandem Axle Utility Trailer","unitCode":"TB-001","pickupAt":"2027-01-01T15:00:00Z","returnAt":"2027-01-02T15:00:00Z"}',quote_snapshot_json:'{"rentalChargeCents":6000,"deliveryChargeCents":1000,"rawRoadMiles":3.56,"billableMiles":4,"securityDepositCents":10000,"totalCents":17000}',signature_evidence_json:'{"signature":{"format":"NORMALIZED_POINTER_POINTS_V1","points":[[0.1,0.2],[0.3,0.6],[0.8,0.3]],"hash":"sig-hash"}}',electronic_consent_at:'2027-01-01T00:00:00Z',terms_acknowledged_at:'2027-01-01T00:00:00Z',driver_insurance_acknowledged_at:'2027-01-01T00:00:00Z',inspection_opportunity_acknowledged_at:'2027-01-01T00:00:00Z',pickup_inspection_choice:'SEND_FORM',signed_at:'2027-01-01T00:00:00Z',printed_name:'Synthetic Long Renter Name'},template:{content_json:JSON.stringify(internalAgreementSource),legal_review_status:'OWNER_DRAFT_ATTORNEY_REVIEW_PENDING'},pickupCondition:{status:'PENDING'}}}
describe('agreement renderer',()=>{
 it('keeps the runtime mirror aligned with the canonical customer Markdown and excludes the appendix',()=>{const normalize=(value:string)=>value.replace(/\r\n/g,'\n').trimEnd()+'\n';const source=normalize(readFileSync(new URL('../src/legal/TB-RA-2026-08-v1.md',import.meta.url),'utf8'));expect(normalize(canonicalAgreementMarkdown)).toBe(source);expect(source).not.toContain('INTERNAL RESEARCH AND IMPLEMENTATION APPENDIX')});
 it('derives deterministic HTML from the canonical source and resolves every customer placeholder',async()=>{const fixture=await input();const first=renderAgreementDocument(fixture);const second=renderAgreementDocument(fixture);expect(first.html).toBe(second.html);expect(first.html).toContain('TB-RA-2026-08-v1');expect(first.html).toContain('5,200 lb');expect(first.html).toContain('TEST-1');expect(first.html).toContain('Billable delivery miles');expect(first.html).toContain('$2.50 per mile');expect(first.html).not.toContain('One-way road mileage');expect(first.html).not.toContain('Rounded billable mileage');expect(first.html).not.toContain('{{');expect(first.html).not.toContain('INTERNAL RESEARCH');expect(first.model.rendererVersion).toBe(AGREEMENT_RENDERER_VERSION);expect(await agreementDocumentHash(first.html)).toBe(await agreementDocumentHash(second.html));});
 it('produces deterministic real PDF bytes with every agreement section, resolved variables, and drawn signature evidence',async()=>{const fixture=await input();const first=renderAgreementPdf(fixture);const second=renderAgreementPdf(fixture);const text=new TextDecoder('latin1').decode(first.bytes);expect(first.pageCount).toBeGreaterThan(2);expect(first.bytes.slice(0,8)).toEqual(new TextEncoder().encode('%PDF-1.4'));expect(await agreementPdfHash(first.bytes)).toBe(await agreementPdfHash(second.bytes));expect(text).toContain('Drawn signature');expect(text).toContain('TEST-1');expect(text).not.toContain('{{');expect(AGREEMENT_PDF_RENDERER_VERSION).toBe('agreement-pdf-v1')});
 it('verifies the exact stored PDF bytes against the immutable document hash',async()=>{const fixture=await input();const rendered=renderAgreementPdf(fixture);const document_hash=await agreementPdfHash(rendered.bytes);const record={content_type:'application/pdf;base64',content_text:bytesToBase64(rendered.bytes),document_hash};expect(await verifiedAgreementPdfBytes(record)).toEqual(rendered.bytes);expect(await verifiedAgreementPdfBytes({...record,document_hash:'0'.repeat(64)})).toBeNull();expect(await verifiedAgreementPdfBytes({...record,content_text:'not-base64'})).toBeNull()});
 it('fails closed when template version and canonical source disagree',async()=>{const fixture=await input();expect(()=>renderAgreementPdf({...fixture,agreement:{...fixture.agreement,template_version:'old'}})).toThrow('CANONICAL_AGREEMENT_SOURCE_MISMATCH')});
});
