import { beforeEach, describe, expect, it } from 'vitest';
import type Database from 'better-sqlite3';
import { handleApiRequest } from '../src/server/api.js';
import { createLocalDatabasePort, migrate, openDatabase } from '../src/server/db/database.js';
import { AGREEMENT_SOURCE_VERSION } from '../src/shared/agreement.js';
import { ATTORNEY_APPROVAL_CONFIRMATION, attorneyApprovalReadiness, currentAgreementApprovalIdentity } from '../src/shared/attorneyApproval.js';

let raw:Database.Database;
const env=()=>({ENVIRONMENT:'development' as const,AUTH_MODE:'mock' as const,ALLOWED_OWNER_EMAIL:'owner@example.test',DB:createLocalDatabasePort(raw)});
const request=(path:string,init:RequestInit={})=>handleApiRequest(new Request(`http://local${path}`,{...init,headers:{'content-type':'application/json','x-dev-owner-email':'owner@example.test',...init.headers}}),env(),{now:()=>new Date('2027-07-15T12:00:00Z')});
beforeEach(()=>{raw?.close();raw=openDatabase(':memory:');migrate(raw)});

describe('attorney approval release gate',()=>{
 it('is fail-closed by default and after a source mismatch',async()=>{expect(await attorneyApprovalReadiness()).toMatchObject({status:'ATTORNEY_APPROVAL_REQUIRED',approved:false,publicAgreementSigningAllowed:false,liveCheckoutAllowed:false});const identity=await currentAgreementApprovalIdentity();expect(await attorneyApprovalReadiness({id:1,agreement_version:'changed-version',agreement_source_hash:identity.agreementSourceHash,attorney_review_date:'2027-07-01',approval_reference:'matter-reference',recorded_at:'2027-07-15T12:00:00Z',recorded_by:'owner@example.test'})).toMatchObject({approved:false})});
 it('requires deliberate exact evidence and records an immutable audited approval',async()=>{expect((await request('/api/readiness/attorney-approval')).status).toBe(200);const missing=await request('/api/readiness/attorney-approval',{method:'POST',body:JSON.stringify({agreementVersion:AGREEMENT_SOURCE_VERSION,attorneyReviewDate:'2027-07-01',approvalReference:'matter-reference'})});expect(missing.status).toBe(400);const created=await request('/api/readiness/attorney-approval',{method:'POST',body:JSON.stringify({agreementVersion:AGREEMENT_SOURCE_VERSION,attorneyReviewDate:'2027-07-01',approvalReference:'matter-reference',confirmation:ATTORNEY_APPROVAL_CONFIRMATION})});expect(created.status).toBe(201);expect(await created.json()).toMatchObject({status:'APPROVED',approved:true,publicAgreementSigningAllowed:true,liveCheckoutAllowed:true,approval:{attorneyReviewDate:'2027-07-01',approvalReference:'matter-reference'}});expect(raw.prepare("SELECT count(*) total FROM audit_events WHERE action='ATTORNEY_APPROVAL_RECORDED'").get()).toEqual({total:1});expect(()=>raw.prepare("UPDATE attorney_approval_records SET approval_reference='changed'").run()).toThrow(/ATTORNEY_APPROVAL_IMMUTABLE/);expect(()=>raw.prepare('DELETE FROM attorney_approval_records').run()).toThrow(/ATTORNEY_APPROVAL_IMMUTABLE/)});
 it('rejects stale versions and future review dates',async()=>{const base={approvalReference:'matter-reference',confirmation:ATTORNEY_APPROVAL_CONFIRMATION};expect((await request('/api/readiness/attorney-approval',{method:'POST',body:JSON.stringify({...base,agreementVersion:'stale',attorneyReviewDate:'2027-07-01'})})).status).toBe(409);expect((await request('/api/readiness/attorney-approval',{method:'POST',body:JSON.stringify({...base,agreementVersion:AGREEMENT_SOURCE_VERSION,attorneyReviewDate:'2027-07-16'})})).status).toBe(400);expect(raw.prepare('SELECT count(*) total FROM attorney_approval_records').get()).toEqual({total:0})});
});
