import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { createRestorableD1Backup, verifyD1Backup } from '../scripts/verify-d1-backup.js';
import { migrate, openDatabase } from '../src/server/db/database.js';

let directory='';afterEach(()=>{if(directory)rmSync(directory,{recursive:true,force:true})});
const literal=(value:unknown)=>value===null?'NULL':typeof value==='number'?String(value):`'${String(value).replaceAll("'","''")}'`;
describe('D1 backup verification',()=>{
 it('verifies schema, triggers, integrity, counts, and synthetic markers without returning row data',()=>{directory=mkdtempSync(join(tmpdir(),'rental-os-backup-'));const db=openDatabase(':memory:');migrate(db);db.exec("INSERT INTO trailers(name,unit_code,published_payload_lbs) VALUES ('Synthetic trailer','SYNTH',5200); INSERT INTO customers(first_name,last_name) VALUES ('Synthetic','Owner'); INSERT INTO reservations(confirmation_code,trailer_id,customer_id,channel,status,pickup_at,return_at,rental_charge_cents,is_synthetic) VALUES ('SYNTH-BACKUP',1,1,'DIRECT','CONFIRMED','2027-10-01T13:00:00Z','2027-10-01T15:00:00Z',1000,1)");const schema=(db.prepare("SELECT sql FROM sqlite_schema WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' ORDER BY CASE type WHEN 'table' THEN 0 WHEN 'index' THEN 1 ELSE 2 END,name").all() as {sql:string}[]).map(row=>`${row.sql};`).join('\n');const tables=['trailers','customers','reservations','availability_blocks','booking_intents','payments','audit_events','condition_inspections','inspection_photos','cancellation_outcomes','deposit_decisions'];const inserts=tables.flatMap(table=>(db.prepare(`SELECT * FROM ${table}`).all() as Record<string,unknown>[]).map(value=>`INSERT INTO ${table}(${Object.keys(value).join(',')}) VALUES (${Object.values(value).map(literal).join(',')});`)).join('\n');db.close();const file=join(directory,'backup.sql');writeFileSync(file,`${schema}\n${inserts}`);const result=verifyD1Backup(file);expect(result.counts).toMatchObject({reservations:1,customers:1,booking_intents:0});expect(result.syntheticReservations).toBe(1);expect(result.sha256).toMatch(/^[0-9a-f]{64}$/);expect(JSON.stringify(result)).not.toContain('Synthetic Owner');});
 it('rejects credential-shaped content before restore',()=>{directory=mkdtempSync(join(tmpdir(),'rental-os-backup-'));const file=join(directory,'bad.sql');writeFileSync(file,'-- client_secret=unsafe');expect(()=>verifyD1Backup(file)).toThrow('credential-shaped');});
 it('normalizes D1 exports into dependency-ordered restorable SQL',()=>{directory=mkdtempSync(join(tmpdir(),'rental-os-backup-'));const source=join(directory,'source.sql');const output=join(directory,'restore.sql');writeFileSync(source,`PRAGMA defer_foreign_keys=TRUE;\nCREATE TABLE availability_blocks(id INTEGER PRIMARY KEY,trailer_id INTEGER REFERENCES trailers(id),is_synthetic INTEGER NOT NULL DEFAULT 0);\nINSERT INTO availability_blocks VALUES(1,1,1);\nCREATE TABLE trailers(id INTEGER PRIMARY KEY,name TEXT);\nINSERT INTO trailers VALUES(1,'Synthetic');\nCREATE TABLE customers(id INTEGER PRIMARY KEY);CREATE TABLE reservations(id INTEGER PRIMARY KEY,is_synthetic INTEGER NOT NULL DEFAULT 0);CREATE TABLE booking_intents(id INTEGER PRIMARY KEY,is_synthetic INTEGER NOT NULL DEFAULT 1);CREATE TABLE booking_intent_conversions(id INTEGER PRIMARY KEY);CREATE TABLE payments(id INTEGER PRIMARY KEY);CREATE TABLE audit_events(id INTEGER PRIMARY KEY);CREATE TABLE condition_inspections(id INTEGER PRIMARY KEY);CREATE TABLE inspection_photos(id INTEGER PRIMARY KEY);CREATE TABLE cancellation_outcomes(id INTEGER PRIMARY KEY);CREATE TABLE deposit_decisions(id INTEGER PRIMARY KEY);CREATE TABLE agreement_templates(id INTEGER PRIMARY KEY);CREATE TABLE agreement_instances(id INTEGER PRIMARY KEY);CREATE TABLE pickup_condition_choices(id INTEGER PRIMARY KEY);CREATE TRIGGER reservations_no_overlap_insert BEFORE INSERT ON reservations BEGIN SELECT 1; END;CREATE TRIGGER reservations_no_overlap_update BEFORE UPDATE ON reservations BEGIN SELECT 1; END;CREATE TRIGGER blocks_no_overlap_insert BEFORE INSERT ON availability_blocks BEGIN SELECT 1; END;CREATE TRIGGER blocks_no_overlap_update BEFORE UPDATE ON availability_blocks BEGIN SELECT 1; END;`);createRestorableD1Backup(source,output);expect(()=>verifyD1Backup(output)).not.toThrow();expect(readFileSync(output,'utf8').indexOf('CREATE TABLE trailers')).toBeLessThan(readFileSync(output,'utf8').indexOf('INSERT INTO "availability_blocks"'));});
});
