import {beforeEach,describe,expect,it} from 'vitest';
import type Database from 'better-sqlite3';
import {handleApiRequest} from '../src/server/api.js';
import {createLocalDatabasePort,migrate,openDatabase} from '../src/server/db/database.js';
import {createNoSendCommunicationProvider,validateGmailConfiguration} from '../src/server/communicationProvider.js';
let raw:Database.Database;
const env=()=>({ENVIRONMENT:'development' as const,AUTH_MODE:'mock' as const,ALLOWED_OWNER_EMAIL:'owner@example.test',DB:createLocalDatabasePort(raw)});
const call=(path:string,init:RequestInit={})=>handleApiRequest(new Request(`http://local${path}`,{...init,headers:{'content-type':'application/json','x-dev-owner-email':'owner@example.test',...init.headers}}),env(),{now:()=>new Date('2027-01-01T12:00:00Z')});
const prepare=(key:string,idempotencyKey=`communication_${key.toLowerCase()}_synthetic_001`)=>call('/api/reservations/1/communications',{method:'POST',body:JSON.stringify({templateKey:key,idempotencyKey})});
function base(choice='SEND_FORM'){raw.exec(`INSERT INTO trailers(name,unit_code,published_payload_lbs) VALUES ('Synthetic Trailer','T1',5200);INSERT INTO customers(first_name,last_name,email,phone) VALUES ('Synthetic','Renter','renter@example.test','480-555-0100');INSERT INTO reservations(id,confirmation_code,trailer_id,customer_id,channel,status,pickup_at,return_at,rental_charge_cents,dolly_days,is_synthetic,renter_age,named_renter_will_tow,interstate_use,interstate_approved,international_use,delivery_requested,delivery_approved) VALUES (1,'DIRECT-1',1,1,'DIRECT','CONFIRMED','2027-08-01T15:00:00Z','2027-08-02T15:00:00Z',6000,1,1,30,1,0,0,0,0,0);INSERT INTO agreement_templates(id,version,source_manifest_version,content_json,content_hash,is_synthetic) VALUES (1,'v1','v1','{}','hash-v1',1);INSERT INTO agreement_instances(reservation_id,template_id,status,template_version,template_hash,renter_snapshot_json,reservation_snapshot_json,quote_snapshot_json,rendered_at,electronic_consent_at,terms_acknowledged_at,driver_insurance_acknowledged_at,inspection_opportunity_acknowledged_at,pickup_inspection_choice,pickup_inspection_choice_at,signed_at,printed_name,is_synthetic) VALUES (1,1,'SIGNED','v1','hash-v1','{}','{}','{}','2027-01-01T00:00:00Z','2027-01-01T00:00:00Z','2027-01-01T00:00:00Z','2027-01-01T00:00:00Z','2027-01-01T00:00:00Z','${choice}','2027-01-01T00:00:00Z','2027-01-01T00:00:00Z','Synthetic Renter',1);INSERT INTO payment_ledger_entries(reservation_id,kind,status,amount_cents,provider,provider_payment_id,idempotency_key,breakdown_json,is_synthetic) VALUES (1,'PAYMENT_COLLECTED','SUCCEEDED',17000,'STRIPE_TEST','pi_test_short','collection_001','{}',1);`)}
beforeEach(()=>{raw?.close();raw=openDatabase(':memory:');migrate(raw);base()});
describe('direct confirmation communication foundation',()=>{
 it('projects the persisted inspection choice into reservation detail',async()=>{const detail=await (await call('/api/reservations/1')).json() as {agreements:Array<Record<string,unknown>>};expect(detail.agreements[0]).toMatchObject({pickup_inspection_choice:'SEND_FORM',pickup_inspection_choice_at:'2027-01-01T00:00:00Z'})});
 it('blocks confirmation when authoritative agreement evidence is absent',async()=>{raw.close();raw=openDatabase(':memory:');migrate(raw);raw.exec("INSERT INTO trailers(name,unit_code,published_payload_lbs) VALUES ('Synthetic Trailer','T1',5200);INSERT INTO customers(first_name,last_name,email) VALUES ('Synthetic','Renter','renter@example.test');INSERT INTO reservations(id,confirmation_code,trailer_id,customer_id,channel,status,pickup_at,return_at,rental_charge_cents,is_synthetic,renter_age,named_renter_will_tow) VALUES (1,'DIRECT-1',1,1,'DIRECT','CONFIRMED','2027-08-01T15:00:00Z','2027-08-02T15:00:00Z',6000,1,30,1);INSERT INTO payment_ledger_entries(reservation_id,kind,status,amount_cents,provider,idempotency_key,is_synthetic) VALUES (1,'PAYMENT_COLLECTED','SUCCEEDED',16000,'MOCK','collection_missing_agreement',1)");expect(await (await prepare('BOOKING_CONFIRMATION')).json()).toMatchObject({blockers:expect.arrayContaining(['A signed agreement is required.'])})});
 it('performs a fresh final availability check',async()=>{raw.exec("DROP TRIGGER blocks_no_overlap_insert; INSERT INTO availability_blocks(trailer_id,start_at,end_at,reason,is_synthetic) VALUES (1,'2027-08-01T16:00:00Z','2027-08-01T17:00:00Z','Simulated concurrent conflict',1)");expect(await (await prepare('BOOKING_CONFIRMATION','communication_conflict_002')).json()).toMatchObject({blockers:expect.arrayContaining(['Final authoritative availability revalidation failed.'])})});
 it('prepares deterministic HTML and text with provenance, idempotency, and affirmative inspection link',async()=>{const response=await prepare('BOOKING_CONFIRMATION');expect(response.status).toBe(201);expect(await response.json()).toMatchObject({state:'SEND_UNAVAILABLE',inspectionLinkIncluded:true,sendAvailable:false});const stored=raw.prepare('SELECT communication_type,recipient,state,source_template_hash,rendered_content_hash,body_text,body_html,safe_error_classification,idempotency_key FROM communication_records').get() as Record<string,string>;expect(stored).toMatchObject({communication_type:'BOOKING_CONFIRMATION',recipient:'renter@example.test',state:'SEND_UNAVAILABLE',safe_error_classification:'PROVIDER_NOT_CONFIGURED'});expect(stored.body_text).toContain('Your Trailer Bros reservation is confirmed.');expect(stored.body_html).toContain('<!doctype html>');expect(stored.body_html).not.toMatch(/<script|<img|https?:\/\//i);expect(stored.source_template_hash).toMatch(/^[0-9a-f]{64}$/);expect(stored.rendered_content_hash).toMatch(/^[0-9a-f]{64}$/);const duplicate=await prepare('BOOKING_CONFIRMATION');expect(await duplicate.json()).toMatchObject({idempotent:true});expect(raw.prepare('SELECT count(*) total FROM communication_records').get()).toEqual({total:1});expect(()=>raw.prepare("UPDATE communication_records SET body_text='changed'").run()).toThrow(/COMMUNICATION_CONTENT_IMMUTABLE/);expect(()=>raw.prepare("UPDATE communication_records SET body_html='<p>changed</p>'").run()).toThrow(/COMMUNICATION_CONTENT_IMMUTABLE/);expect(()=>raw.prepare('DELETE FROM communication_records').run()).toThrow(/COMMUNICATION_RECORD_IMMUTABLE/);expect(raw.prepare("SELECT count(*) total FROM audit_events WHERE action='COMMUNICATION_PREPARED'").get()).toEqual({total:1})});
 it('does not include an inspection link after an explicit decline',async()=>{raw.close();raw=openDatabase(':memory:');migrate(raw);base('DECLINE_FORM');raw.exec("INSERT INTO pickup_condition_choices(reservation_id,status,decline_acknowledgment,decided_at,actor,is_synthetic) VALUES (1,'DECLINED','Explicit choice','2027-01-01T00:00:00Z','owner@example.test',1)");const result=await (await prepare('BOOKING_CONFIRMATION')).json() as {body:string;html:string;inspectionLinkIncluded:boolean};expect(result.inspectionLinkIncluded).toBe(false);expect(result.body).toContain('chose to decline');expect(`${result.body}${result.html}`).not.toContain('pickup-inspection link generated')});
 it('keeps external-source workflows manual',async()=>{raw.prepare("UPDATE reservations SET channel='EXTERNAL',external_source='FACEBOOK_MARKETPLACE'").run();const response=await prepare('BOOKING_CONFIRMATION');expect(response.status).toBe(409);expect(await response.json()).toMatchObject({blockers:expect.arrayContaining([expect.stringContaining('external sources remain owner-review/manual')])})});
});
describe('rental closeout communication foundation',()=>{
 it('blocks closeout before return inspection and final deposit decision',async()=>{const response=await prepare('RENTAL_CLOSEOUT');expect(response.status).toBe(409);expect(await response.json()).toMatchObject({blockers:expect.arrayContaining(['Completed return inspection is required.','Final deposit decision is required.'])})});
 it('does not claim a release refund until the immutable ledger records completion',async()=>{raw.exec("INSERT INTO condition_inspections(reservation_id,type,condition_notes,damage_found,inspected_at,actor) VALUES (1,'RETURN','Good',0,'2027-08-02T15:00:00Z','owner@example.test');INSERT INTO deposit_decisions(reservation_id,decision,amount_cents,reason,payment_action,decided_at,actor) VALUES (1,'RELEASE_RECORDED',0,'Clean return','NOT_EXECUTED','2027-08-02T16:00:00Z','owner@example.test')");let result=await (await prepare('RENTAL_CLOSEOUT')).json() as {body:string};expect(result.body).toContain('does not yet record');raw.exec("INSERT INTO payment_ledger_entries(reservation_id,kind,status,amount_cents,provider,provider_refund_id,idempotency_key,breakdown_json,is_synthetic) VALUES (1,'REFUND_SUCCEEDED','SUCCEEDED',10000,'STRIPE_TEST','re_test_short','deposit_release_001','{\"action\":\"DEPOSIT_RELEASE\"}',1)");result=await (await prepare('RENTAL_CLOSEOUT','communication_closeout_completed_002')).json() as {body:string};expect(result.body).toContain('records the $100 refundable security-deposit refund as completed')});
});
describe('provider and privacy boundary',()=>{
 it('fails closed without Gmail configuration and never reports sent',async()=>{expect(validateGmailConfiguration({})).toMatchObject({configured:false,ready:false,reason:'GMAIL_NOT_CONNECTED'});await expect(createNoSendCommunicationProvider().prepare({recipient:'renter@example.test',subject:'Test',body:'Test',idempotencyKey:'provider_test_001'})).resolves.toEqual({state:'SEND_UNAVAILABLE',safeErrorClassification:'PROVIDER_NOT_CONFIGURED'})});
 it('stores no card, credential, driver-license, or raw agreement evidence fields',async()=>{await prepare('BOOKING_CONFIRMATION');const columns=(raw.prepare('PRAGMA table_info(communication_records)').all() as {name:string}[]).map(row=>row.name).join(' ');expect(columns).not.toMatch(/card|secret|license|signature|agreement_snapshot|inspection_notes/i)});
});
