import {describe,expect,it} from 'vitest';
import {communicationHash,communicationTemplateKeys,communicationTemplateManifest,renderCommunication} from '../src/shared/communicationTemplates.js';
const base={customerName:'Synthetic Owner Test',confirmationCode:'SYN-100',pickupAt:'2026-07-16T13:00:00.000Z',returnAt:'2026-07-17T13:00:00.000Z',trailerName:'Synthetic Trailer',fulfillment:'Customer pickup',rentalCents:6000,dollyCents:1000,deliveryCents:0,depositCents:10000,totalCents:17000,inspectionChoice:'SEND_FORM' as const};
describe('two deterministic customer communications',()=>{
 it('defines exactly booking confirmation and rental closeout',()=>expect(communicationTemplateKeys).toEqual(['BOOKING_CONFIRMATION','RENTAL_CLOSEOUT']));
 it('renders a confirmation with parity, itemized payment, agreement receipt, and affirmative inspection link only',()=>{const result=renderCommunication('BOOKING_CONFIRMATION',{...base,agreementLinkPlaceholder:'[agreement]',inspectionLinkPlaceholder:'[inspection]'});for(const text of ['[agreement]','[inspection]','Arizona time']){expect(result.plainText).toContain(text);expect(result.html).toContain(text)}expect(result.plainText).toContain('Total collected: $170.00');expect(result.html).toContain('Total collected');expect(result.html).toContain('$170.00');expect(result.subject).toContain('booking confirmed');expect(result.plainText).not.toMatch(/request received/i)});
 it('suppresses the inspection link for an explicit decline in both formats',()=>{const result=renderCommunication('BOOKING_CONFIRMATION',{...base,inspectionChoice:'DECLINE_FORM',inspectionLinkPlaceholder:'NEVER_SHOW'});expect(result.plainText).toContain('chose to decline');expect(result.html).toContain('chose to decline');expect(`${result.plainText}${result.html}`).not.toContain('NEVER_SHOW')});
 it('never claims refund completion without authoritative ledger evidence',()=>{const pending=renderCommunication('RENTAL_CLOSEOUT',{...base,depositDecision:'RELEASE_RECORDED',refundCompleted:false});expect(`${pending.plainText}${pending.html}`).toContain('does not yet record');const completed=renderCommunication('RENTAL_CLOSEOUT',{...base,depositDecision:'RELEASE_RECORDED',refundCompleted:true});expect(completed.plainText).toContain('records the $100 refundable security-deposit refund as completed');expect(completed.html).toContain('records the $100 refundable security-deposit refund as completed')});
 it('renders retained outcomes neutrally and hashes deterministically',async()=>{const result=renderCommunication('RENTAL_CLOSEOUT',{...base,depositDecision:'RETAIN_RECORDED',depositAmountCents:5000});expect(`${result.plainText}${result.html}`).toContain('owner-reviewed');expect(await communicationHash(communicationTemplateManifest)).toBe(await communicationHash(communicationTemplateManifest))});
 it('uses accessible self-contained email HTML without external assets, fonts, scripts, or tracking',()=>{const html=renderCommunication('BOOKING_CONFIRMATION',base).html;expect(html).toContain('role="presentation"');expect(html).toContain('Arial');expect(html).not.toMatch(/<script|<img|<link|@font-face|https?:\/\//i);expect(communicationTemplateManifest).toMatchObject({externalAssets:false,tracking:false,formats:['text/plain','text/html']})});
});
