import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { convertSyntheticBookingIntent, type ConversionRequest } from '../src/server/conversion.js';
import { createLocalDatabasePort, migrate, openDatabase } from '../src/server/db/database.js';
import type { DatabasePort } from '../src/server/db/port.js';

describe('reservation conversion foundation',()=>{
  let raw:ReturnType<typeof openDatabase>;let db:DatabasePort;
  const now=new Date('2027-01-01T12:00:00.000Z');
  const approval:ConversionRequest['approval']={qualificationReviewed:true,interstateApproved:false,deliveryApproved:false,agreement:{agreementId:77,status:'SIGNED',signedAt:'2027-01-01T11:55:00.000Z',templateHash:'a'.repeat(64)}};
  const request=(overrides:Partial<ConversionRequest>={}):ConversionRequest=>({intentId:1,idempotencyKey:'convert-intent-1',actor:'owner@example.test',approval,confirmationCode:'SYN-CONVERT-1',...overrides});
  beforeEach(()=>{raw=openDatabase(':memory:');migrate(raw);db=createLocalDatabasePort(raw);raw.exec(`INSERT INTO trailers(name,unit_code,published_payload_lbs,plate_verified) VALUES ('Synthetic trailer','SYN-1',5200,0);
    INSERT INTO booking_intents(idempotency_key,trailer_id,status,legal_name,email,phone,age_25_confirmed,named_renter_only_towing,tow_vehicle_details,hitch_ball_acknowledged,brake_controller_acknowledged,insurance_acknowledged,intended_use,trip_type,interstate_approval_required,fulfillment_type,delivery_approval_required,pickup_at,return_at,dolly_requested,rental_days,rental_charge_cents,dolly_charge_cents,security_deposit_cents,delivery_quote_status,tax_cents,estimated_due_before_delivery_cents,estimated_total_cents,exceptions_json,expires_at,is_synthetic)
    VALUES ('intent-source-1',1,'SUBMITTED','Synthetic Conversion Renter','synthetic@example.test','555-0100',1,1,'Synthetic tow vehicle',1,1,1,'Synthetic local use','IN_STATE',0,'PICKUP',0,'2027-10-10T15:00:00.000Z','2027-10-11T15:00:00.000Z',1,1,6000,1000,10000,'NOT_REQUESTED',0,17000,17000,'[]','2027-01-02T12:00:00.000Z',1);`)});
  afterEach(()=>raw.close());

  it('atomically creates a pending-review reservation and immutable audit trail',async()=>{const result=await convertSyntheticBookingIntent(db,request(),now);expect(result).toEqual({intentId:1,reservationId:1,confirmationCode:'SYN-CONVERT-1',idempotent:false,status:'PENDING_REVIEW'});expect(raw.prepare('SELECT status,is_synthetic,channel,rental_charge_cents,dolly_days FROM reservations').get()).toEqual({status:'PENDING_REVIEW',is_synthetic:1,channel:'DIRECT',rental_charge_cents:6000,dolly_days:1});expect(raw.prepare('SELECT status FROM booking_intents WHERE id=1').get()).toEqual({status:'CONVERTED'});expect(raw.prepare('SELECT count(*) total FROM audit_events').get()).toEqual({total:2});});
  it('returns the original reservation for the same idempotency key and rejects a changed key',async()=>{await convertSyntheticBookingIntent(db,request(),now);expect(await convertSyntheticBookingIntent(db,request(),now)).toMatchObject({reservationId:1,idempotent:true});await expect(convertSyntheticBookingIntent(db,request({idempotencyKey:'different-key'}),now)).rejects.toThrow(/different idempotency/);expect(raw.prepare('SELECT count(*) total FROM reservations').get()).toEqual({total:1});});
  it('fails closed for expiration, quote drift, qualification, approvals, and unsigned evidence',async()=>{raw.prepare("UPDATE booking_intents SET expires_at='2027-01-01T11:59:00.000Z'").run();await expect(convertSyntheticBookingIntent(db,request(),now)).rejects.toThrow(/expired/);raw.prepare("UPDATE booking_intents SET expires_at='2027-01-02T12:00:00.000Z',rental_charge_cents=6100").run();await expect(convertSyntheticBookingIntent(db,request(),now)).rejects.toThrow(/quote/);raw.prepare('UPDATE booking_intents SET rental_charge_cents=6000,insurance_acknowledged=0').run();await expect(convertSyntheticBookingIntent(db,request(),now)).rejects.toThrow(/Qualification/);raw.prepare("UPDATE booking_intents SET insurance_acknowledged=1,trip_type='INTERSTATE',interstate_approval_required=1").run();await expect(convertSyntheticBookingIntent(db,request(),now)).rejects.toThrow(/Interstate/);raw.prepare("UPDATE booking_intents SET trip_type='IN_STATE',interstate_approval_required=0").run();await expect(convertSyntheticBookingIntent(db,request({approval:{...approval,agreement:{...approval.agreement,status:'SIGNED',signedAt:'',templateHash:'a'.repeat(64)}}}),now)).rejects.toThrow(/agreement/);});
  it('rolls back every write when availability changes after the precheck',async()=>{const base=db;let raced=false;const racing:DatabasePort={...base,batch:async statements=>{if(!raced){raced=true;raw.exec("INSERT INTO customers(first_name,last_name) VALUES ('Concurrent','Owner'); INSERT INTO reservations(confirmation_code,trailer_id,customer_id,channel,status,pickup_at,return_at,rental_charge_cents,is_synthetic) VALUES ('CONCURRENT',1,last_insert_rowid(),'DIRECT','CONFIRMED','2027-10-10T16:00:00.000Z','2027-10-10T18:00:00.000Z',6000,1)")}return base.batch(statements)}};await expect(convertSyntheticBookingIntent(racing,request(),now)).rejects.toThrow(/TRAILER_SCHEDULE_CONFLICT/);expect(raw.prepare('SELECT count(*) total FROM booking_intent_conversions').get()).toEqual({total:0});expect(raw.prepare("SELECT count(*) total FROM reservations WHERE confirmation_code='SYN-CONVERT-1'").get()).toEqual({total:0});expect(raw.prepare("SELECT count(*) total FROM customers WHERE email='synthetic@example.test'").get()).toEqual({total:0});});
  it('rolls back customer, reservation, conversion, intent status, and audits on a late failure',async()=>{raw.exec("CREATE TRIGGER fail_conversion_audit BEFORE INSERT ON audit_events WHEN NEW.action='BOOKING_INTENT_CONVERTED' BEGIN SELECT RAISE(ABORT,'SYNTHETIC_AUDIT_FAILURE'); END;");await expect(convertSyntheticBookingIntent(db,request(),now)).rejects.toThrow(/SYNTHETIC_AUDIT_FAILURE/);expect(raw.prepare('SELECT count(*) total FROM customers').get()).toEqual({total:0});expect(raw.prepare('SELECT count(*) total FROM reservations').get()).toEqual({total:0});expect(raw.prepare('SELECT count(*) total FROM booking_intent_conversions').get()).toEqual({total:0});expect(raw.prepare('SELECT status FROM booking_intents').get()).toEqual({status:'SUBMITTED'});expect(raw.prepare('SELECT count(*) total FROM audit_events').get()).toEqual({total:0});});
});
