import { beforeEach,describe,expect,it } from 'vitest';
import type Database from 'better-sqlite3';
import { createLocalDatabasePort,migrate,openDatabase } from '../src/server/db/database.js';
import { createDirectCheckoutSession,finalizeDirectCheckout,getDirectCheckout,initiateDirectCheckoutPayment,signDirectCheckoutAgreement } from '../src/server/directCheckout.js';
import { createMockPaymentProvider } from '../src/server/paymentProvider.js';
import { canCheckoutTransition,checkoutOperationalState,directCheckoutBlockers } from '../src/shared/directCheckout.js';

let raw:Database.Database;const now=new Date('2027-01-01T12:00:00Z');
function seed(){raw.exec("INSERT INTO trailers(name,unit_code,published_payload_lbs) VALUES ('Synthetic Trailer','SYN-1',5200);INSERT INTO booking_intents(idempotency_key,trailer_id,status,legal_name,email,phone,age_25_confirmed,named_renter_only_towing,tow_vehicle_details,hitch_ball_acknowledged,brake_controller_acknowledged,insurance_acknowledged,intended_use,trip_type,interstate_approval_required,fulfillment_type,delivery_approval_required,pickup_at,return_at,dolly_requested,rental_days,rental_charge_cents,dolly_charge_cents,security_deposit_cents,delivery_quote_status,tax_cents,estimated_due_before_delivery_cents,estimated_total_cents,exceptions_json,expires_at,is_synthetic) VALUES ('intent_checkout_1',1,'SUBMITTED','Synthetic Direct Customer','synthetic-direct@example.test','480-555-0100',1,1,'2026 tow vehicle',1,1,1,'Synthetic local move','IN_STATE',0,'PICKUP',0,'2027-02-01T15:00:00.000Z','2027-02-02T15:00:00.000Z',1,1,6000,1000,10000,'NOT_REQUESTED',0,17000,17000,'[]','2027-01-01T12:30:00.000Z',1)")}
beforeEach(()=>{raw?.close();raw=openDatabase(':memory:');migrate(raw)});
describe('direct checkout orchestration',()=>{
 it('defines explicit safe transitions and derived expiry',()=>{expect(canCheckoutTransition('AGREEMENT_REQUIRED','AGREEMENT_SIGNED')).toBe(true);expect(canCheckoutTransition('PAYMENT_PENDING','COMPLETE')).toBe(false);expect(checkoutOperationalState('PAYMENT_REQUIRED','2027-01-01T11:59:00Z',now)).toBe('EXPIRED')});
 it('routes delivery, interstate, and review requests away from automatic checkout',()=>{expect(directCheckoutBlockers({is_synthetic:1,status:'REVIEW_REQUIRED',trip_type:'INTERSTATE',fulfillment_type:'DELIVERY',age_25_confirmed:1,named_renter_only_towing:1,hitch_ball_acknowledged:1,brake_controller_acknowledged:1,insurance_acknowledged:1})).toEqual(expect.arrayContaining(['OWNER_REVIEW_REQUIRED','INTERSTATE_OWNER_REVIEW','DELIVERY_OWNER_REVIEW']))});
 it('completes one idempotent authoritative happy path',async()=>{seed();const db=createLocalDatabasePort(raw);const created=await createDirectCheckoutSession(db,{intentId:1,idempotencyKey:'checkout_create_001',actor:'owner@example.test'},now);expect(created.state).toBe('AGREEMENT_REQUIRED');expect(JSON.stringify(raw.prepare('SELECT * FROM direct_checkout_sessions').get())).not.toContain(created.token);await signDirectCheckoutAgreement(db,{token:created.token!,csrfToken:created.csrfToken!,printedName:'Synthetic Direct Customer',inspectionChoice:'SEND_FORM',actor:'owner@example.test'},now);expect(()=>raw.prepare("UPDATE direct_checkout_agreements SET printed_name='Changed'").run()).toThrow(/CHECKOUT_AGREEMENT_IMMUTABLE/);expect((await initiateDirectCheckoutPayment(db,createMockPaymentProvider(),{token:created.token!,csrfToken:created.csrfToken!,actor:'owner@example.test',idempotencyKey:'checkout_payment_001'},now)).state).toBe('PAYMENT_COLLECTED');const result=await finalizeDirectCheckout(db,{token:created.token!,csrfToken:created.csrfToken!,actor:'owner@example.test',idempotencyKey:'checkout_convert_001'},now);expect(result.state).toBe('COMPLETE');expect(raw.prepare('SELECT status,channel,is_synthetic FROM reservations').get()).toEqual({status:'CONFIRMED',channel:'DIRECT',is_synthetic:1});expect(raw.prepare('SELECT status,pickup_inspection_choice FROM agreement_instances').get()).toEqual({status:'SIGNED',pickup_inspection_choice:'SEND_FORM'});expect(raw.prepare("SELECT count(1) total FROM payment_ledger_entries WHERE kind='PAYMENT_COLLECTED' AND reservation_id IS NOT NULL").get()).toEqual({total:1});expect(raw.prepare('SELECT communication_type,state FROM communication_records').get()).toEqual({communication_type:'BOOKING_CONFIRMATION',state:'SEND_UNAVAILABLE'});expect(raw.prepare('SELECT count(1) total FROM secure_links').get()).toEqual({total:2});expect((await finalizeDirectCheckout(db,{token:created.token!,csrfToken:created.csrfToken!,actor:'owner@example.test',idempotencyKey:'checkout_convert_001'},now)).idempotent).toBe(true);expect(raw.prepare('SELECT count(1) total FROM reservations').get()).toEqual({total:1})});
 it('rejects a cross-session token and derives expiration without deleting audit history',async()=>{seed();const db=createLocalDatabasePort(raw);const created=await createDirectCheckoutSession(db,{intentId:1,idempotencyKey:'checkout_create_002',actor:'owner@example.test'},now);await expect(getDirectCheckout(db,'x'.repeat(48),now)).rejects.toThrow('Checkout session not found.');expect((await getDirectCheckout(db,created.token!,new Date('2027-01-01T12:31:00Z'))).state).toBe('EXPIRED');expect(raw.prepare("SELECT count(1) total FROM audit_events WHERE aggregate_type='DIRECT_CHECKOUT'").get()).toEqual({total:1})});
 it('leaves payment auditable and creates no reservation when availability changes',async()=>{seed();const db=createLocalDatabasePort(raw);const created=await createDirectCheckoutSession(db,{intentId:1,idempotencyKey:'checkout_create_003',actor:'owner@example.test'},now);await signDirectCheckoutAgreement(db,{token:created.token!,csrfToken:created.csrfToken!,printedName:'Synthetic Direct Customer',inspectionChoice:'DECLINE_FORM',actor:'owner@example.test'},now);await initiateDirectCheckoutPayment(db,createMockPaymentProvider(),{token:created.token!,csrfToken:created.csrfToken!,actor:'owner@example.test',idempotencyKey:'checkout_payment_003'},now);raw.prepare("INSERT INTO availability_blocks(trailer_id,start_at,end_at,reason,is_synthetic) VALUES (1,'2027-02-01T16:00:00Z','2027-02-01T17:00:00Z','Concurrent hold',1)").run();await expect(finalizeDirectCheckout(db,{token:created.token!,csrfToken:created.csrfToken!,actor:'owner@example.test',idempotencyKey:'checkout_convert_003'},now)).rejects.toThrow('no longer available');expect(raw.prepare('SELECT count(1) total FROM reservations').get()).toEqual({total:0});expect(raw.prepare('SELECT state FROM direct_checkout_sessions').get()).toEqual({state:'PAYMENT_COLLECTED'})});
});
