import { describe,expect,it,vi } from 'vitest';
import { APPROVED_GMAIL_SENDER,createAuthorizationRequest,createGmailTransport,decryptToken,encryptToken,gmailConfiguration,gmailRetryDecision,GMAIL_CALLBACK_PATH,GMAIL_SEND_SCOPE,pkceChallenge,secureRandomToken } from '../src/server/gmailIntegration.js';

type RequestInfo=string|URL|Request;

const key=btoa(String.fromCharCode(...new Uint8Array(32).fill(7))).replace(/=+$/,'');
const configuration={clientId:'synthetic-client.apps.googleusercontent.test',clientSecret:'synthetic-secret',tokenEncryptionKey:key,approvedSender:APPROVED_GMAIL_SENDER,testRecipient:APPROVED_GMAIL_SENDER};
describe('Gmail test-mode integration safety',()=>{
 it('creates one-use OAuth state and S256 PKCE without broad Gmail scopes',async()=>{const request=await createAuthorizationRequest(configuration,`https://staging.example.test${GMAIL_CALLBACK_PATH}`);const url=new URL(request.authorizationUrl);expect(request.state).not.toBe(request.verifier);expect(url.searchParams.get('state')).toBe(request.state);expect(url.searchParams.get('code_challenge')).toBe(await pkceChallenge(request.verifier));expect(url.searchParams.get('code_challenge_method')).toBe('S256');expect(url.searchParams.get('scope')?.split(' ')).toEqual(['openid','email',GMAIL_SEND_SCOPE]);expect(url.searchParams.get('scope')).not.toMatch(/gmail\.(readonly|modify|compose)|drive|calendar|contacts/)});
 it('encrypts tokens with authenticated encryption and rejects a wrong key',async()=>{const encrypted=await encryptToken('synthetic-refresh-token',key);expect(JSON.stringify(encrypted)).not.toContain('synthetic-refresh-token');expect(await decryptToken(encrypted,key)).toBe('synthetic-refresh-token');const wrong=btoa(String.fromCharCode(...new Uint8Array(32).fill(9))).replace(/=+$/,'');await expect(decryptToken(encrypted,wrong)).rejects.toThrow('TOKEN_DECRYPTION_FAILED')});
 it('fails closed unless every binding and exact owner mailbox restriction is present',()=>{expect(gmailConfiguration({})).toMatchObject({configured:false,reason:'CONFIGURATION_MISSING'});expect(gmailConfiguration({GMAIL_OAUTH_CLIENT_ID:'x',GMAIL_OAUTH_CLIENT_SECRET:'y',GMAIL_TOKEN_ENCRYPTION_KEY:key,GMAIL_TEST_RECIPIENT:'customer@example.test'})).toMatchObject({configured:false,reason:'OWNER_MAILBOX_MISMATCH'});expect(gmailConfiguration({GMAIL_OAUTH_CLIENT_ID:'x',GMAIL_OAUTH_CLIENT_SECRET:'y',GMAIL_TOKEN_ENCRYPTION_KEY:key,GMAIL_TEST_RECIPIENT:APPROVED_GMAIL_SENDER})).toMatchObject({configured:true,reason:null})});
 it('uses a stable message identifier and reports provider acceptance without delivery claims',async()=>{const fetcher=vi.fn(async(_url:RequestInfo|URL,init?:RequestInit)=>{const decoded=atob(String(JSON.parse(String(init?.body)).raw).replace(/-/g,'+').replace(/_/g,'/'));expect(decoded).toContain('Message-ID: <stable-123@rental-os.invalid>');expect(decoded).toContain(`To: ${APPROVED_GMAIL_SENDER}`);return Response.json({id:'synthetic-provider-id'})});const result=await createGmailTransport(fetcher as typeof fetch).send({accessToken:'synthetic-access',sender:APPROVED_GMAIL_SENDER,recipient:APPROVED_GMAIL_SENDER,subject:'Synthetic subject',body:'Synthetic body',stableMessageId:'stable-123'});expect(result).toEqual({state:'ACCEPTED_BY_GMAIL',providerMessageId:'synthetic-provider-id'});expect(fetcher).toHaveBeenCalledTimes(1)});
 it.each([[401,'AUTHORIZATION_REVOKED'],[429,'PROVIDER_RATE_LIMITED'],[500,'PROVIDER_REJECTED']])('classifies provider failure %s safely',async(status,category)=>{const transport=createGmailTransport(vi.fn(async()=>new Response('{}',{status})) as typeof fetch);expect(await transport.send({accessToken:'synthetic',sender:APPROVED_GMAIL_SENDER,recipient:APPROVED_GMAIL_SENDER,subject:'x',body:'x',stableMessageId:secureRandomToken()})).toEqual({state:'FAILED',safeErrorClassification:category})});
 it('returns unknown rather than claiming delivery after an uncertain network result',async()=>{const transport=createGmailTransport(vi.fn(async()=>{throw new Error('sensitive upstream detail')}) as typeof fetch);expect(await transport.send({accessToken:'synthetic',sender:APPROVED_GMAIL_SENDER,recipient:APPROVED_GMAIL_SENDER,subject:'x',body:'x',stableMessageId:'stable'})).toEqual({state:'UNKNOWN',safeErrorClassification:'PROVIDER_UNREACHABLE'})});
 it('blocks sending and accepted retries while requiring a reason after failed or unknown attempts',()=>{expect(gmailRetryDecision(undefined,undefined)).toMatchObject({allowed:true});expect(gmailRetryDecision('SENDING',undefined)).toEqual({allowed:false,reason:'DUPLICATE_SEND_BLOCKED'});expect(gmailRetryDecision('ACCEPTED_BY_GMAIL','try again')).toEqual({allowed:false,reason:'DUPLICATE_SEND_BLOCKED'});expect(gmailRetryDecision('FAILED',undefined)).toEqual({allowed:false,reason:'OWNER_OVERRIDE_REASON_REQUIRED'});expect(gmailRetryDecision('UNKNOWN','Owner verified no acceptance')).toMatchObject({allowed:true})});
});
