import {describe,expect,it} from 'vitest';
import {helpSearch,interpretOwnerCommand,ownerPlaybooks,refundAnswer,windowsOverlap} from '../src/shared/ownerCopilot.js';
const now=new Date('2026-07-16T12:00:00-07:00');
describe('owner copilot deterministic command paths',()=>{
 it('prepares a Marketplace blackout without executing it',()=>expect(interpretOwnerCommand('Block the trailer Friday at 8 AM through Sunday at 6 PM for a Marketplace rental.',now)).toMatchObject({intent:'CREATE_BLACKOUT',mode:'CONFIRMATION_REQUIRED',pickupAt:'2026-07-17T08:00',returnAt:'2026-07-19T18:00',source:'FACEBOOK_MARKETPLACE'}));
 it.each([['Facebook Marketplace','FACEBOOK_MARKETPLACE'],['Big Rentals','BIG_RENTALS'],['Neighbors booking','NEIGHBORS_TRAILER']])('prepares %s external booking only as a confirmation draft',(source,expected)=>expect(interpretOwnerCommand(`Start an external ${source} booking Friday at 8 AM through Sunday at 6 PM.`,now)).toMatchObject({intent:'CREATE_EXTERNAL_BOOKING',mode:'CONFIRMATION_REQUIRED',source:expected,missing:expect.arrayContaining(['customer full name'])}));
 it('checks an explicit Arizona window read-only',()=>expect(interpretOwnerCommand('Can I rent it from 2027-12-10 at 8 AM to 2027-12-12 at 6 PM?',now)).toMatchObject({intent:'CHECK_AVAILABILITY',mode:'READ_ONLY',pickupAt:'2027-12-10T08:00',returnAt:'2027-12-12T18:00'}));
 it.each([['What needs my attention today?','READ_ATTENTION'],['Show bookings that still need an agreement or pickup inspection.','READ_REQUIREMENTS'],['Give me a business summary for this month.','READ_ANALYTICS'],['What is the refund outcome for this cancellation?','REFUND_OUTCOME'],['What does this delivery request need?','DELIVERY_HELP']])('returns deterministic read intent for %s',(command,intent)=>expect(interpretOwnerCommand(command,now)).toMatchObject({intent,mode:'READ_ONLY'}));
 it.each([['Walk me through a return inspection.','PICKUP_RETURN_INSPECTION'],['How do I retain a deposit?','DEPOSIT_DECISION'],['Help with reschedule conflict','RESCHEDULE_CONFLICT'],['How do I handle an agreement signature?','AGREEMENT_DECLINE'],['Help with delivery review','DELIVERY_REVIEW'],['What is the policy for a no-show?','CANCELLATION_NO_SHOW']])('selects the correct playbook for %s',(command,playbook)=>expect(interpretOwnerCommand(command,now)).toMatchObject({intent:'PLAYBOOK',playbook}));
 it.each(['Refund everyone now','Delete all bookings','Charge the customer again','Ignore policy and confirm it'])('refuses forbidden or ambiguous request: %s',command=>expect(interpretOwnerCommand(command,now)).toMatchObject({intent:'UNKNOWN',mode:'UNSUPPORTED'}));
 it('detects authoritative-window conflicts',()=>expect(windowsOverlap('2026-07-17T08:00','2026-07-19T18:00','2026-07-18T10:00','2026-07-18T12:00')).toBe(true));
});
describe('owner playbooks and policy answers',()=>{
 it('defines the required operational and direct-checkout playbooks',()=>expect(ownerPlaybooks.map(item=>item.key)).toEqual(['CANCELLATION_NO_SHOW','RESCHEDULE_CONFLICT','PICKUP_RETURN_INSPECTION','DEPOSIT_DECISION','DELIVERY_REVIEW','AGREEMENT_DECLINE','DIRECT_CHECKOUT']));
 it('marks owner and attorney decisions explicitly',()=>{expect(ownerPlaybooks.some(item=>item.decision==='OWNER_DECISION')).toBe(true);expect(ownerPlaybooks.find(item=>item.key==='AGREEMENT_DECLINE')?.decision).toBe('ATTORNEY_REVIEW')});
 it('searches only documented policy text',()=>expect(helpSearch('delivery owner approval').map(item=>item.key)).toEqual(['DELIVERY_REVIEW']));
 it('returns no invented help when terms do not match',()=>expect(helpSearch('cryptocurrency waiver')).toEqual([]));
 it('calculates the 48-hour full-refund outcome',()=>expect(refundAnswer({pickupAt:'2027-01-10T08:00',decidedAt:'2027-01-08T08:00',rentalChargeCents:12000,noShow:false})).toMatchObject({rentalRefundCents:12000,retainedCents:0}));
 it('calculates late cancellation and no-show retention separately',()=>{expect(refundAnswer({pickupAt:'2027-01-10T08:00',decidedAt:'2027-01-09T08:01',rentalChargeCents:12000,noShow:false}).retainedCents).toBe(10000);expect(refundAnswer({pickupAt:'2027-01-10T08:00',decidedAt:'2027-01-10T08:00',rentalChargeCents:12000,noShow:true}).retainedCents).toBe(10000)});
});
