import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import type Database from 'better-sqlite3';
import { cancellationRefund, depositRefund, paymentBreakdown } from '../src/shared/payments.js';
import { createMockPaymentProvider } from '../src/server/paymentProvider.js';
import { migrate, openDatabase } from '../src/server/db/database.js';

describe('payment policy contracts',()=>{
 it('itemizes rental, dolly, approved delivery, collected deposit, and no tax',()=>expect(paymentBreakdown({rentalChargeCents:12_000,dollyDays:2,deliveryChargeCents:4_000})).toEqual({rentalCents:12_000,dollyCents:2_000,deliveryCents:4_000,depositCents:10_000,taxCents:0,totalCents:28_000}));
 it('refunds everything at the 48-hour boundary',()=>expect(cancellationRefund({paid:paymentBreakdown({rentalChargeCents:12_000,dollyDays:1,deliveryChargeCents:2_000}),pickupAt:new Date('2027-01-03T12:00:00Z'),decidedAt:new Date('2027-01-01T12:00:00Z'),noShow:false})).toMatchObject({refundCents:25_000,retainedCents:0,policy:'FULL_REFUND'}));
 it('retains only $100 for late cancellation and no-show',()=>{const paid=paymentBreakdown({rentalChargeCents:12_000,dollyDays:1,deliveryChargeCents:2_000});expect(cancellationRefund({paid,pickupAt:new Date('2027-01-03T11:59:59Z'),decidedAt:new Date('2027-01-01T12:00:00Z'),noShow:false})).toMatchObject({refundCents:15_000,retainedCents:10_000});expect(cancellationRefund({paid,pickupAt:new Date('2027-01-10T12:00:00Z'),decidedAt:new Date('2027-01-01T12:00:00Z'),noShow:true})).toMatchObject({refundCents:15_000,retainedCents:10_000})});
 it('caps deposit refunds at the amount collected and never creates an extra charge',()=>{expect(depositRefund(8_000)).toBe(8_000);expect(depositRefund(20_000)).toBe(10_000);expect(depositRefund(-1)).toBe(0)});
});

describe('deterministic payment provider contract',()=>{
 it('deduplicates payment and refund retries by idempotency key',async()=>{const provider=createMockPaymentProvider();const input={amountCents:20_000,currency:'usd' as const,idempotencyKey:'pay-one',metadata:{reservationId:'1',synthetic:'true' as const}};expect(await provider.createPayment(input)).toEqual(await provider.createPayment(input));const refund={providerPaymentId:'mock',amountCents:10_000,idempotencyKey:'refund-one',reason:'test'};expect(await provider.createRefund(refund)).toEqual(await provider.createRefund(refund))});
 it('models refused payments and failed refunds without card data',async()=>{expect((await createMockPaymentProvider({failPayments:true}).createPayment({amountCents:1,currency:'usd',idempotencyKey:'decline',metadata:{reservationId:'1',synthetic:'true'}})).status).toBe('FAILED');expect((await createMockPaymentProvider({failRefunds:true}).createRefund({providerPaymentId:'mock',amountCents:1,idempotencyKey:'refund-fail',reason:'test'})).status).toBe('FAILED')});
 it('verifies the mock webhook contract and rejects replay signatures',async()=>{const provider=createMockPaymentProvider();await expect(provider.verifyWebhook('{"id":"evt_1","type":"payment.updated","status":"succeeded"}','bad')).rejects.toThrow(/verification/);await expect(provider.verifyWebhook('{"id":"evt_1","type":"payment.updated","status":"succeeded"}','mock-valid')).resolves.toMatchObject({providerEventId:'evt_1',status:'succeeded'})});
});

describe('durable payment persistence',()=>{let db:Database.Database;beforeEach(()=>{db=openDatabase(':memory:');migrate(db);db.exec("INSERT INTO trailers(name,unit_code,published_payload_lbs) VALUES ('T','T',5200); INSERT INTO reservations(confirmation_code,trailer_id,channel,status,pickup_at,return_at,is_synthetic) VALUES ('P',1,'DIRECT','CONFIRMED','2027-01-01T13:00:00Z','2027-01-02T13:00:00Z',1)")});afterEach(()=>db.close());
 it('enforces ledger idempotency and append-only history',()=>{db.prepare("INSERT INTO payment_ledger_entries(reservation_id,kind,status,amount_cents,idempotency_key) VALUES (1,'PAYMENT_COLLECTED','SUCCEEDED',10000,'one')").run();expect(()=>db.prepare("INSERT INTO payment_ledger_entries(reservation_id,kind,status,amount_cents,idempotency_key) VALUES (1,'PAYMENT_COLLECTED','SUCCEEDED',10000,'one')").run()).toThrow();expect(()=>db.prepare("UPDATE payment_ledger_entries SET amount_cents=1").run()).toThrow(/PAYMENT_LEDGER_IMMUTABLE/);expect(()=>db.prepare('DELETE FROM payment_ledger_entries').run()).toThrow(/PAYMENT_LEDGER_IMMUTABLE/)});
 it('deduplicates webhook events and stores only a hash plus sanitized fields',()=>{db.prepare("INSERT INTO payment_webhook_events(provider_event_id,event_type,processing_status,sanitized_status,payload_hash,provider_created_at) VALUES ('evt','payment.updated','PROCESSED','succeeded','hash','2027-01-01T00:00:00Z')").run();expect(()=>db.prepare("INSERT INTO payment_webhook_events(provider_event_id,event_type,processing_status,sanitized_status,payload_hash,provider_created_at) VALUES ('evt','payment.updated','PROCESSED','succeeded','hash','2027-01-01T00:00:00Z')").run()).toThrow()});
});
