import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import type Database from 'better-sqlite3';
import { handleApiRequest } from '../src/server/api.js';
import { createLocalDatabasePort, migrate, openDatabase } from '../src/server/db/database.js';
import { createMockPaymentProvider } from '../src/server/paymentProvider.js';

let raw:Database.Database;
const env=()=>({ENVIRONMENT:'development' as const,AUTH_MODE:'mock' as const,ALLOWED_OWNER_EMAIL:'owner@example.test',DB:createLocalDatabasePort(raw)});
const call=(path:string,init:RequestInit={},provider=createMockPaymentProvider())=>handleApiRequest(new Request(`http://local${path}`,{...init,headers:{'content-type':'application/json','x-dev-owner-email':'owner@example.test',...init.headers}}),env(),{now:()=>new Date('2027-01-01T12:00:00Z'),paymentProvider:provider});
beforeEach(()=>{raw=openDatabase(':memory:');migrate(raw);raw.exec("INSERT INTO trailers(name,unit_code,published_payload_lbs) VALUES ('T','T',5200); INSERT INTO customers(first_name,last_name) VALUES ('Synthetic','Renter'); INSERT INTO reservations(confirmation_code,trailer_id,customer_id,channel,status,pickup_at,return_at,rental_charge_cents,dolly_days,renter_age,named_renter_will_tow,is_synthetic) VALUES ('PAY',1,1,'DIRECT','CONFIRMED','2027-02-01T15:00:00Z','2027-02-02T15:00:00Z',6000,1,30,1,1); INSERT INTO agreement_templates(version,source_manifest_version,content_json,content_hash) VALUES ('v','v','{}','hash'); INSERT INTO agreement_instances(reservation_id,template_id,status,template_version,template_hash,renter_snapshot_json,reservation_snapshot_json,quote_snapshot_json,rendered_at,signed_at,printed_name) VALUES (1,1,'SIGNED','v','hash','{}','{}','{}','2027-01-01T00:00:00Z','2027-01-01T00:00:00Z','Synthetic Renter')")});afterEach(()=>raw.close());

describe('protected mock payment API',()=>{
 it('returns an authoritative itemization and never records a client price',async()=>{const response=await call('/api/reservations/1/payment-preview');expect(response.status).toBe(200);expect(await response.json()).toMatchObject({breakdown:{rentalCents:6000,dollyCents:1000,deliveryCents:0,depositCents:10000,taxCents:0,totalCents:17000},ready:true,testOnly:true,liveProcessorConnected:false})});
 it('collects synthetically without confirming or changing reservation status',async()=>{const provider=createMockPaymentProvider();const payload={action:'COLLECT',idempotencyKey:'collect_payment_0001',reason:'Synthetic owner rehearsal',amountCents:1};const first=await call('/api/reservations/1/payment-actions',{method:'POST',body:JSON.stringify(payload)},provider);expect(first.status).toBe(201);expect(await first.json()).toMatchObject({kind:'PAYMENT_COLLECTED',amountCents:17000,testOnly:true});const duplicate=await call('/api/reservations/1/payment-actions',{method:'POST',body:JSON.stringify(payload)},provider);expect(duplicate.status).toBe(200);expect(await duplicate.json()).toMatchObject({idempotent:true});expect(raw.prepare('SELECT status FROM reservations').get()).toEqual({status:'CONFIRMED'});expect(raw.prepare('SELECT count(*) total FROM payment_ledger_entries').get()).toEqual({total:1});expect(raw.prepare("SELECT count(*) total FROM audit_events WHERE action='PAYMENT_LEDGER_APPENDED'").get()).toEqual({total:1})});
 it('fails closed when qualification and owner approvals are incomplete',async()=>{raw.exec("UPDATE reservations SET renter_age=20,delivery_requested=1,delivery_approved=0,interstate_use=1,interstate_approved=0");const response=await call('/api/reservations/1/payment-actions',{method:'POST',body:JSON.stringify({action:'COLLECT',idempotencyKey:'blocked_payment_001',reason:'Synthetic readiness test'})});expect(response.status).toBe(409);const result=await response.json() as {blockers:string[]};expect(result.blockers.length).toBeGreaterThanOrEqual(3);expect(raw.prepare('SELECT count(*) total FROM payment_ledger_entries').get()).toEqual({total:0})});
 it('records a failed provider attempt without changing the reservation',async()=>{const response=await call('/api/reservations/1/payment-actions',{method:'POST',body:JSON.stringify({action:'COLLECT',idempotencyKey:'failed_payment_0001',reason:'Synthetic decline test'})},createMockPaymentProvider({failPayments:true}));expect(response.status).toBe(201);expect(await response.json()).toMatchObject({kind:'PAYMENT_FAILED',status:'FAILED'});expect(raw.prepare('SELECT status FROM reservations').get()).toEqual({status:'CONFIRMED'})});
 it('verifies and deduplicates sanitized webhook rehearsals',async()=>{const event=JSON.stringify({id:'evt_test_1',type:'payment.updated',paymentId:'mock_pay',status:'succeeded',createdAt:'2027-01-01T00:00:00Z'});expect((await call('/api/payments/webhooks/mock',{method:'POST',headers:{'x-mock-signature':'bad'},body:event})).status).toBe(401);const first=await call('/api/payments/webhooks/mock',{method:'POST',headers:{'x-mock-signature':'mock-valid'},body:event});expect(first.status).toBe(201);const duplicate=await call('/api/payments/webhooks/mock',{method:'POST',headers:{'x-mock-signature':'mock-valid'},body:event});expect(await duplicate.json()).toEqual({duplicate:true,processed:false});const stored=raw.prepare('SELECT processing_status,sanitized_status,length(payload_hash) hash_length FROM payment_webhook_events').get();expect(stored).toEqual({processing_status:'PROCESSED',sanitized_status:'succeeded',hash_length:64});expect(JSON.stringify(stored)).not.toContain('payment.updated')});
 it('rolls back ledger insertion if its immutable audit event fails',async()=>{raw.exec("CREATE TRIGGER fail_payment_audit BEFORE INSERT ON audit_events WHEN NEW.action='PAYMENT_LEDGER_APPENDED' BEGIN SELECT RAISE(ABORT,'forced'); END;");const response=await call('/api/reservations/1/payment-actions',{method:'POST',body:JSON.stringify({action:'COLLECT',idempotencyKey:'rollback_pay_0001',reason:'Synthetic rollback test'})});expect(response.status).toBe(500);expect(raw.prepare('SELECT count(*) total FROM payment_ledger_entries').get()).toEqual({total:0})});
});
