import { beforeEach, describe, expect, it } from 'vitest';
import { handleApiRequest } from '../src/server/api.js';
import { createLocalDatabasePort, migrate, openDatabase } from '../src/server/db/database.js';
import type Database from 'better-sqlite3';
import { toArizonaInput } from '../src/shared/arizonaTime.js';
let raw: Database.Database; const env=()=>({ENVIRONMENT:'development' as const,AUTH_MODE:'mock' as const,ALLOWED_OWNER_EMAIL:'owner@example.test',DB:createLocalDatabasePort(raw)});
const request=(path:string,init:RequestInit={})=>handleApiRequest(new Request(`http://local${path}`,{...init,headers:{'content-type':'application/json','x-dev-owner-email':'owner@example.test',...init.headers}}),env(),{now:()=>new Date('2027-01-01T12:00:00Z')});
beforeEach(()=>{raw?.close();raw=openDatabase(':memory:');migrate(raw);raw.prepare("INSERT INTO trailers(name,unit_code,published_payload_lbs) VALUES ('Trailer','T1',5200)").run();});
describe('portable API',()=>{
 it('serves owner-only deterministic analytics and excludes synthetic records by default',async()=>{raw.exec("INSERT INTO customers(first_name,last_name) VALUES ('A','B'); INSERT INTO reservations(confirmation_code,trailer_id,customer_id,channel,status,pickup_at,return_at,rental_charge_cents,is_synthetic) VALUES ('REAL',1,1,'DIRECT','CONFIRMED','2027-07-01T15:00:00.000Z','2027-07-01T19:00:00.000Z',10000,0),('SYNTH',1,1,'DIRECT','CONFIRMED','2027-07-02T15:00:00.000Z','2027-07-02T19:00:00.000Z',90000,1)");const excluded=await (await request('/api/analytics?startDate=2027-07-01&endDate=2027-07-31')).json() as {current:{reservationRequests:number;activeCompletedRentals:number;bookedRevenueCents:number};includeSynthetic:boolean};expect(excluded).toMatchObject({current:{reservationRequests:1,activeCompletedRentals:1,bookedRevenueCents:10000},includeSynthetic:false});const included=await (await request('/api/analytics?startDate=2027-07-01&endDate=2027-07-31&includeSynthetic=true')).json() as {current:{reservationRequests:number;activeCompletedRentals:number;bookedRevenueCents:number};includeSynthetic:boolean};expect(included).toMatchObject({current:{reservationRequests:2,activeCompletedRentals:2,bookedRevenueCents:100000},includeSynthetic:true});});
 it('persists and audits explicit synthetic classification on staging QA records',async()=>{const response=await request('/api/reservations/external',{method:'POST',body:JSON.stringify({trailerId:1,customerName:'Synthetic QA',source:'OTHER',pickupAt:'2027-10-01T08:00',returnAt:'2027-10-01T10:00',rentalChargeCents:10000,isSynthetic:true})});expect(response.status).toBe(201);expect(raw.prepare('SELECT is_synthetic FROM reservations').get()).toEqual({is_synthetic:1});const audit=raw.prepare("SELECT payload_json FROM audit_events WHERE action='EXTERNAL_BOOKING_CREATED'").get() as {payload_json:string};expect(JSON.parse(audit.payload_json)).toMatchObject({isSynthetic:true});});
 it('persists and audits synthetic classification for staging QA blackouts',async()=>{const response=await request('/api/availability-blocks',{method:'POST',body:JSON.stringify({trailerId:1,startAt:'2027-10-02T08:00',endAt:'2027-10-02T10:00',reason:'Synthetic QA hold',isSynthetic:true})});expect(response.status).toBe(201);expect(raw.prepare('SELECT is_synthetic FROM availability_blocks').get()).toEqual({is_synthetic:1});const audit=raw.prepare("SELECT payload_json FROM audit_events WHERE action='BLACKOUT_CREATED'").get() as {payload_json:string};expect(JSON.parse(audit.payload_json)).toMatchObject({isSynthetic:true});});
 it.each([
  ['winter','2027-01-15T08:30','2027-01-15T10:30','2027-01-15T15:30:00.000Z'],
  ['summer','2027-07-15T08:30','2027-07-15T10:30','2027-07-15T15:30:00.000Z'],
 ])('round-trips Arizona %s reservation wall time through API and persistence',async(_season,pickupAt,returnAt,storedPickup)=>{const response=await request('/api/reservations/external',{method:'POST',body:JSON.stringify({trailerId:1,customerName:`Arizona ${_season}`,source:'OTHER',pickupAt,returnAt,rentalChargeCents:10000})});expect(response.status).toBe(201);expect(raw.prepare('SELECT pickup_at FROM reservations').get()).toEqual({pickup_at:storedPickup});const dashboard=await (await request('/api/dashboard')).json() as {reservations:{pickup_at:string}[]};expect(toArizonaInput(dashboard.reservations[0].pickup_at)).toBe(pickupAt);});
 it('preserves Arizona wall time through blackout creation and its audit payload',async()=>{const response=await request('/api/availability-blocks',{method:'POST',body:JSON.stringify({trailerId:1,startAt:'2027-08-20T06:30',endAt:'2027-08-20T09:00',reason:'Arizona time test'})});expect(response.status).toBe(201);expect(raw.prepare('SELECT start_at,end_at FROM availability_blocks').get()).toEqual({start_at:'2027-08-20T13:30:00.000Z',end_at:'2027-08-20T16:00:00.000Z'});const audit=raw.prepare("SELECT payload_json FROM audit_events WHERE action='BLACKOUT_CREATED'").get() as {payload_json:string};expect(JSON.parse(audit.payload_json)).toMatchObject({startAt:'2027-08-20T13:30:00.000Z',endAt:'2027-08-20T16:00:00.000Z'});});
 it('revalidates and preserves Arizona wall time when rescheduling',async()=>{raw.exec("INSERT INTO customers(first_name,last_name) VALUES ('A','B'); INSERT INTO reservations(confirmation_code,trailer_id,customer_id,channel,status,pickup_at,return_at,rental_charge_cents) VALUES ('AZ-EDIT',1,1,'DIRECT','CONFIRMED','2027-09-01T13:00:00.000Z','2027-09-01T15:00:00.000Z',10000)");const response=await request('/api/reservations/1',{method:'PATCH',body:JSON.stringify({version:1,pickupAt:'2027-09-02T08:30',returnAt:'2027-09-02T11:00',rentalChargeCents:10000,dollyDays:0,reason:'Arizona time regression'})});expect(response.status).toBe(200);expect(raw.prepare('SELECT pickup_at,return_at FROM reservations WHERE id=1').get()).toEqual({pickup_at:'2027-09-02T15:30:00.000Z',return_at:'2027-09-02T18:00:00.000Z'});const audit=raw.prepare("SELECT payload_json FROM audit_events WHERE action='RESERVATION_EDITED'").get() as {payload_json:string};expect(JSON.parse(audit.payload_json).after).toMatchObject({pickup_at:'2027-09-02T15:30:00.000Z',return_at:'2027-09-02T18:00:00.000Z'});});
 it('creates external bookings and rejects overlap at the data layer',async()=>{const payload={trailerId:1,customerName:'Test Owner',source:'OTHER',pickupAt:'2027-04-01T13:00:00Z',returnAt:'2027-04-02T13:00:00Z',rentalChargeCents:10000};expect((await request('/api/reservations/external',{method:'POST',body:JSON.stringify(payload)})).status).toBe(201);expect((await request('/api/reservations/external',{method:'POST',body:JSON.stringify({...payload,customerName:'Overlap Owner'})})).status).toBe(409);expect((raw.prepare('SELECT actor FROM audit_events').get() as {actor:string}).actor).toBe('owner@example.test');});
 it('rejects hosted inspection references',async()=>{raw.exec("INSERT INTO customers(first_name,last_name) VALUES ('A','B'); INSERT INTO reservations(confirmation_code,trailer_id,customer_id,channel,status,pickup_at,return_at,rental_charge_cents) VALUES ('X',1,1,'DIRECT','CONFIRMED','2027-05-01T13:00:00Z','2027-05-02T13:00:00Z',10000)");const response=await request('/api/reservations/1/inspections/pickup',{method:'POST',body:JSON.stringify({conditionNotes:'Good condition',photoReferences:['https://hosted.example/photo.jpg']})});expect(response.status).toBe(400);expect(await response.json()).toMatchObject({error:expect.stringContaining('not accepted')});});
 it.each(['https://hosted.example/photo.jpg','file:///photo.jpg','C:\\photos\\damage.jpg','/var/photos/damage.jpg','../damage.jpg'])('rejects hosted URL or filesystem-shaped photo metadata: %s',async(reference)=>{raw.exec("INSERT OR IGNORE INTO customers(id,first_name,last_name) VALUES (1,'A','B'); INSERT OR IGNORE INTO reservations(id,confirmation_code,trailer_id,customer_id,channel,status,pickup_at,return_at,rental_charge_cents) VALUES (1,'X',1,1,'DIRECT','CONFIRMED','2027-05-01T13:00:00Z','2027-05-02T13:00:00Z',10000)");const response=await request('/api/reservations/1/inspections/pickup',{method:'POST',body:JSON.stringify({conditionNotes:'Good condition',photoReferences:[reference]})});expect(response.status).toBe(400);expect(raw.prepare('SELECT count(*) total FROM inspection_photos').get()).toEqual({total:0});});
 it('rolls back a reschedule if its audit event fails',async()=>{raw.exec("INSERT INTO customers(first_name,last_name) VALUES ('A','B'); INSERT INTO reservations(confirmation_code,trailer_id,customer_id,channel,status,pickup_at,return_at,rental_charge_cents) VALUES ('EDIT',1,1,'DIRECT','CONFIRMED','2027-06-01T13:00:00Z','2027-06-02T13:00:00Z',10000); CREATE TRIGGER fail_edit_audit BEFORE INSERT ON audit_events WHEN NEW.action='RESERVATION_EDITED' BEGIN SELECT RAISE(ABORT,'forced audit failure'); END;");const response=await request('/api/reservations/1',{method:'PATCH',body:JSON.stringify({version:1,pickupAt:'2027-06-03T13:00:00Z',returnAt:'2027-06-04T13:00:00Z',rentalChargeCents:10000,dollyDays:0,reason:'test rollback'})});expect(response.status).toBe(400);expect(await response.json()).toEqual({error:'The request could not be completed.'});expect(raw.prepare('SELECT pickup_at,version FROM reservations WHERE id=1').get()).toEqual({pickup_at:'2027-06-01T13:00:00Z',version:1});});
 it('rolls back cancellation outcome and status if audit creation fails',async()=>{raw.exec("INSERT INTO customers(first_name,last_name) VALUES ('A','B'); INSERT INTO reservations(confirmation_code,trailer_id,customer_id,channel,status,pickup_at,return_at,rental_charge_cents) VALUES ('CANCEL',1,1,'DIRECT','CONFIRMED','2027-07-01T13:00:00Z','2027-07-02T13:00:00Z',10000); CREATE TRIGGER fail_cancel_audit BEFORE INSERT ON audit_events WHEN NEW.action='CANCELLATION_OUTCOME_RECORDED' BEGIN SELECT RAISE(ABORT,'forced audit failure'); END;");const response=await request('/api/reservations/1/outcome',{method:'POST',body:JSON.stringify({type:'CANCELLATION',notes:'Owner cancellation'})});expect(response.status).toBe(400);expect(raw.prepare('SELECT status FROM reservations WHERE id=1').get()).toEqual({status:'CONFIRMED'});expect(raw.prepare('SELECT count(*) total FROM cancellation_outcomes').get()).toEqual({total:0});});
});
