import { beforeEach, describe, expect, it } from 'vitest';
import { handleApiRequest } from '../src/server/api.js';
import { createLocalDatabasePort, migrate, openDatabase } from '../src/server/db/database.js';
import type Database from 'better-sqlite3';
let raw: Database.Database; const env=()=>({ENVIRONMENT:'development' as const,AUTH_MODE:'mock' as const,ALLOWED_OWNER_EMAIL:'owner@example.test',DB:createLocalDatabasePort(raw)});
const request=(path:string,init:RequestInit={})=>handleApiRequest(new Request(`http://local${path}`,{...init,headers:{'content-type':'application/json','x-dev-owner-email':'owner@example.test',...init.headers}}),env(),{now:()=>new Date('2027-01-01T12:00:00Z')});
beforeEach(()=>{raw?.close();raw=openDatabase(':memory:');migrate(raw);raw.prepare("INSERT INTO trailers(name,unit_code,published_payload_lbs) VALUES ('Trailer','T1',5200)").run();});
describe('portable API',()=>{
 it('creates external bookings and rejects overlap at the data layer',async()=>{const payload={trailerId:1,customerName:'Test Owner',source:'OTHER',pickupAt:'2027-04-01T13:00:00Z',returnAt:'2027-04-02T13:00:00Z',rentalChargeCents:10000};expect((await request('/api/reservations/external',{method:'POST',body:JSON.stringify(payload)})).status).toBe(201);expect((await request('/api/reservations/external',{method:'POST',body:JSON.stringify({...payload,customerName:'Overlap Owner'})})).status).toBe(409);expect((raw.prepare('SELECT actor FROM audit_events').get() as {actor:string}).actor).toBe('owner@example.test');});
 it('rejects hosted inspection references',async()=>{raw.exec("INSERT INTO customers(first_name,last_name) VALUES ('A','B'); INSERT INTO reservations(confirmation_code,trailer_id,customer_id,channel,status,pickup_at,return_at,rental_charge_cents) VALUES ('X',1,1,'DIRECT','CONFIRMED','2027-05-01T13:00:00Z','2027-05-02T13:00:00Z',10000)");const response=await request('/api/reservations/1/inspections/pickup',{method:'POST',body:JSON.stringify({conditionNotes:'Good condition',photoReferences:['https://hosted.example/photo.jpg']})});expect(response.status).toBe(400);expect(await response.json()).toMatchObject({error:expect.stringContaining('not accepted')});});
 it.each(['https://hosted.example/photo.jpg','file:///photo.jpg','C:\\photos\\damage.jpg','/var/photos/damage.jpg','../damage.jpg'])('rejects hosted URL or filesystem-shaped photo metadata: %s',async(reference)=>{raw.exec("INSERT OR IGNORE INTO customers(id,first_name,last_name) VALUES (1,'A','B'); INSERT OR IGNORE INTO reservations(id,confirmation_code,trailer_id,customer_id,channel,status,pickup_at,return_at,rental_charge_cents) VALUES (1,'X',1,1,'DIRECT','CONFIRMED','2027-05-01T13:00:00Z','2027-05-02T13:00:00Z',10000)");const response=await request('/api/reservations/1/inspections/pickup',{method:'POST',body:JSON.stringify({conditionNotes:'Good condition',photoReferences:[reference]})});expect(response.status).toBe(400);expect(raw.prepare('SELECT count(*) total FROM inspection_photos').get()).toEqual({total:0});});
 it('rolls back a reschedule if its audit event fails',async()=>{raw.exec("INSERT INTO customers(first_name,last_name) VALUES ('A','B'); INSERT INTO reservations(confirmation_code,trailer_id,customer_id,channel,status,pickup_at,return_at,rental_charge_cents) VALUES ('EDIT',1,1,'DIRECT','CONFIRMED','2027-06-01T13:00:00Z','2027-06-02T13:00:00Z',10000); CREATE TRIGGER fail_edit_audit BEFORE INSERT ON audit_events WHEN NEW.action='RESERVATION_EDITED' BEGIN SELECT RAISE(ABORT,'forced audit failure'); END;");const response=await request('/api/reservations/1',{method:'PATCH',body:JSON.stringify({version:1,pickupAt:'2027-06-03T13:00:00Z',returnAt:'2027-06-04T13:00:00Z',rentalChargeCents:10000,dollyDays:0,reason:'test rollback'})});expect(response.status).toBe(400);expect(await response.json()).toEqual({error:'The request could not be completed.'});expect(raw.prepare('SELECT pickup_at,version FROM reservations WHERE id=1').get()).toEqual({pickup_at:'2027-06-01T13:00:00Z',version:1});});
 it('rolls back cancellation outcome and status if audit creation fails',async()=>{raw.exec("INSERT INTO customers(first_name,last_name) VALUES ('A','B'); INSERT INTO reservations(confirmation_code,trailer_id,customer_id,channel,status,pickup_at,return_at,rental_charge_cents) VALUES ('CANCEL',1,1,'DIRECT','CONFIRMED','2027-07-01T13:00:00Z','2027-07-02T13:00:00Z',10000); CREATE TRIGGER fail_cancel_audit BEFORE INSERT ON audit_events WHEN NEW.action='CANCELLATION_OUTCOME_RECORDED' BEGIN SELECT RAISE(ABORT,'forced audit failure'); END;");const response=await request('/api/reservations/1/outcome',{method:'POST',body:JSON.stringify({type:'CANCELLATION',notes:'Owner cancellation'})});expect(response.status).toBe(400);expect(raw.prepare('SELECT status FROM reservations WHERE id=1').get()).toEqual({status:'CONFIRMED'});expect(raw.prepare('SELECT count(*) total FROM cancellation_outcomes').get()).toEqual({total:0});});
});
