import { beforeEach,describe,expect,it } from 'vitest';
import type Database from 'better-sqlite3';
import { createLocalDatabasePort,migrate,openDatabase } from '../src/server/db/database.js';
import { BOOKING_CONFIRMATION_ACCEPTANCE_CODE,createBookingConfirmationAcceptanceFixture } from '../src/server/stagingAcceptanceFixture.js';

let raw:Database.Database;
beforeEach(()=>{raw?.close();raw=openDatabase(':memory:');migrate(raw);raw.prepare("INSERT INTO trailers(name,unit_code,published_payload_lbs) VALUES ('Synthetic Trailer','SYN-1',5200)").run()});
describe('Booking Confirmation staging acceptance fixture',()=>{
 it('atomically creates one fully qualified direct synthetic fixture with no raw secure tokens',async()=>{const result=await createBookingConfirmationAcceptanceFixture(createLocalDatabasePort(raw),'owner@example.test',new Date('2027-01-01T12:00:00Z'));expect(result).toMatchObject({confirmationCode:BOOKING_CONFIRMATION_ACCEPTANCE_CODE,idempotent:false,synthetic:true});expect(raw.prepare('SELECT channel,status,renter_age,named_renter_will_tow,international_use,delivery_requested,is_synthetic FROM reservations').get()).toEqual({channel:'DIRECT',status:'CONFIRMED',renter_age:30,named_renter_will_tow:1,international_use:0,delivery_requested:0,is_synthetic:1});expect(raw.prepare('SELECT status,pickup_inspection_choice FROM agreement_instances').get()).toEqual({status:'SIGNED',pickup_inspection_choice:'SEND_FORM'});expect(raw.prepare('SELECT kind,status,amount_cents,provider FROM payment_ledger_entries').get()).toEqual({kind:'PAYMENT_COLLECTED',status:'SUCCEEDED',amount_cents:17000,provider:'MOCK'});expect(raw.prepare('SELECT count(*) total FROM secure_links WHERE revoked_at IS NULL AND used_at IS NULL').get()).toEqual({total:2});for(const row of raw.prepare('SELECT token_hash,token_fingerprint FROM secure_links').all() as Array<{token_hash:string;token_fingerprint:string}>){expect(row.token_hash).toMatch(/^[0-9a-f]{64}$/);expect(row.token_fingerprint).toBe(row.token_hash.slice(0,12))}expect(raw.prepare("SELECT count(*) total FROM audit_events WHERE action='BOOKING_CONFIRMATION_ACCEPTANCE_FIXTURE_CREATED'").get()).toEqual({total:1})});
 it('is idempotent and never creates a second fixture',async()=>{const db=createLocalDatabasePort(raw);await createBookingConfirmationAcceptanceFixture(db,'owner@example.test',new Date('2027-01-01T12:00:00Z'));expect(await createBookingConfirmationAcceptanceFixture(db,'owner@example.test',new Date('2027-01-01T12:01:00Z'))).toMatchObject({idempotent:true});expect(raw.prepare('SELECT count(*) total FROM reservations').get()).toEqual({total:1});expect(raw.prepare('SELECT count(*) total FROM payment_ledger_entries').get()).toEqual({total:1});expect(raw.prepare('SELECT count(*) total FROM secure_links').get()).toEqual({total:2})});
 it('rolls back every fixture record when authoritative availability rejects the reservation',async()=>{raw.prepare("INSERT INTO availability_blocks(trailer_id,start_at,end_at,reason,is_synthetic) VALUES (1,'2029-02-01T14:00:00.000Z','2029-02-01T16:00:00.000Z','Synthetic conflict',1)").run();await expect(createBookingConfirmationAcceptanceFixture(createLocalDatabasePort(raw),'owner@example.test',new Date('2027-01-01T12:00:00Z'))).rejects.toThrow(/TRAILER_SCHEDULE_CONFLICT/);expect(raw.prepare('SELECT count(*) total FROM reservations').get()).toEqual({total:0});expect(raw.prepare('SELECT count(*) total FROM customers').get()).toEqual({total:0});expect(raw.prepare('SELECT count(*) total FROM payment_ledger_entries').get()).toEqual({total:0});expect(raw.prepare('SELECT count(*) total FROM audit_events').get()).toEqual({total:0})});
});
