import {afterEach,beforeEach,describe,expect,it} from 'vitest';
import type Database from 'better-sqlite3';
import {handleApiRequest} from '../src/server/api.js';
import {createLocalDatabasePort,migrate,openDatabase} from '../src/server/db/database.js';
import type {PaymentProvider,SanitizedWebhook} from '../src/server/paymentProvider.js';

let raw:Database.Database;let webhookEvent:SanitizedWebhook;
const provider:PaymentProvider={provider:'STRIPE_TEST',async createPayment(){return{providerPaymentId:'pi_test_api',status:'REQUIRES_CONFIRMATION',clientSecret:'pi_test_api_secret'}},async retrievePayment(id){return{providerPaymentId:id,status:'SUCCEEDED'}},async createRefund(){return{providerRefundId:'re_test_api',status:'SUCCEEDED'}},async verifyWebhook(){return webhookEvent}};
const env=()=>({ENVIRONMENT:'development' as const,AUTH_MODE:'mock' as const,ALLOWED_OWNER_EMAIL:'owner@example.test',DB:createLocalDatabasePort(raw)});
const call=(path:string,init:RequestInit={})=>handleApiRequest(new Request(`http://local${path}`,{...init,headers:{'content-type':'application/json','x-dev-owner-email':'owner@example.test',...init.headers}}),env(),{now:()=>new Date('2027-01-01T12:00:00Z'),paymentProvider:provider,stripePublishableKey:'pk_test_placeholder'});
beforeEach(()=>{raw=openDatabase(':memory:');migrate(raw);raw.exec("INSERT INTO trailers(name,unit_code,published_payload_lbs) VALUES ('T','T',5200); INSERT INTO customers(first_name,last_name) VALUES ('Synthetic','Renter'); INSERT INTO reservations(confirmation_code,trailer_id,customer_id,channel,status,pickup_at,return_at,rental_charge_cents,dolly_days,renter_age,named_renter_will_tow,is_synthetic) VALUES ('PAY',1,1,'DIRECT','CONFIRMED','2027-02-01T15:00:00Z','2027-02-02T15:00:00Z',6000,1,30,1,1); INSERT INTO agreement_templates(version,source_manifest_version,content_json,content_hash) VALUES ('v','v','{}','hash'); INSERT INTO agreement_instances(reservation_id,template_id,status,template_version,template_hash,renter_snapshot_json,reservation_snapshot_json,quote_snapshot_json,rendered_at,signed_at,printed_name) VALUES (1,1,'SIGNED','v','hash','{}','{}','{}','2027-01-01T00:00:00Z','2027-01-01T00:00:00Z','Synthetic Renter')");webhookEvent={providerEventId:'evt_default',type:'payment_intent.succeeded',providerPaymentId:'pi_test_api',status:'succeeded',createdAt:'2027-01-01T12:00:00.000Z'}});afterEach(()=>raw.close());
async function start(){return call('/api/reservations/1/payment-actions',{method:'POST',body:JSON.stringify({action:'COLLECT',idempotencyKey:'stripe_collect_api_1',reason:'Synthetic Stripe test checkout'})})}

describe('protected Stripe test payment API',()=>{
 it('returns test checkout material and records only a pending server ledger entry',async()=>{const response=await start();expect(response.status).toBe(201);expect(await response.json()).toMatchObject({kind:'PAYMENT_PENDING',status:'REQUIRES_CONFIRMATION',clientSecret:'pi_test_api_secret',publishableKey:'pk_test_placeholder'});expect(raw.prepare('SELECT kind,provider,status FROM payment_ledger_entries').get()).toEqual({kind:'PAYMENT_PENDING',provider:'STRIPE_TEST',status:'REQUIRES_CONFIRMATION'});expect(raw.prepare('SELECT status FROM reservations').get()).toEqual({status:'CONFIRMED'})});
 it('reconciles success only by retrieving Stripe status server-side',async()=>{await start();const response=await call('/api/reservations/1/payment-reconcile',{method:'POST'});expect(await response.json()).toEqual({status:'SUCCEEDED',reconciled:true});expect(raw.prepare("SELECT count(*) total FROM payment_ledger_entries WHERE kind='PAYMENT_COLLECTED'").get()).toEqual({total:1});expect(raw.prepare('SELECT status FROM reservations').get()).toEqual({status:'CONFIRMED'})});
 it('does not duplicate a collection when the signed webhook wins the reconciliation race',async()=>{await start();webhookEvent={providerEventId:'evt_race',type:'payment_intent.succeeded',providerPaymentId:'pi_test_api',status:'succeeded',createdAt:'2027-01-01T12:00:00.000Z'};expect((await call('/api/payments/webhooks/stripe',{method:'POST',headers:{'stripe-signature':'verified-by-provider'},body:'race'})).status).toBe(202);const reconciled=await call('/api/reservations/1/payment-reconcile',{method:'POST'});expect(await reconciled.json()).toEqual({status:'SUCCEEDED',reconciled:true,idempotent:true});expect(raw.prepare("SELECT count(*) total FROM payment_ledger_entries WHERE kind='PAYMENT_COLLECTED'").get()).toEqual({total:1})});
 it('rejects stale readiness when reservation state changes before PaymentIntent creation',async()=>{raw.exec("UPDATE reservations SET status='CANCELLED'");const response=await start();expect(response.status).toBe(409);expect(raw.prepare('SELECT count(*) total FROM payment_ledger_entries').get()).toEqual({total:0})});
 it('deduplicates and ignores out-of-order Stripe webhook delivery',async()=>{await start();webhookEvent={providerEventId:'evt_new',type:'payment_intent.succeeded',providerPaymentId:'pi_test_api',status:'succeeded',createdAt:'2027-01-01T12:00:00.000Z'};const first=await call('/api/payments/webhooks/stripe',{method:'POST',headers:{'stripe-signature':'verified-by-provider'},body:'new'});expect(first.status).toBe(202);expect(await first.json()).toEqual({accepted:true});const duplicate=await call('/api/payments/webhooks/stripe',{method:'POST',headers:{'stripe-signature':'verified-by-provider'},body:'new'});expect(duplicate.status).toBe(409);webhookEvent={providerEventId:'evt_old',type:'payment_intent.payment_failed',providerPaymentId:'pi_test_api',status:'requires_payment_method',createdAt:'2027-01-01T11:00:00.000Z'};expect((await call('/api/payments/webhooks/stripe',{method:'POST',headers:{'stripe-signature':'verified-by-provider'},body:'old'})).status).toBe(202);expect(raw.prepare("SELECT processing_status FROM payment_webhook_events WHERE provider_event_id='evt_old'").get()).toEqual({processing_status:'IGNORED_STALE'});expect(raw.prepare("SELECT count(*) total FROM payment_ledger_entries WHERE kind='PAYMENT_FAILED'").get()).toEqual({total:0})});
});
