import {afterEach,beforeEach,describe,expect,it} from 'vitest';
import type Database from 'better-sqlite3';
import {handleStripeWebhookRequest} from '../src/server/api.js';
import {createLocalDatabasePort,migrate,openDatabase} from '../src/server/db/database.js';
import {createStripeTestWebhookVerifier} from '../src/server/paymentProvider.js';

const webhookSecret='whsec_x';const timestamp=1_800_000_000;let rawDb:Database.Database;
async function signature(raw:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(webhookSecret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const bytes=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(`${timestamp}.${raw}`));return`t=${timestamp},v1=${Array.from(new Uint8Array(bytes)).map(byte=>byte.toString(16).padStart(2,'0')).join('')}`}
const verifier=()=>createStripeTestWebhookVerifier(webhookSecret,()=>timestamp*1000);
const request=(body:string,headers:Record<string,string>={})=>new Request('https://staging.example.test/api/payments/webhooks/stripe',{method:'POST',headers,body});
beforeEach(()=>{rawDb=openDatabase(':memory:');migrate(rawDb)});afterEach(()=>rawDb.close());

describe('exact Stripe webhook security boundary',()=>{
 it('rejects wrong paths and non-POST methods with private no-store responses',async()=>{const db=createLocalDatabasePort(rawDb);expect((await handleStripeWebhookRequest(new Request('https://staging.example.test/api/payments/webhooks/other',{method:'POST'}),db,verifier())).status).toBe(404);const get=await handleStripeWebhookRequest(new Request('https://staging.example.test/api/payments/webhooks/stripe'),db,verifier());expect(get.status).toBe(405);expect(get.headers.get('cache-control')).toBe('private, no-store')});
 it('rejects missing and invalid signatures without diagnostics',async()=>{const db=createLocalDatabasePort(rawDb);const missing=await handleStripeWebhookRequest(request('{}'),db,verifier());expect(missing.status).toBe(401);expect(await missing.json()).toEqual({error:'Invalid webhook request.'});const invalid=await handleStripeWebhookRequest(request('{}',{'stripe-signature':'invalid'}),db,verifier());expect(invalid.status).toBe(401)});
 it('rejects oversized bodies before signature processing',async()=>{const response=await handleStripeWebhookRequest(request('x',{'content-length':String(256*1024+1),'stripe-signature':'unused'}),createLocalDatabasePort(rawDb),verifier());expect(response.status).toBe(413);expect(await response.json()).toEqual({error:'Webhook payload too large.'})});
 it('rejects malformed and unsupported signed events',async()=>{const db=createLocalDatabasePort(rawDb);const malformed='{';expect((await handleStripeWebhookRequest(request(malformed,{'stripe-signature':await signature(malformed)}),db,verifier())).status).toBe(401);const unsupported=JSON.stringify({id:'evt_unsupported',type:'customer.created',created:timestamp,data:{object:{id:'cus_x'}}});expect((await handleStripeWebhookRequest(request(unsupported,{'stripe-signature':await signature(unsupported)}),db,verifier())).status).toBe(422)});
 it('accepts a supported signed fixture once and rejects the duplicate',async()=>{const raw=JSON.stringify({id:'evt_secure_1',type:'payment_intent.succeeded',created:timestamp,data:{object:{id:'pi_test_secure',status:'succeeded'}}});const headers={'stripe-signature':await signature(raw)};const db=createLocalDatabasePort(rawDb);const accepted=await handleStripeWebhookRequest(request(raw,headers),db,verifier(),new Date(timestamp*1000));expect(accepted.status).toBe(202);expect(await accepted.json()).toEqual({accepted:true});expect(accepted.headers.get('cache-control')).toBe('private, no-store');const duplicate=await handleStripeWebhookRequest(request(raw,headers),db,verifier(),new Date(timestamp*1000));expect(duplicate.status).toBe(409);expect(await duplicate.json()).toEqual({error:'Duplicate webhook event.'});expect(rawDb.prepare('SELECT event_type,processing_status,length(payload_hash) hash_length FROM payment_webhook_events').get()).toEqual({event_type:'payment_intent.succeeded',processing_status:'UNMATCHED',hash_length:64})});
});
