import {describe,expect,it} from 'vitest';
import {createStripeTestPaymentProvider} from '../src/server/paymentProvider.js';

const secret='sk_test_x';
const webhookSecret='whsec_x';
type RequestInfo=Parameters<typeof fetch>[0];
const response=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status,headers:{'content-type':'application/json'}});
function recordedFetch(payload:unknown,status=200){const calls:Array<{input:RequestInfo|URL;init?:RequestInit}>=[];const fetchImpl:typeof fetch=async(input,init)=>{calls.push({input,init});return response(payload,status)};return{fetchImpl,calls}}
async function signature(raw:string,timestamp=1_800_000_000){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(webhookSecret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const bytes=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(`${timestamp}.${raw}`));return`t=${timestamp},v1=${Array.from(new Uint8Array(bytes)).map(byte=>byte.toString(16).padStart(2,'0')).join('')}`}

describe('Stripe test provider adapter',()=>{
  it('creates an authoritative test PaymentIntent with an idempotency key',async()=>{const mock=recordedFetch({id:'pi_test_1',status:'requires_payment_method',client_secret:'pi_test_secret'});const provider=createStripeTestPaymentProvider({secretKey:secret,webhookSecret,fetchImpl:mock.fetchImpl});const result=await provider.createPayment({amountCents:17_000,currency:'usd',idempotencyKey:'collect_1',metadata:{reservationId:'7',synthetic:'true'}});expect(result).toMatchObject({providerPaymentId:'pi_test_1',status:'REQUIRES_CONFIRMATION'});const call=mock.calls[0];expect(call.input).toBe('https://api.stripe.com/v1/payment_intents');expect(call.init?.headers).toMatchObject({authorization:`Bearer ${secret}`,'idempotency-key':'collect_1','content-type':'application/x-www-form-urlencoded'});const form=new URLSearchParams(String(call.init?.body));expect(form.get('amount')).toBe('17000');expect(form.get('currency')).toBe('usd');expect(form.get('metadata[synthetic]')).toBe('true')});
  it('returns a client secret for confirmation-capable intents',async()=>{const mock=recordedFetch({id:'pi_test_2',status:'requires_action',client_secret:'client_secret_value'});const provider=createStripeTestPaymentProvider({secretKey:secret,webhookSecret,fetchImpl:mock.fetchImpl});await expect(provider.createPayment({amountCents:10_000,currency:'usd',idempotencyKey:'collect_2',metadata:{reservationId:'8',synthetic:'true'}})).resolves.toMatchObject({status:'REQUIRES_CONFIRMATION',clientSecret:'client_secret_value'})});
  it('creates bounded refunds with Stripe idempotency',async()=>{const mock=recordedFetch({id:'re_test_1',status:'succeeded'});const provider=createStripeTestPaymentProvider({secretKey:secret,webhookSecret,fetchImpl:mock.fetchImpl});await expect(provider.createRefund({providerPaymentId:'pi_test_1',amountCents:10_000,idempotencyKey:'refund_1',reason:'clean return'})).resolves.toMatchObject({providerRefundId:'re_test_1',status:'SUCCEEDED'});const call=mock.calls[0];expect(call.input).toBe('https://api.stripe.com/v1/refunds');expect(new URLSearchParams(String(call.init?.body)).get('amount')).toBe('10000');expect((call.init?.headers as Record<string,string>)['idempotency-key']).toBe('refund_1')});
  it('sanitizes upstream failures',async()=>{const mock=recordedFetch({error:{type:'card_error',message:'sensitive detail'}},402);const provider=createStripeTestPaymentProvider({secretKey:secret,webhookSecret,fetchImpl:mock.fetchImpl});await expect(provider.createPayment({amountCents:100,currency:'usd',idempotencyKey:'failed',metadata:{reservationId:'1',synthetic:'true'}})).rejects.toThrow('card_error');await expect(provider.createPayment({amountCents:100,currency:'usd',idempotencyKey:'failed',metadata:{reservationId:'1',synthetic:'true'}})).rejects.not.toThrow('sensitive detail')});
  it('verifies realistic raw Stripe signatures and extracts sanitized fields',async()=>{const raw=JSON.stringify({id:'evt_test_1',type:'payment_intent.succeeded',created:1_800_000_000,data:{object:{id:'pi_test_1',status:'succeeded',amount:17000,client_secret:'never-store'}}});const provider=createStripeTestPaymentProvider({secretKey:secret,webhookSecret,now:()=>1_800_000_000_000});await expect(provider.verifyWebhook(raw,await signature(raw))).resolves.toEqual({providerEventId:'evt_test_1',type:'payment_intent.succeeded',providerPaymentId:'pi_test_1',status:'succeeded',createdAt:'2027-01-15T08:00:00.000Z'});await expect(provider.verifyWebhook(`${raw} `,await signature(raw))).rejects.toThrow(/verification/)});
  it('retrieves status server-side without accepting browser status',async()=>{const mock=recordedFetch({id:'pi_test_3',status:'succeeded'});const provider=createStripeTestPaymentProvider({secretKey:secret,webhookSecret,fetchImpl:mock.fetchImpl});await expect(provider.retrievePayment('pi_test_3')).resolves.toMatchObject({providerPaymentId:'pi_test_3',status:'SUCCEEDED'});expect(mock.calls[0].input).toBe('https://api.stripe.com/v1/payment_intents/pi_test_3')});
  it('rejects stale signatures and non-test keys',async()=>{expect(()=>createStripeTestPaymentProvider({secretKey:'sk_live_forbidden',webhookSecret})).toThrow(/test-mode/);const raw='{}';const provider=createStripeTestPaymentProvider({secretKey:secret,webhookSecret,now:()=>1_800_001_000_000});await expect(provider.verifyWebhook(raw,await signature(raw))).rejects.toThrow(/tolerance/)})
});
