import { useCallback, useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react';
import { AlertTriangle, ArrowLeft, Ban, CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, Clock3, LayoutDashboard, Menu, Plus, Search, Truck, X } from 'lucide-react';

type Reservation = { id:number; confirmation_code:string; trailer_name:string; customer_name:string; channel:'DIRECT'|'EXTERNAL'; external_source?:string; external_reference?:string; status:string; pickup_at:string; return_at:string; rental_charge_cents:number; renter_age?:number; named_renter_will_tow?:number; interstate_use?:number; interstate_approved?:number; international_use?:number; delivery_requested?:number; delivery_distance_miles?:number; delivery_approved?:number; dolly_days:number; notes?:string };
type Block = { id:number; trailer_name:string; start_at:string; end_at:string; reason:string; notes?:string };
type Trailer = { id:number; name:string; unit_code:string; published_payload_lbs:number; plate_verified:boolean };
type Dashboard = { reservations:Reservation[]; blocks:Block[]; trailers:Trailer[] };
type View = 'dashboard'|'schedule'|'reservations'|'attention'|'detail';
const sourceLabels:Record<string,string>={BIG_RENTALS:'Big Rentals',NEIGHBORS_TRAILER:'Neighbors Trailer',FACEBOOK_MARKETPLACE:'Facebook Marketplace',OTHER:'Other'};
const fmt=(iso:string,time=true)=>new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric',...(time?{hour:'numeric',minute:'2-digit'}:{})}).format(new Date(iso));
const money=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100);
const statusLabel=(s:string)=>s.toLowerCase().replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const attentionStatuses=['PENDING_REVIEW','PENDING_AGREEMENT','PENDING_PAYMENT','RETURNED_PENDING_INSPECTION'];
const attentionReason=(r:Reservation)=>r.notes||({PENDING_REVIEW:'Review booking source and renter qualification',PENDING_AGREEMENT:'Agreement signature is still required',PENDING_PAYMENT:'Rental payment is still required',RETURNED_PENDING_INSPECTION:'Owner inspection is required before deposit release'}[r.status]||'Owner review required');

function App(){
 const [data,setData]=useState<Dashboard>({reservations:[],blocks:[],trailers:[]}); const [view,setView]=useState<View>('dashboard'); const [selected,setSelected]=useState<number|null>(null); const [modal,setModal]=useState<'booking'|'block'|null>(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(true); const [menu,setMenu]=useState(false); const [query,setQuery]=useState('');
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch('/api/dashboard');setData(await r.json());}finally{setLoading(false)}},[]); useEffect(()=>{void load()},[load]);
 const attention=data.reservations.filter(r=>attentionStatuses.includes(r.status)); const selectedReservation=data.reservations.find(r=>r.id===selected);
 const go=(next:View)=>{setView(next);setSelected(null);setMenu(false);window.scrollTo(0,0)}; const openReservation=(id:number)=>{setSelected(id);setView('detail');setMenu(false);window.scrollTo(0,0)};
 async function submit(e:FormEvent<HTMLFormElement>,path:string){e.preventDefault();setError('');const body=Object.fromEntries(new FormData(e.currentTarget));if('rentalChargeDollars'in body){body.rentalChargeCents=String(Number(body.rentalChargeDollars)*100);delete body.rentalChargeDollars}const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await r.json();if(!r.ok){setError(result.error);return}setModal(null);await load()}
 const titles:Record<View,[string,string,string]>={dashboard:['OWNER OPERATIONS','Operations overview','One clear view of bookings, availability, and what needs action.'],schedule:['CALENDAR','Schedule','Reservations and availability blocks in chronological order.'],reservations:['BOOKINGS','Reservations','All persisted direct and external reservations.'],attention:['ACTION QUEUE','Needs attention','Bookings waiting for an owner decision or follow-up.'],detail:['RESERVATION','Reservation detail','Stored booking information and current operational status.']};
 const title=titles[view];
 return <div className="shell">
  <aside className={menu?'open':''}><div className="brand"><img src="/tb-logo.svg" alt="Trailer Bros"/><div><strong>TRAILER BROS</strong><span>RENTAL OS</span></div><button aria-label="Close menu" className="mobile-close" onClick={()=>setMenu(false)}><X/></button></div><nav><Nav active={view==='dashboard'} onClick={()=>go('dashboard')} icon={<LayoutDashboard/>}>Dashboard</Nav><Nav active={view==='schedule'} onClick={()=>go('schedule')} icon={<CalendarDays/>}>Schedule</Nav><Nav active={view==='reservations'||view==='detail'} onClick={()=>go('reservations')} icon={<Truck/>}>Reservations</Nav><Nav active={view==='attention'} onClick={()=>go('attention')} icon={<AlertTriangle/>}>Attention <b>{attention.length}</b></Nav></nav><div className="sidebar-foot"><span>DEVELOPMENT</span><small>Local data only</small></div></aside>
  <main><header><button aria-label="Open menu" className="menu" onClick={()=>setMenu(true)}><Menu/></button><div><p>{title[0]}</p><h1>{view==='dashboard'?'Good morning':title[1]}</h1></div><div className="header-tools"><button aria-label="Search reservations" className="icon" onClick={()=>go('reservations')}><Search/></button><img className="avatar-logo" src="/tb-logo.svg" alt="Trailer Bros"/></div></header>
   <section className="content"><div className="heading"><div>{view==='detail'&&<button className="back" onClick={()=>go('reservations')}><ArrowLeft/> Back to reservations</button>}<h2>{view==='detail'?(selectedReservation?.confirmation_code||'Reservation not found'):title[1]}</h2><p>{title[2]}</p></div>{view!=='detail'&&<div className="actions"><button className="secondary" onClick={()=>setModal('block')}><Ban/>Block availability</button><button className="primary" onClick={()=>setModal('booking')}><Plus/>External booking</button></div>}</div>
   {view==='dashboard'&&<DashboardView data={data} attention={attention} loading={loading} onView={go} onReservation={openReservation}/>}
   {view==='schedule'&&<ScheduleView data={data} onReservation={openReservation}/>}
   {view==='reservations'&&<ReservationsView reservations={data.reservations} query={query} setQuery={setQuery} onReservation={openReservation}/>}
   {view==='attention'&&<AttentionView reservations={attention} onReservation={openReservation}/>}
   {view==='detail'&&<ReservationDetail reservation={selectedReservation}/>}
   </section><footer>Trailer Bros Rental OS <span>•</span> Development checkpoint</footer></main>
  {modal&&<BookingModal modal={modal} data={data} error={error} close={()=>{setModal(null);setError('')}} submit={submit}/>}
 </div>
}

function Nav({active,onClick,icon,children}:{active:boolean;onClick:()=>void;icon:ReactNode;children:ReactNode}){return <button className={active?'active':''} onClick={onClick}>{icon}{children}</button>}
function DashboardView({data,attention,loading,onView,onReservation}:{data:Dashboard;attention:Reservation[];loading:boolean;onView:(v:View)=>void;onReservation:(id:number)=>void}){const upcoming=data.reservations.slice(0,5);return <><div className="metrics"><Metric icon={<CalendarDays/>} label="Upcoming reservations" value={data.reservations.length} note="Active schedule"/><Metric icon={<AlertTriangle/>} label="Needs attention" value={attention.length} note="Owner action required" warning/><Metric icon={<CheckCircle2/>} label="Confirmed" value={data.reservations.filter(r=>r.status==='CONFIRMED').length} note="Ready on calendar"/><Metric icon={<Ban/>} label="Availability blocks" value={data.blocks.length} note="Maintenance & holds"/></div><div className="grid"><section className="panel schedule"><div className="panel-head"><div><p>UPCOMING</p><h3>Reservation schedule</h3></div><button onClick={()=>onView('schedule')}>View calendar <ChevronRight/></button></div>{loading?<div className="empty">Loading schedule…</div>:upcoming.map(r=><ReservationRow key={r.id} reservation={r} onClick={()=>onReservation(r.id)}/>)}{!loading&&!upcoming.length&&<div className="empty">No upcoming reservations.</div>}</section><section className="panel attention"><div className="panel-head"><div><p>ACTION QUEUE</p><h3>Needs attention</h3></div><button className="count" onClick={()=>onView('attention')}>{attention.length}</button></div>{attention.map(r=><AttentionRow key={r.id} reservation={r} onClick={()=>onReservation(r.id)}/>)}{!attention.length&&<div className="empty"><CheckCircle2/> You’re all caught up.</div>}<div className="policy"><strong>V1A guardrails active</strong><span>30-minute times · 6 AM–10 PM · overlap protection</span></div></section></div></>}
function ScheduleView({data,onReservation}:{data:Dashboard;onReservation:(id:number)=>void}){
 const initial=useMemo(()=>{const first=[...data.reservations.map(r=>r.pickup_at),...data.blocks.map(b=>b.start_at)].sort()[0];const d=first?new Date(first):new Date();return new Date(d.getFullYear(),d.getMonth(),1)},[data]);
 const [month,setMonth]=useState(initial); useEffect(()=>setMonth(initial),[initial]);
 const items=useMemo(()=>[...data.reservations.map(r=>({type:'reservation' as const,start:r.pickup_at,item:r})),...data.blocks.map(b=>({type:'block' as const,start:b.start_at,item:b}))].sort((a,b)=>a.start.localeCompare(b.start)),[data]);
 const days=useMemo(()=>{const first=new Date(month.getFullYear(),month.getMonth(),1);const cursor=new Date(first);cursor.setDate(1-first.getDay());return Array.from({length:42},(_,i)=>{const d=new Date(cursor);d.setDate(cursor.getDate()+i);return d})},[month]);
 const dayEvents=(day:Date)=>{const key=localDayKey(day);return [...data.reservations.filter(r=>localDayKey(new Date(r.pickup_at))<=key&&localDayKey(new Date(r.return_at))>=key).map(r=>({type:'reservation' as const,id:r.id,label:r.customer_name||r.confirmation_code,status:r.status})),...data.blocks.filter(b=>localDayKey(new Date(b.start_at))<=key&&localDayKey(new Date(b.end_at))>=key).map(b=>({type:'block' as const,id:b.id,label:b.reason,status:'BLOCK'}))]};
 const move=(delta:number)=>setMonth(m=>new Date(m.getFullYear(),m.getMonth()+delta,1));
 return <div className="schedule-page"><section className="panel calendar-panel"><div className="calendar-head"><div><p>MONTH VIEW</p><h3>{new Intl.DateTimeFormat('en-US',{month:'long',year:'numeric'}).format(month)}</h3></div><div className="calendar-controls"><button aria-label="Previous month" onClick={()=>move(-1)}><ChevronLeft/></button><button onClick={()=>setMonth(new Date(new Date().getFullYear(),new Date().getMonth(),1))}>Today</button><button aria-label="Next month" onClick={()=>move(1)}><ChevronRight/></button></div></div><div className="weekday-row">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=><span key={d}>{d}</span>)}</div><div className="calendar-grid">{days.map(day=>{const events=dayEvents(day);const outside=day.getMonth()!==month.getMonth();const today=localDayKey(day)===localDayKey(new Date());return <div className={`calendar-day${outside?' outside':''}${today?' today':''}`} key={localDayKey(day)}><div className="day-number">{day.getDate()}</div><div className="day-events">{events.slice(0,3).map(event=>event.type==='reservation'?<button title={`${event.label} — ${statusLabel(event.status)}`} className={`calendar-event ${event.status.toLowerCase()}`} key={`r-${event.id}`} onClick={()=>onReservation(event.id)}><span>{event.label}</span></button>:<div title={event.label} className="calendar-event block-event" key={`b-${event.id}`}><Ban/><span>{event.label}</span></div>)}{events.length>3&&<small>+{events.length-3} more</small>}</div></div>})}</div><div className="calendar-legend"><span><i className="confirmed-dot"/>Confirmed</span><span><i className="review-dot"/>Needs review</span><span><i className="block-dot"/>Availability block</span></div></section><section className="panel list-panel agenda-panel"><div className="panel-head"><div><p>CHRONOLOGICAL AGENDA</p><h3>All scheduled activity</h3></div><span className="count">{items.length}</span></div>{items.map(entry=>entry.type==='reservation'?<ReservationRow key={`r-${entry.item.id}`} reservation={entry.item} onClick={()=>onReservation(entry.item.id)}/>:<BlockRow key={`b-${entry.item.id}`} block={entry.item}/>)}{!items.length&&<div className="empty">Nothing is scheduled.</div>}</section></div>}
function localDayKey(date:Date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
function ReservationsView({reservations,query,setQuery,onReservation}:{reservations:Reservation[];query:string;setQuery:(q:string)=>void;onReservation:(id:number)=>void}){const filtered=reservations.filter(r=>`${r.customer_name} ${r.confirmation_code} ${r.status} ${r.external_source||''}`.toLowerCase().includes(query.toLowerCase()));return <section className="panel list-panel"><div className="list-toolbar"><div><p>ALL RESERVATIONS</p><h3>{filtered.length} booking{filtered.length===1?'':'s'}</h3></div><label className="search-box"><Search/><input aria-label="Filter reservations" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name or confirmation"/></label></div>{filtered.map(r=><ReservationRow key={r.id} reservation={r} onClick={()=>onReservation(r.id)}/>)}{!filtered.length&&<div className="empty">No reservations match your search.</div>}</section>}
function AttentionView({reservations,onReservation}:{reservations:Reservation[];onReservation:(id:number)=>void}){return <section className="panel list-panel"><div className="panel-head"><div><p>OWNER FOLLOW-UP</p><h3>Action queue</h3></div><span className="count">{reservations.length}</span></div>{reservations.map(r=><AttentionRow key={r.id} reservation={r} onClick={()=>onReservation(r.id)}/>)}{!reservations.length&&<div className="empty"><CheckCircle2/> You’re all caught up.</div>}</section>}
function ReservationDetail({reservation:r}:{reservation?:Reservation}){if(!r)return <div className="empty">Reservation not found.</div>;const source=r.channel==='EXTERNAL'?sourceLabels[r.external_source||'OTHER']:'Direct booking';return <div className="detail-grid"><section className="panel detail-main"><div className="detail-hero"><div><span className={'status '+r.status.toLowerCase()}>{statusLabel(r.status)}</span><h3>{r.customer_name||'Customer pending'}</h3><p>{r.trailer_name}</p></div><strong>{money(r.rental_charge_cents)}</strong></div><div className="detail-dates"><div><span>Pickup</span><strong>{fmt(r.pickup_at)}</strong></div><ChevronRight/><div><span>Return</span><strong>{fmt(r.return_at)}</strong></div></div><DetailSection title="Booking"><Detail label="Confirmation" value={r.confirmation_code}/><Detail label="Channel" value={source}/><Detail label="External reference" value={r.external_reference||'—'}/><Detail label="Dolly" value={r.dolly_days?`${r.dolly_days} day(s) at $10/day`:'Not included'}/></DetailSection><DetailSection title="Qualification"><Detail label="Renter age" value={r.renter_age?String(r.renter_age):'Not recorded'}/><Detail label="Named renter towing" value={r.named_renter_will_tow===0?'No':'Yes'}/><Detail label="Interstate use" value={r.interstate_use?`Yes — ${r.interstate_approved?'approved':'approval required'}`:'No'}/><Detail label="International use" value={r.international_use?'Prohibited — review':'No'}/></DetailSection><DetailSection title="Delivery & notes"><Detail label="Delivery" value={r.delivery_requested?`${r.delivery_distance_miles||'Distance pending'} miles — ${r.delivery_approved?'approved':'approval required'}`:'Pickup'}/><Detail label="Owner notes" value={r.notes||'No notes'}/></DetailSection></section><section className="panel detail-side"><p>NEXT ACTION</p><h3>{attentionStatuses.includes(r.status)?statusLabel(r.status):'No action required'}</h3><span>{attentionStatuses.includes(r.status)?attentionReason(r):'This reservation is on the active schedule.'}</span></section></div>}
function DetailSection({title,children}:{title:string;children:ReactNode}){return <section className="detail-section"><h4>{title}</h4><div>{children}</div></section>} function Detail({label,value}:{label:string;value:string}){return <div className="detail-field"><span>{label}</span><strong>{value}</strong></div>}
function ReservationRow({reservation:r,onClick}:{reservation:Reservation;onClick:()=>void}){return <button className="reservation reservation-button" onClick={onClick}><div className="date"><b>{new Date(r.pickup_at).getDate()}</b><span>{new Intl.DateTimeFormat('en-US',{month:'short'}).format(new Date(r.pickup_at))}</span></div><div className="reservation-main"><div><h4>{r.customer_name||'Customer pending'}</h4><p>{r.trailer_name} · {r.confirmation_code}</p></div><span className={'status '+r.status.toLowerCase()}>{statusLabel(r.status)}</span><div className="times"><span><Clock3/> {fmt(r.pickup_at)} → {fmt(r.return_at)}</span><small>{r.channel==='EXTERNAL'?sourceLabels[r.external_source||'OTHER']:'Direct booking'} <ChevronRight/></small></div></div></button>}
function BlockRow({block:b}:{block:Block}){return <article className="reservation block-row"><div className="date block-date"><Ban/><span>BLOCK</span></div><div className="reservation-main"><div><h4>{b.reason}</h4><p>{b.trailer_name}</p></div><span className="status blocked">Availability block</span><div className="times"><span><Clock3/> {fmt(b.start_at)} → {fmt(b.end_at)}</span><small>{b.notes||'Owner hold'}</small></div></div></article>}
function AttentionRow({reservation:r,onClick}:{reservation:Reservation;onClick:()=>void}){return <button className="task task-button" onClick={onClick}><div className="task-icon"><AlertTriangle/></div><div><h4>{r.customer_name}</h4><p>{statusLabel(r.status)} · {fmt(r.pickup_at,false)}</p><small>{attentionReason(r)}</small></div><ChevronRight/></button>}
function BookingModal({modal,data,error,close,submit}:{modal:'booking'|'block';data:Dashboard;error:string;close:()=>void;submit:(e:FormEvent<HTMLFormElement>,path:string)=>Promise<void>}){return <div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="modal"><div className="modal-head"><div><p>OWNER TOOL</p><h3>{modal==='booking'?'Add external booking':'Block availability'}</h3></div><button aria-label="Close form" onClick={close}><X/></button></div><p className="intro">{modal==='booking'?'Add bookings received outside this system. They block availability immediately.':'Reserve time for maintenance, personal use, or another operational hold.'}</p><form onSubmit={e=>void submit(e,modal==='booking'?'/api/reservations/external':'/api/availability-blocks')}><label>Trailer<select name="trailerId" required>{data.trailers.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label>{modal==='booking'?<><label>Customer name<input name="customerName" required placeholder="Full name"/></label><div className="two"><label>External source<select name="source"><option value="BIG_RENTALS">Big Rentals</option><option value="NEIGHBORS_TRAILER">Neighbors Trailer</option><option value="FACEBOOK_MARKETPLACE">Facebook Marketplace</option><option value="OTHER">Other</option></select></label><label>External reference<input name="externalReference" placeholder="Optional"/></label></div><div className="two"><label>Pickup<input name="pickupAt" type="datetime-local" step="1800" required/></label><label>Return<input name="returnAt" type="datetime-local" step="1800" required/></label></div><label>Rental charge<input name="rentalChargeDollars" type="number" min="0" step="1" placeholder="$0"/></label></>:<><div className="two"><label>Starts<input name="startAt" type="datetime-local" step="1800" required/></label><label>Ends<input name="endAt" type="datetime-local" step="1800" required/></label></div><label>Reason<input name="reason" required placeholder="Maintenance, personal use…"/></label></>}<label>Internal notes<textarea name="notes" rows={3} placeholder="Visible to owner only"/></label>{error&&<div className="form-error"><AlertTriangle/>{error}</div>}<div className="form-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary" type="submit">{modal==='booking'?'Add booking':'Block time'}</button></div></form></div></div>}
function Metric({icon,label,value,note,warning=false}:{icon:ReactNode;label:string;value:number;note:string;warning?:boolean}){return <article className={'metric '+(warning?'warning':'')}><div className="metric-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div></article>}
export default App;
