import { useEffect, useState, type FormEvent } from 'react';
import { AlertTriangle, CheckCircle2, Scale } from 'lucide-react';

type Readiness={status:'APPROVED'|'ATTORNEY_APPROVAL_REQUIRED';approved:boolean;publicAgreementSigningAllowed:boolean;liveCheckoutAllowed:boolean;currentAgreementVersion:string;approval:{attorneyReviewDate:string;approvalReference:string;recordedAt:string}|null;reason:string};
const confirmation='RECORD_ATTORNEY_APPROVAL_FOR_CURRENT_AGREEMENT';

export default function AttorneyApprovalGate(){
 const [readiness,setReadiness]=useState<Readiness|null>(null);const [recording,setRecording]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const load=()=>fetch('/api/readiness/attorney-approval').then(response=>response.json()).then(setReadiness);useEffect(()=>{void load()},[]);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!readiness)return;setBusy(true);setError('');const values=Object.fromEntries(new FormData(event.currentTarget));const response=await fetch('/api/readiness/attorney-approval',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...values,agreementVersion:readiness.currentAgreementVersion,confirmation})});const result=await response.json();setBusy(false);if(!response.ok){setError(result.error||'Approval could not be recorded.');return}setReadiness(result);setRecording(false)}
 if(!readiness)return <section className="panel attorney-gate"><span>Checking attorney-approval release gate…</span></section>;
 return <section className={`panel attorney-gate ${readiness.approved?'approved':'blocked'}`} aria-labelledby="attorney-gate-title"><div className="attorney-gate-head"><div className="attorney-gate-icon">{readiness.approved?<CheckCircle2/>:<Scale/>}</div><div><p>PUBLIC RELEASE GATE</p><h3 id="attorney-gate-title">{readiness.approved?'Attorney approval recorded':'Attorney Approval Required'}</h3></div><span className={`status ${readiness.approved?'completed':'pending_review'}`}>{readiness.status.replaceAll('_',' ')}</span></div><p>{readiness.reason}</p><dl><div><dt>Agreement version</dt><dd>{readiness.currentAgreementVersion}</dd></div><div><dt>Public agreement signing</dt><dd>{readiness.publicAgreementSigningAllowed?'Release gate passed':'Blocked'}</dd></div><div><dt>Live checkout</dt><dd>{readiness.liveCheckoutAllowed?'Release gate passed':'Blocked'}</dd></div></dl>{readiness.approval?<div className="attorney-approval-evidence"><strong>Recorded evidence</strong><span>Review date: {readiness.approval.attorneyReviewDate}</span><span>Approval reference: {readiness.approval.approvalReference}</span><small>This record applies only to the exact current source version and hash.</small></div>:<><button className="secondary" onClick={()=>setRecording(value=>!value)}>{recording?'Cancel':'Record attorney approval evidence'}</button>{recording&&<form onSubmit={event=>void submit(event)}><div className="form-warning"><AlertTriangle/>Record this only after Arizona counsel approves the displayed agreement version. This is not a simulation.</div><label>Attorney review date<input name="attorneyReviewDate" type="date" required/></label><label>Approval reference<input name="approvalReference" maxLength={240} placeholder="Counsel letter, matter, or internal approval reference" required/></label>{error&&<div className="form-error"><AlertTriangle/>{error}</div>}<button className="primary" disabled={busy}>{busy?'Recording…':'Confirm and record immutable approval'}</button></form>}</>}</section>;
}
