import { useEffect, useRef, useState } from 'react';
import { AlertTriangle, CheckCircle2, FileSignature, ShieldCheck } from 'lucide-react';
import { recoverCheckoutAfterConfirmationError } from './checkoutRecovery.js';

type Session={sessionId:number;state:string;statusLabel:string;expiresAt:string;token?:string;csrfToken?:string;quote?:Record<string,number>;clientSecret?:string|null;publishableKey?:string|null;reservationId?:number|null;confirmationCode?:string};
type StripeElementsLike={create(type:'payment'):{mount(selector:string):void;unmount():void}};
type StripeLike={elements(options:{clientSecret:string}):StripeElementsLike;confirmPayment(options:{elements:StripeElementsLike;redirect:'if_required'}):Promise<{error?:{message?:string}}>};
declare global{interface Window{Stripe?:(publishableKey:string)=>StripeLike}}
const money=(value:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(value/100);

export default function DirectCheckoutPreview({intent,onComplete}:{intent:Record<string,unknown>&{id:number;status:string;legal_name:string};onComplete?:()=>void}){
 const [session,setSession]=useState<Session|null>(null);const [token,setToken]=useState('');const [csrfToken,setCsrfToken]=useState('');const [choice,setChoice]=useState<'SEND_FORM'|'DECLINE_FORM'>('SEND_FORM');const [printedName,setPrintedName]=useState(intent.legal_name);const [accepted,setAccepted]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const finalizing=useRef(false);
 async function call(path:string,payload:Record<string,unknown>){setBusy(true);setError('');try{const response=await fetch(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw new Error(result.error||'This checkout step could not be completed.');setSession(current=>({...current,...result} as Session));return result as Session}catch(caught){setError((caught as Error).message);return null}finally{setBusy(false)}}
 async function begin(){const result=await call('/api/customer-preview/direct-checkout/sessions',{intentId:intent.id,idempotencyKey:`checkout_${intent.id}_${crypto.randomUUID()}`});if(result?.token&&result.csrfToken){setToken(result.token);setCsrfToken(result.csrfToken)}}
 async function refresh(){if(!token)return null;const response=await fetch('/api/customer-preview/direct-checkout/session',{headers:{'x-checkout-token':token}});const result=await response.json();if(response.ok){setSession(current=>({...current,...result}));return result as Session}setError(result.error||'Checkout status could not be refreshed.');return null}
 useEffect(()=>{if(session?.state!=='PAYMENT_COLLECTED'||!token||!csrfToken||finalizing.current)return;finalizing.current=true;setBusy(true);setError('');void fetch('/api/customer-preview/direct-checkout/finalize',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token,csrfToken,idempotencyKey:`checkout_convert_${session.sessionId}`})}).then(async response=>{const result=await response.json();if(!response.ok)throw new Error(result.error||'Your payment was accepted, but the booking could not be finalized. Do not retry payment; contact Trailer Bros.');setSession(current=>({...current,...result} as Session))}).catch(caught=>setError((caught as Error).message)).finally(()=>{setBusy(false);finalizing.current=false})},[session?.state,session?.sessionId,token,csrfToken]);
 useEffect(()=>{if(session?.state==='COMPLETE')onComplete?.()},[session?.state,onComplete]);
 const eligible=intent.status==='SUBMITTED';
 return <section className="panel direct-checkout" aria-labelledby="direct-checkout-title"><div><p>PROTECTED DIRECT CHECKOUT</p><h3 id="direct-checkout-title">Complete your synthetic reservation</h3><span>Every step is rechecked by Trailer Bros. Dates are not held until final confirmation.</span></div>{!session&&<button type="button" className="primary" disabled={!eligible||busy} onClick={()=>void begin()}>{eligible?'Continue to agreement':'Owner review is required'}</button>}
 {session?.state==='AGREEMENT_REQUIRED'&&<div className="checkout-step"><FileSignature/><div><strong>Review and acknowledge the rental agreement</strong><p>Staging agreement text remains marked for Arizona-attorney review.</p><label>Printed legal name<input value={printedName} onChange={event=>setPrintedName(event.target.value)}/></label><label className="check"><input type="checkbox" checked={accepted} onChange={event=>setAccepted(event.target.checked)}/>I electronically consent, acknowledge the displayed terms and insurance requirement, and choose a pickup-condition option below.</label><fieldset><legend>Pickup-condition choice</legend><label className="check"><input type="radio" checked={choice==='SEND_FORM'} onChange={()=>setChoice('SEND_FORM')}/>Send me the pickup-condition inspection form.</label><label className="check"><input type="radio" checked={choice==='DECLINE_FORM'} onChange={()=>setChoice('DECLINE_FORM')}/>I decline the offered pickup-condition inspection form.</label></fieldset><button type="button" className="primary" disabled={!accepted||busy} onClick={()=>void call('/api/customer-preview/direct-checkout/agreement',{token,csrfToken,printedName,inspectionChoice:choice})}>Sign synthetic agreement</button></div></div>}
 {session?.state==='PAYMENT_REQUIRED'&&<div className="checkout-step"><ShieldCheck/><div><strong>Payment required</strong><p>The server will recheck availability and the authoritative total before creating a Stripe test Payment Intent.</p>{session.quote&&<p>Authoritative total: <b>{money(Number(session.quote.totalCents||0))}</b>, including the refundable $100 security deposit.</p>}{!session.clientSecret&&<button type="button" className="primary" disabled={busy} onClick={()=>void call('/api/customer-preview/direct-checkout/payment',{token,csrfToken,idempotencyKey:`checkout_payment_${session.sessionId}`})}>Start Stripe test payment</button>}</div></div>}
 {session?.clientSecret&&session.publishableKey&&['PAYMENT_PENDING','PAYMENT_REQUIRED'].includes(session.state)&&<CheckoutPayment clientSecret={session.clientSecret} publishableKey={session.publishableKey} authoritativeState={session.state} onRefresh={refresh}/>}
 {session?.state==='PAYMENT_PENDING'&&<div className="checkout-step"><strong>Confirming your payment</strong><p>Please stay on this page while Trailer Bros securely verifies the payment. Do not submit another payment.</p><button type="button" onClick={()=>void refresh()}>Check payment status</button></div>}
 {session?.state==='PAYMENT_COLLECTED'&&<div className="checkout-step"><CheckCircle2/><div><strong>Payment accepted</strong><p>We are completing the final availability and booking checks now. No additional action is needed.</p></div></div>}
 {session?.state==='COMPLETE'&&<div role="status" className="intent-success"><CheckCircle2/><div><strong>Booking confirmed</strong><p>Confirmation {session.confirmationCode||'recorded'}.</p></div></div>}
 {session&&<p className="checkout-state">{session.statusLabel||session.state} · expires {new Date(session.expiresAt).toLocaleString('en-US',{timeZone:'America/Phoenix'})} Arizona time</p>}{error&&<div role="alert" className="form-error"><AlertTriangle/>{error}</div>}</section>
}

function CheckoutPayment({clientSecret,publishableKey,authoritativeState,onRefresh}:{clientSecret:string;publishableKey:string;authoritativeState:string;onRefresh:()=>Promise<Session|null>}){const [stripe,setStripe]=useState<StripeLike|null>(null);const [elements,setElements]=useState<StripeElementsLike|null>(null);const [busy,setBusy]=useState(false);const [retryAllowed,setRetryAllowed]=useState(true);const [error,setError]=useState('');useEffect(()=>{if(authoritativeState==='PAYMENT_REQUIRED')setRetryAllowed(true)},[authoritativeState]);useEffect(()=>{let active=true;let mounted:{mount(selector:string):void;unmount():void}|undefined;async function setup(){let script=document.querySelector<HTMLScriptElement>('script[data-stripe-js]');if(!script){script=document.createElement('script');script.src='https://js.stripe.com/v3/';script.async=true;script.dataset.stripeJs='true';document.head.appendChild(script)}if(!window.Stripe)await new Promise<void>((resolve,reject)=>{script!.addEventListener('load',()=>resolve(),{once:true});script!.addEventListener('error',()=>reject(new Error('Stripe test checkout could not load.')),{once:true})});if(!active||!window.Stripe)return;const instance=window.Stripe(publishableKey);const created=instance.elements({clientSecret});mounted=created.create('payment');mounted.mount('#direct-checkout-payment-element');setStripe(instance);setElements(created)}void setup().catch(caught=>setError((caught as Error).message));return()=>{active=false;mounted?.unmount()}},[clientSecret,publishableKey]);async function confirm(){if(!stripe||!elements||!retryAllowed)return;setBusy(true);setRetryAllowed(false);setError('');try{const result=await stripe.confirmPayment({elements,redirect:'if_required'});const recovery=await recoverCheckoutAfterConfirmationError(onRefresh);if(result.error&&recovery.retryAllowed){setRetryAllowed(true);setError(`${result.error.message||'Payment was not accepted.'} The server confirms no payment was collected; you may retry.`)}else if(recovery.stillReconciling)setError('Stripe is still confirming the payment. Do not retry yet; refresh the authoritative status shortly.')}catch{setError('The authoritative payment status could not be refreshed. Do not retry until the status check succeeds.')}finally{setBusy(false)}}return <div className="stripe-test-checkout"><strong>Stripe test payment</strong><div id="direct-checkout-payment-element"/><button type="button" disabled={!stripe||busy||!retryAllowed} onClick={()=>void confirm()}>{busy?'Checking authoritative status…':retryAllowed?'Confirm test payment':'Awaiting server reconciliation'}</button>{error&&<div className="form-error"><AlertTriangle/>{error}</div>}<p>Test mode only. Signed server reconciliation—not the browser—controls confirmation.</p></div>}
