import { useState, type FormEvent } from 'react';
import { AlertTriangle, CheckCircle2, ClipboardCheck, Edit3, LogOut, RotateCcw, ShieldCheck, XCircle } from 'lucide-react';

type RecordLike=Record<string,unknown>;
export type OperationalReservation=RecordLike&{id:number;status:string;operational_status?:string;pickup_at:string;return_at:string;rental_charge_cents:number;dolly_days:number;notes?:string;external_reference?:string;version:number;inspections?:RecordLike[];cancellation_outcome?:RecordLike|null;deposit_decision?:RecordLike|null;audit_events?:RecordLike[]};
const label=(s:string)=>s.toLowerCase().replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const localInput=(iso:string)=>{const d=new Date(iso);const local=new Date(d.getTime()-d.getTimezoneOffset()*60000);return local.toISOString().slice(0,16)};

export default function ReservationOperations({reservation:r,onChanged}:{reservation:OperationalReservation;onChanged:()=>Promise<void>}){
 const [mode,setMode]=useState<string|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const op=r.operational_status||r.status;
 async function send(path:string,method:string,body:unknown){setBusy(true);setError('');try{const response=await fetch(path,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=response.status===204?{}:await response.json();if(!response.ok)throw new Error(result.error||'Action failed.');setMode(null);await onChanged()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const action=(to:string,notes='Owner action')=>send(`/api/reservations/${r.id}/transition`,'POST',{to,notes});
 return <section className="operations-card"><div className="operations-head"><div><p>OWNER ACTIONS</p><h3>{label(op)}</h3></div><span>All actions are recorded</span></div><div className="operation-buttons">
  {!['COMPLETED','CANCELLED','NO_SHOW'].includes(r.status)&&<button onClick={()=>setMode('edit')}><Edit3/>Edit / reschedule</button>}
  {r.status==='PENDING_REVIEW'&&<button className="positive" onClick={()=>void action('CONFIRMED','Owner approved reservation')}><CheckCircle2/>Confirm</button>}
  {r.status==='CONFIRMED'&&<button className="positive" onClick={()=>setMode('pickup')}><LogOut/>Pickup inspection</button>}
  {r.status==='CHECKED_OUT'&&<button className="positive" onClick={()=>setMode('return')}><RotateCcw/>Return inspection</button>}
  {r.status==='INSPECTION_PENDING'&&!r.deposit_decision&&<><button className="positive" onClick={()=>setMode('release')}><ShieldCheck/>Record release</button><button onClick={()=>setMode('retain')}><AlertTriangle/>Record damage retain</button></>}
  {r.status==='INSPECTION_PENDING'&&r.deposit_decision&&<button className="positive" onClick={()=>void action('COMPLETED','Inspection and deposit decision complete')}><ClipboardCheck/>Complete rental</button>}
  {['PENDING_REVIEW','CONFIRMED'].includes(r.status)&&<button className="danger" onClick={()=>setMode('cancel')}><XCircle/>Cancel</button>}
  {r.status==='CONFIRMED'&&<button className="danger" onClick={()=>setMode('no_show')}><XCircle/>No show</button>}
 </div>{error&&<div className="form-error"><AlertTriangle/>{error}</div>}{mode&&<OperationForm mode={mode} reservation={r} busy={busy} close={()=>{setMode(null);setError('')}} submit={(path,method,body)=>void send(path,method,body)}/>}</section>
}

function OperationForm({mode,reservation:r,busy,close,submit}:{mode:string;reservation:OperationalReservation;busy:boolean;close:()=>void;submit:(path:string,method:string,body:unknown)=>void}){
 function handle(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(mode==='edit')return submit(`/api/reservations/${r.id}`,'PATCH',{version:r.version,pickupAt:f.get('pickupAt'),returnAt:f.get('returnAt'),rentalChargeCents:Number(f.get('rentalChargeDollars'))*100,dollyDays:Number(f.get('dollyDays')),notes:f.get('notes'),externalReference:r.external_reference||'',reason:f.get('reason')});if(['cancel','no_show'].includes(mode))return submit(`/api/reservations/${r.id}/outcome`,'POST',{type:mode==='no_show'?'NO_SHOW':'CANCELLATION',notes:f.get('notes')});if(['pickup','return'].includes(mode))return submit(`/api/reservations/${r.id}/inspections/${mode}`,'POST',{conditionNotes:f.get('conditionNotes'),usageTripNotes:f.get('usageTripNotes'),damageFound:f.get('damageFound')==='on',damageNotes:f.get('damageNotes'),photoReferences:String(f.get('photoReferences')||'').split(/\r?\n/).map(v=>v.trim()).filter(Boolean)});return submit(`/api/reservations/${r.id}/deposit-decision`,'POST',{decision:mode==='retain'?'RETAIN_RECORDED':'RELEASE_RECORDED',amountCents:mode==='retain'?Number(f.get('amountDollars'))*100:0,reason:f.get('reason'),damageNotes:f.get('damageNotes')||undefined})}
 const title={edit:'Edit / reschedule',cancel:'Record cancellation',no_show:'Record no show',pickup:'Pickup inspection',return:'Return inspection',release:'Record deposit release decision',retain:'Record damage retain decision'}[mode]||'Owner action';
 return <form className="operation-form" onSubmit={handle}><h4>{title}</h4>{mode==='edit'&&<><div className="two"><label>Pickup<input name="pickupAt" type="datetime-local" step="1800" defaultValue={localInput(r.pickup_at)} required/></label><label>Return<input name="returnAt" type="datetime-local" step="1800" defaultValue={localInput(r.return_at)} required/></label></div><div className="two"><label>Rental charge<input name="rentalChargeDollars" type="number" min="0" defaultValue={r.rental_charge_cents/100}/></label><label>Dolly days<input name="dollyDays" type="number" min="0" defaultValue={r.dolly_days}/></label></div><label>Owner notes<textarea name="notes" defaultValue={r.notes||''}/></label><label>Reason for change<input name="reason" required/></label></>}{['cancel','no_show'].includes(mode)&&<><p className="operation-note">No payment is processed. This records the approved refund and retention outcome only.</p><label>Owner decision notes<textarea name="notes" required/></label></>}{['pickup','return'].includes(mode)&&<><label>Condition notes<textarea name="conditionNotes" required/></label><label>Usage / trip notes<textarea name="usageTripNotes"/></label><label className="check"><input type="checkbox" name="damageFound"/> Damage found</label><label>Damage notes<textarea name="damageNotes"/></label><label>Local photo references, one per line<textarea name="photoReferences" placeholder="Local development references only"/></label></>}{mode==='release'&&<><p className="operation-note">Owner-recorded placeholder only. No payment authorization or release occurs.</p><label>Release reason<input name="reason" required defaultValue="Return inspection complete; release recorded"/></label></>}{mode==='retain'&&<><p className="operation-note">Requires a completed return inspection. No payment action occurs.</p><label>Amount to retain<input name="amountDollars" type="number" min="1" required/></label><label>Reason<input name="reason" required/></label><label>Damage notes<textarea name="damageNotes" required/></label></>}<div className="form-actions"><button type="button" className="secondary" onClick={close}>Close</button><button className="primary" disabled={busy}>{busy?'Saving…':'Record action'}</button></div></form>
}
