import { useState, type FormEvent } from 'react';
import { AlertTriangle, CheckCircle2, ClipboardCheck, Edit3, FileSignature, LogOut, RotateCcw, ShieldCheck, XCircle } from 'lucide-react';
import { toArizonaInput } from '../shared/arizonaTime';

type RecordLike = Record<string, unknown>;
export type OperationalReservation = RecordLike & { id:number;status:string;operational_status?:string;pickup_at:string;return_at:string;rental_charge_cents:number;dolly_days:number;notes?:string;external_reference?:string;version:number;inspections?:RecordLike[];agreements?:RecordLike[];pickup_condition?:RecordLike|null;cancellation_outcome?:RecordLike|null;deposit_decision?:RecordLike|null;audit_events?:RecordLike[] };
const label = (status:string) => status.toLowerCase().replaceAll('_',' ').replace(/\b\w/g,character=>character.toUpperCase());

export default function ReservationOperations({reservation,onChanged}:{reservation:OperationalReservation;onChanged:()=>Promise<void>}) {
  const [mode,setMode]=useState<string|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const operationalStatus=reservation.operational_status||reservation.status;
  async function send(path:string,method:string,body:unknown) { setBusy(true);setError('');try { const response=await fetch(path,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=response.status===204?{}:await response.json();if(!response.ok)throw new Error(result.error||'Action failed.');setMode(null);await onChanged(); } catch(caught) { setError((caught as Error).message); } finally { setBusy(false); } }
  const transition=(to:string,notes='Owner action')=>send(`/api/reservations/${reservation.id}/transition`,'POST',{to,notes});
  return <section className="operations-card">
    <div className="operations-head"><div><p>OWNER ACTIONS</p><h3>{label(operationalStatus)}</h3></div><span>All actions are recorded</span></div>
    <div className="operation-buttons">
      <button className="positive" onClick={()=>void send(`/api/reservations/${reservation.id}/agreements`,'POST',{})}><FileSignature/>Open agreement</button>
      {reservation.agreements?.[0]?.status==='OPENED'&&<button onClick={()=>setMode('sign_agreement')}><FileSignature/>Record synthetic signature</button>}
      {(!reservation.pickup_condition||reservation.pickup_condition.status==='PENDING')&&<><button onClick={()=>setMode('condition_complete')}><ClipboardCheck/>Pickup condition</button><button onClick={()=>setMode('condition_decline')}><XCircle/>Record inspection decline</button></>}
      {!['COMPLETED','CANCELLED','NO_SHOW'].includes(reservation.status)&&<button onClick={()=>setMode('edit')}><Edit3/>Edit / reschedule</button>}
      {reservation.status==='PENDING_REVIEW'&&<button className="positive" onClick={()=>void transition('CONFIRMED','Owner approved reservation')}><CheckCircle2/>Confirm</button>}
      {reservation.status==='CONFIRMED'&&<button className="positive" onClick={()=>setMode('pickup')}><LogOut/>Pickup inspection</button>}
      {reservation.status==='CHECKED_OUT'&&<button className="positive" onClick={()=>setMode('return')}><RotateCcw/>Return inspection</button>}
      {reservation.status==='INSPECTION_PENDING'&&!reservation.deposit_decision&&<><button className="positive" onClick={()=>setMode('release')}><ShieldCheck/>Record release</button><button onClick={()=>setMode('retain')}><AlertTriangle/>Record damage retain</button></>}
      {reservation.status==='INSPECTION_PENDING'&&reservation.deposit_decision&&<button className="positive" onClick={()=>void transition('COMPLETED','Inspection and deposit decision complete')}><ClipboardCheck/>Complete rental</button>}
      {['PENDING_REVIEW','CONFIRMED'].includes(reservation.status)&&<button className="danger" onClick={()=>setMode('cancel')}><XCircle/>Cancel</button>}
      {reservation.status==='CONFIRMED'&&<button className="danger" onClick={()=>setMode('no_show')}><XCircle/>No show</button>}
    </div>
    {error&&<div className="form-error"><AlertTriangle/>{error}</div>}
    {mode&&<OperationForm mode={mode} reservation={reservation} busy={busy} close={()=>{setMode(null);setError('');}} submit={(path,method,body)=>void send(path,method,body)}/>}
  </section>;
}

function OperationForm({mode,reservation,busy,close,submit}:{mode:string;reservation:OperationalReservation;busy:boolean;close:()=>void;submit:(path:string,method:string,body:unknown)=>void}) {
  function handle(event:FormEvent<HTMLFormElement>) { event.preventDefault();const form=new FormData(event.currentTarget);
    if(mode==='edit')return submit(`/api/reservations/${reservation.id}`,'PATCH',{version:reservation.version,pickupAt:form.get('pickupAt'),returnAt:form.get('returnAt'),rentalChargeCents:Number(form.get('rentalChargeDollars'))*100,dollyDays:Number(form.get('dollyDays')),notes:form.get('notes'),externalReference:reservation.external_reference||'',reason:form.get('reason')});
    if(['cancel','no_show'].includes(mode))return submit(`/api/reservations/${reservation.id}/outcome`,'POST',{type:mode==='no_show'?'NO_SHOW':'CANCELLATION',notes:form.get('notes')});
    if(['pickup','return'].includes(mode))return submit(`/api/reservations/${reservation.id}/inspections/${mode}`,'POST',{conditionNotes:form.get('conditionNotes'),usageTripNotes:form.get('usageTripNotes'),damageFound:form.get('damageFound')==='on',damageNotes:form.get('damageNotes'),photoReferences:String(form.get('photoReferences')||'').split(/\r?\n/).map(value=>value.trim()).filter(Boolean)});
    if(mode==='sign_agreement')return submit(`/api/agreements/${reservation.agreements?.[0]?.id}/sign`,'POST',{printedName:form.get('printedName'),electronicRecordsConsent:form.get('electronicRecordsConsent')==='on',termsAcknowledged:form.get('termsAcknowledged')==='on',driverInsuranceAcknowledged:form.get('driverInsuranceAcknowledged')==='on',inspectionOpportunityAcknowledged:form.get('inspectionOpportunityAcknowledged')==='on'});
    if(mode==='condition_complete')return submit(`/api/reservations/${reservation.id}/pickup-condition/complete`,'POST',{checklist:{lights:form.get('lights')==='on',tires:form.get('tires')==='on',hitch:form.get('hitch')==='on',deck:form.get('deck')==='on'},generalNotes:form.get('generalNotes'),markedDamageAreas:String(form.get('markedDamageAreas')||'').split(/\r?\n/).map(value=>value.trim()).filter(Boolean),customerAcknowledged:form.get('customerAcknowledged')==='on'});
    if(mode==='condition_decline')return submit(`/api/reservations/${reservation.id}/pickup-condition/decline`,'POST',{affirmativeDecline:form.get('affirmativeDecline')==='on',acknowledgment:'I affirmatively decline the offered pre-pickup condition inspection.'});
    return submit(`/api/reservations/${reservation.id}/deposit-decision`,'POST',{decision:mode==='retain'?'RETAIN_RECORDED':'RELEASE_RECORDED',amountCents:mode==='retain'?Number(form.get('amountDollars'))*100:0,reason:form.get('reason'),damageNotes:form.get('damageNotes')||undefined});
  }
  const title={edit:'Edit / reschedule',cancel:'Record cancellation',no_show:'Record no show',pickup:'Pickup inspection',return:'Return inspection',release:'Record deposit release decision',retain:'Record damage retain decision',sign_agreement:'Synthetic in-person agreement',condition_complete:'Pickup condition report',condition_decline:'Decline pickup condition report'}[mode]||'Owner action';
  return <form className="operation-form" onSubmit={handle}>
    <h4>{title}</h4>
    {mode==='edit'&&<><div className="two"><label>Pickup<input name="pickupAt" type="datetime-local" step="900" defaultValue={toArizonaInput(reservation.pickup_at)} required/></label><label>Return<input name="returnAt" type="datetime-local" step="900" defaultValue={toArizonaInput(reservation.return_at)} required/></label></div><div className="two"><label>Rental charge<input name="rentalChargeDollars" type="number" min="0" defaultValue={reservation.rental_charge_cents/100}/></label><label>Dolly days<input name="dollyDays" type="number" min="0" defaultValue={reservation.dolly_days}/></label></div><label>Owner notes<textarea name="notes" defaultValue={reservation.notes||''}/></label><label>Reason for change<input name="reason" required/></label></>}
    {['cancel','no_show'].includes(mode)&&<><p className="operation-note">No payment is processed. This records the approved refund and retention outcome only.</p><label>Owner decision notes<textarea name="notes" required/></label></>}
    {['pickup','return'].includes(mode)&&<><label>Condition notes<textarea name="conditionNotes" required/></label><label>Usage / trip notes<textarea name="usageTripNotes"/></label><label className="check"><input type="checkbox" name="damageFound"/> Damage found</label><label>Damage notes<textarea name="damageNotes"/></label><label>Photo metadata labels, one per line<textarea name="photoReferences" placeholder="Short labels only; no paths, URLs, or files"/></label><p className="operation-note">Hosted photo attachments are disabled. Secure photo storage is planned for a later phase.</p></>}
    {mode==='sign_agreement'&&<><p className="operation-note">Protected synthetic preview only. No link, email, text, payment, or legally final PDF is created.</p><label>Printed name<input name="printedName" required/></label><label className="check"><input type="checkbox" name="electronicRecordsConsent" required/> Consent to electronic records and signature</label><label className="check"><input type="checkbox" name="termsAcknowledged" required/> Agreement terms acknowledged</label><label className="check"><input type="checkbox" name="driverInsuranceAcknowledged" required/> Named renter/driver and insurance acknowledged</label><label className="check"><input type="checkbox" name="inspectionOpportunityAcknowledged" required/> Opportunity to inspect before possession acknowledged</label></>}
    {mode==='condition_complete'&&<><p className="operation-note">Customer-facing synthetic preview. Photo labels are metadata only; hosted uploads remain disabled.</p><div className="two"><label className="check"><input type="checkbox" name="lights"/>Lights reviewed</label><label className="check"><input type="checkbox" name="tires"/>Tires reviewed</label><label className="check"><input type="checkbox" name="hitch"/>Hitch reviewed</label><label className="check"><input type="checkbox" name="deck"/>Deck reviewed</label></div><label>General notes<textarea name="generalNotes"/></label><label>Marked damage areas, one per line<textarea name="markedDamageAreas"/></label><label className="check"><input type="checkbox" name="customerAcknowledged" required/> Customer acknowledges this condition report</label></>}
    {mode==='condition_decline'&&<><p className="operation-note">Decline records only the affirmative choice not to complete the offered inspection. It does not accept unknown defects or forfeit a deposit.</p><label className="check"><input type="checkbox" name="affirmativeDecline" required/> I affirmatively decline the offered pre-pickup condition inspection.</label></>}
    {mode==='release'&&<><p className="operation-note">Owner-recorded placeholder only. No payment authorization or release occurs.</p><label>Release reason<input name="reason" required defaultValue="Return inspection complete; release recorded"/></label></>}
    {mode==='retain'&&<><p className="operation-note">Requires a completed return inspection. No payment action occurs.</p><label>Amount to retain<input name="amountDollars" type="number" min="1" required/></label><label>Reason<input name="reason" required/></label><label>Damage notes<textarea name="damageNotes" required/></label></>}
    <div className="form-actions"><button type="button" className="secondary" onClick={close}>Close</button><button className="primary" disabled={busy}>{busy?'Saving...':'Record action'}</button></div>
  </form>;
}
