import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { AlertTriangle, CheckCircle2, Clipboard, ClipboardCheck, Edit3, FileSignature, Link2, LogOut, MessageSquareText, RotateCcw, ShieldCheck, XCircle } from 'lucide-react';
import { toArizonaInput } from '../shared/arizonaTime';

type RecordLike = Record<string, unknown>;
export type OperationalReservation = RecordLike & { id:number;status:string;operational_status?:string;pickup_at:string;return_at:string;rental_charge_cents:number;dolly_days:number;notes?:string;external_reference?:string;version:number;inspections?:RecordLike[];agreements?:RecordLike[];agreement_documents?:RecordLike[];secure_links?:RecordLike[];payment_ledger?:RecordLike[];pickup_condition?:RecordLike|null;cancellation_outcome?:RecordLike|null;deposit_decision?:RecordLike|null;audit_events?:RecordLike[] };
const label = (status:string) => status.toLowerCase().replaceAll('_',' ').replace(/\b\w/g,character=>character.toUpperCase());

export default function ReservationOperations({reservation,onChanged}:{reservation:OperationalReservation;onChanged:()=>Promise<void>}) {
  const [mode,setMode]=useState<string|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const operationalStatus=reservation.operational_status||reservation.status;
  async function send(path:string,method:string,body:unknown) { setBusy(true);setError('');try { const response=await fetch(path,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=response.status===204?{}:await response.json();if(!response.ok)throw new Error(result.error||'Action failed.');setMode(null);await onChanged(); } catch(caught) { setError((caught as Error).message); } finally { setBusy(false); } }
  const transition=(to:string,notes='Owner action')=>send(`/api/reservations/${reservation.id}/transition`,'POST',{to,notes});
  return <section className="operations-card">
    <div className="operations-head"><div><p>OWNER ACTIONS</p><h3>{label(operationalStatus)}</h3></div><span>All actions are recorded</span></div>
    <div className="operation-buttons">
      <button className="positive" onClick={()=>void send(`/api/reservations/${reservation.id}/agreements`,'POST',{})}><FileSignature/>Open agreement</button>
      {reservation.agreements?.[0]?.status==='OPENED'&&<button onClick={()=>setMode('sign_agreement')}><FileSignature/>Record synthetic signature</button>}
      {reservation.agreements?.[0]?.status==='SIGNED'&&!reservation.agreement_documents?.length&&<button onClick={()=>void send(`/api/agreements/${reservation.agreements?.[0]?.id}/render-document`,'POST',{})}><FileSignature/>Generate print-ready agreement</button>}
      {!!reservation.agreement_documents?.length&&<a className="button-link" href={`/api/agreement-documents/${reservation.agreement_documents[0].id}`}><FileSignature/>Download print-ready agreement</a>}
      {(!reservation.pickup_condition||reservation.pickup_condition.status==='PENDING')&&<><button onClick={()=>setMode('condition_complete')}><ClipboardCheck/>Pickup condition</button><button onClick={()=>setMode('condition_decline')}><XCircle/>Record inspection decline</button></>}
      {!['COMPLETED','CANCELLED','NO_SHOW'].includes(reservation.status)&&<button onClick={()=>setMode('edit')}><Edit3/>Edit / reschedule</button>}
      {reservation.status==='PENDING_REVIEW'&&<button className="positive" onClick={()=>void transition('CONFIRMED','Owner approved reservation')}><CheckCircle2/>Confirm</button>}
      {reservation.status==='CONFIRMED'&&<button className="positive" onClick={()=>setMode('pickup')}><LogOut/>Pickup inspection</button>}
      {reservation.status==='CHECKED_OUT'&&<button className="positive" onClick={()=>setMode('return')}><RotateCcw/>Return inspection</button>}
      {reservation.status==='INSPECTION_PENDING'&&!reservation.deposit_decision&&<><button className="positive" onClick={()=>setMode('release')}><ShieldCheck/>Record release</button><button onClick={()=>setMode('retain')}><AlertTriangle/>Record damage retain</button></>}
      {reservation.status==='INSPECTION_PENDING'&&reservation.deposit_decision&&<button className="positive" onClick={()=>void transition('COMPLETED','Inspection and deposit decision complete')}><ClipboardCheck/>Complete rental</button>}
      {['PENDING_REVIEW','CONFIRMED'].includes(reservation.status)&&<button className="danger" onClick={()=>setMode('cancel')}><XCircle/>Cancel</button>}
      {reservation.status==='CONFIRMED'&&<button className="danger" onClick={()=>setMode('no_show')}><XCircle/>No show</button>}
    </div>
    {error&&<div className="form-error"><AlertTriangle/>{error}</div>}
    <PaymentPanel key={reservation.id} reservation={reservation} onChanged={onChanged}/>
    <SecureLinkPanel reservation={reservation} onChanged={onChanged}/>
    <CommunicationPanel reservationId={reservation.id}/>
    {!!reservation.agreement_documents?.length&&<p className="operation-note">Immutable synthetic document · renderer {String(reservation.agreement_documents[0].renderer_version)} · hash {String(reservation.agreement_documents[0].document_hash).slice(0,12)}…</p>}
    {mode&&<OperationForm mode={mode} reservation={reservation} busy={busy} close={()=>{setMode(null);setError('');}} submit={(path,method,body)=>void send(path,method,body)}/>}
  </section>;
}

type StripeElementsLike={create(type:'payment'):{mount(selector:string):void;unmount():void}};
type StripeLike={elements(options:{clientSecret:string}):StripeElementsLike;confirmPayment(options:{elements:StripeElementsLike;redirect:'if_required'}):Promise<{error?:{message?:string}}>};
declare global{interface Window{Stripe?:(publishableKey:string)=>StripeLike}}
// @ts-expect-error The dynamically loaded Stripe.js element exposes mount at runtime.
function StripeTestCheckout({clientSecret,publishableKey,onComplete}:{clientSecret:string;publishableKey:string;onComplete:()=>Promise<void>}){const [stripe,setStripe]=useState<StripeLike|null>(null);const [elements,setElements]=useState<StripeElementsLike|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);useEffect(()=>{let active=true;let mounted:{unmount():void}|undefined;async function setup(){let script=document.querySelector<HTMLScriptElement>('script[data-stripe-js]');if(!script){script=document.createElement('script');script.src='https://js.stripe.com/v3/';script.async=true;script.dataset.stripeJs='true';document.head.appendChild(script)}if(!window.Stripe)await new Promise<void>((resolve,reject)=>{script!.addEventListener('load',()=>resolve(),{once:true});script!.addEventListener('error',()=>reject(new Error('Stripe test checkout could not load.')),{once:true})});if(!active||!window.Stripe)return;const instance=window.Stripe(publishableKey);const created=instance.elements({clientSecret});mounted=created.create('payment');mounted.mount('#stripe-test-payment-element');setStripe(instance);setElements(created)}void setup().catch(caught=>setError((caught as Error).message));return()=>{active=false;mounted?.unmount()}},[clientSecret,publishableKey]);async function confirm(){if(!stripe||!elements)return;setBusy(true);setError('');const result=await stripe.confirmPayment({elements,redirect:'if_required'});if(result.error)setError(result.error.message||'Stripe test payment was not confirmed.');else await onComplete();setBusy(false)}return <div className="stripe-test-checkout"><strong>Stripe test card details</strong><div id="stripe-test-payment-element"/><button disabled={!stripe||busy} onClick={()=>void confirm()}>{busy?'Confirming test payment…':'Confirm Stripe test payment'}</button>{error&&<div className="form-error"><AlertTriangle/>{error}</div>}<p className="operation-note">Stripe test mode only. The server and webhook ledger—not this browser result—determine payment status.</p></div>}

function PaymentPanel({reservation,onChanged}:{reservation:OperationalReservation;onChanged:()=>Promise<void>}){
  const [preview,setPreview]=useState<RecordLike|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [checkout,setCheckout]=useState<{clientSecret:string;publishableKey:string}|null>(null);
  useEffect(()=>{setPreview(null);setCheckout(null);setError('')},[reservation.id]);
  const load=useCallback(async()=>{try{let response=await fetch(`/api/reservations/${reservation.id}/payment-preview`);let result=await response.json();if(!response.ok)throw new Error(result.error||'Payment preview unavailable.');if(result.stripeTestConfigured&&Array.isArray(result.ledger)&&result.ledger.some((entry:RecordLike)=>entry.kind==='PAYMENT_PENDING')){await fetch(`/api/reservations/${reservation.id}/payment-reconcile`,{method:'POST'});response=await fetch(`/api/reservations/${reservation.id}/payment-preview`);result=await response.json()}setPreview(result)}catch(caught){setError((caught as Error).message)}},[reservation.id]);
  useEffect(()=>{void load()},[load]);
  async function action(actionName:string){setBusy(true);setError('');try{const response=await fetch(`/api/reservations/${reservation.id}/payment-actions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:actionName,idempotencyKey:`owner_${actionName.toLowerCase()}_${crypto.randomUUID()}`,reason:`Owner synthetic ${actionName.toLowerCase()} rehearsal`})});const result=await response.json();if(!response.ok)throw new Error(result.blockers?.join(' ')||result.error||'Payment rehearsal failed.');if(result.clientSecret&&result.publishableKey)setCheckout({clientSecret:String(result.clientSecret),publishableKey:String(result.publishableKey)});await load();await onChanged()}catch(caught){setError((caught as Error).message)}finally{setBusy(false)}}
  const breakdown=preview?.breakdown as RecordLike|undefined;const money=(value:unknown)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(value||0)/100);const ledger=(preview?.ledger||[]) as RecordLike[];
  const alreadyStarted=ledger.some(item=>item.kind==='PAYMENT_PENDING'||item.kind==='PAYMENT_COLLECTED');
  return <div className="payment-panel"><div className="operations-head"><div><p>TEST ONLY — NO LIVE CHARGE</p><h3>Payment preview & ledger</h3></div><span>{preview?.stripeTestConfigured?'Stripe test mode':'Mock provider'}</span></div>{breakdown&&<div className="detail-grid"><div><span>Rental</span><strong>{money(breakdown.rentalCents)}</strong></div><div><span>Dolly</span><strong>{money(breakdown.dollyCents)}</strong></div><div><span>Approved delivery</span><strong>{money(breakdown.deliveryCents)}</strong></div><div><span>Refundable deposit collected</span><strong>{money(breakdown.depositCents)}</strong></div><div><span>Arizona tax</span><strong>No separate line</strong></div><div><span>Total due</span><strong>{money(breakdown.totalCents)}</strong></div></div>}<div className="operation-buttons"><button disabled={busy||!preview?.ready||alreadyStarted} onClick={()=>void action('COLLECT')}><ShieldCheck/>{preview?.stripeTestConfigured?'Start Stripe test checkout':'Rehearse collection'}</button><button disabled={busy||!ledger.some(item=>item.kind==='PAYMENT_COLLECTED')} onClick={()=>void action('POLICY_REFUND')}><RotateCcw/>Rehearse policy refund</button>{reservation.deposit_decision&&<button disabled={busy} onClick={()=>void action(reservation.deposit_decision?.decision==='RETAIN_RECORDED'?'DEPOSIT_RETAIN':'DEPOSIT_RELEASE')}><ClipboardCheck/>Rehearse deposit outcome</button>}</div>{checkout&&<StripeTestCheckout {...checkout} onComplete={async()=>{setCheckout(null);await load();await onChanged()}}/>}{!preview?.ready&&<p className="operation-note">Readiness blockers: {((preview?.blockers||[]) as string[]).join(' ')||'Loading…'}</p>}<div className="secure-link-list">{ledger.map(entry=><article key={String(entry.id)}><div><strong>{label(String(entry.kind))}</strong><span>{money(entry.amount_cents)} · {String(entry.status)} · {String(entry.provider)}</span></div></article>)}{!ledger.length&&<p className="operation-note">No collected, refunded, or retained amount is recorded.</p>}</div>{error&&<div className="form-error"><AlertTriangle/>{error}</div>}<p className="operation-note">Payment success never confirms a reservation or bypasses agreement, qualification, approval, or availability checks. Card data is handled by Stripe.js and never enters Rental OS.</p></div>;
}

const communicationOptions=[['BOOKING_REQUEST_RECEIVED','Booking request received'],['AGREEMENT_ACTION_NEEDED','Agreement action needed'],['PICKUP_INSPECTION_REMINDER','Pickup inspection reminder'],['PICKUP_INSTRUCTIONS','Pickup instructions'],['RETURN_REMINDER','Return reminder'],['DEPOSIT_OUTCOME','Deposit outcome']];
function CommunicationPanel({reservationId}:{reservationId:number}){const [records,setRecords]=useState<RecordLike[]>([]);const [selected,setSelected]=useState(communicationOptions[0][0]);const [error,setError]=useState('');const load=useCallback(()=>fetch(`/api/reservations/${reservationId}/communications`).then(response=>response.json()).then(setRecords).catch(()=>setError('Communication previews are unavailable.')),[reservationId]);useEffect(()=>{void load()},[load]);async function preview(){setError('');const response=await fetch(`/api/reservations/${reservationId}/communications`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({templateKey:selected})});const result=await response.json();if(!response.ok)return setError(result.error||'Preview could not be created.');await load()}async function copy(record:RecordLike){await navigator.clipboard.writeText(`${record.subject_text}\n\n${record.body_text}`);await fetch(`/api/communications/${record.id}/copied`,{method:'POST'});await load()}return <div className="communication-panel"><div className="operations-head"><div><p>OWNER PREVIEW ONLY</p><h3>Fixed communications</h3></div><span>No message is sent</span></div><div className="operation-buttons"><select aria-label="Communication template" value={selected} onChange={event=>setSelected(event.target.value)}>{communicationOptions.map(([key,name])=><option key={key} value={key}>{name}</option>)}</select><button onClick={()=>void preview()}><MessageSquareText/>Create preview</button></div>{records[0]&&<article className="communication-preview"><strong>{String(records[0].subject_text)}</strong><p>{String(records[0].body_text)}</p><div className="operation-buttons"><button onClick={()=>void copy(records[0])}><Clipboard/>Copy text</button><span>{String(records[0].status)} · template {String(records[0].template_version)}</span></div></article>}{!records.length&&<p className="operation-note">No communication preview recorded.</p>}{error&&<div className="form-error"><AlertTriangle/>{error}</div>}<p className="operation-note">Deterministic approved variables only. Gmail, text messaging, and all delivery integrations remain disconnected.</p></div>}

function SecureLinkPanel({reservation,onChanged}:{reservation:OperationalReservation;onChanged:()=>Promise<void>}){
  const [token,setToken]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const links=reservation.secure_links||[];
  async function request(path:string,method:string,body:unknown){setBusy(true);setError('');try{const response=await fetch(path,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error||'Secure-link action failed.');setToken(String(result.token||''));await onChanged()}catch(caught){setError((caught as Error).message)}finally{setBusy(false)}}
  const generate=(purpose:string)=>request(`/api/reservations/${reservation.id}/secure-links`,'POST',{purpose,expiresInMinutes:60});
  return <div className="secure-link-panel"><div className="operations-head"><div><p>PROTECTED SYNTHETIC LINKS</p><h3>Secure-link status</h3></div><span>Raw tokens display once</span></div><div className="operation-buttons"><button disabled={busy} onClick={()=>void generate('AGREEMENT_SIGNING')}><Link2/>Agreement link</button><button disabled={busy} onClick={()=>void generate('PICKUP_INSPECTION')}><Link2/>Pickup link</button><button disabled={busy} onClick={()=>void generate('RETURN_INSPECTION')}><Link2/>Return link</button></div>{token&&<div className="one-time-token"><strong>Copy now — this token will not be shown again.</strong><code>{token}</code><div className="operation-buttons"><button onClick={()=>void navigator.clipboard.writeText(token)}><Clipboard/>Copy token</button><button onClick={()=>setToken('')}>Hide permanently</button></div></div>}<div className="secure-link-list">{links.map(link=><article key={String(link.id)}><div><strong>{label(String(link.purpose))}</strong><span>{String(link.status)} · expires {new Date(String(link.expires_at)).toLocaleString('en-US',{timeZone:'America/Phoenix'})} · fingerprint {String(link.token_fingerprint)}</span></div><div className="operation-buttons">{link.status==='ACTIVE'&&<button disabled={busy} onClick={()=>void request(`/api/secure-links/${link.id}`,'DELETE',{confirm:true,reason:'Owner revoked synthetic link'})}>Revoke</button>}<button disabled={busy} onClick={()=>void request(`/api/secure-links/${link.id}/regenerate`,'POST',{expiresInMinutes:60})}>Regenerate</button></div></article>)}{!links.length&&<p className="operation-note">No secure links created for this reservation.</p>}</div>{error&&<div className="form-error"><AlertTriangle/>{error}</div>}<p className="operation-note">All links remain behind Cloudflare Access. No email, text, public route, or workflow action is enabled.</p></div>
}

function OperationForm({mode,reservation,busy,close,submit}:{mode:string;reservation:OperationalReservation;busy:boolean;close:()=>void;submit:(path:string,method:string,body:unknown)=>void}) {
  function handle(event:FormEvent<HTMLFormElement>) { event.preventDefault();const form=new FormData(event.currentTarget);
    if(mode==='edit')return submit(`/api/reservations/${reservation.id}`,'PATCH',{version:reservation.version,pickupAt:form.get('pickupAt'),returnAt:form.get('returnAt'),rentalChargeCents:Number(form.get('rentalChargeDollars'))*100,dollyDays:Number(form.get('dollyDays')),notes:form.get('notes'),externalReference:reservation.external_reference||'',reason:form.get('reason')});
    if(['cancel','no_show'].includes(mode))return submit(`/api/reservations/${reservation.id}/outcome`,'POST',{type:mode==='no_show'?'NO_SHOW':'CANCELLATION',notes:form.get('notes')});
    if(['pickup','return'].includes(mode))return submit(`/api/reservations/${reservation.id}/inspections/${mode}`,'POST',{conditionNotes:form.get('conditionNotes'),usageTripNotes:form.get('usageTripNotes'),damageFound:form.get('damageFound')==='on',damageNotes:form.get('damageNotes'),photoReferences:String(form.get('photoReferences')||'').split(/\r?\n/).map(value=>value.trim()).filter(Boolean)});
    if(mode==='sign_agreement')return submit(`/api/agreements/${reservation.agreements?.[0]?.id}/sign`,'POST',{printedName:form.get('printedName'),electronicRecordsConsent:form.get('electronicRecordsConsent')==='on',termsAcknowledged:form.get('termsAcknowledged')==='on',driverInsuranceAcknowledged:form.get('driverInsuranceAcknowledged')==='on',inspectionOpportunityAcknowledged:form.get('inspectionOpportunityAcknowledged')==='on'});
    if(mode==='condition_complete')return submit(`/api/reservations/${reservation.id}/pickup-condition/complete`,'POST',{checklist:{lights:form.get('lights')==='on',tires:form.get('tires')==='on',hitch:form.get('hitch')==='on',deck:form.get('deck')==='on'},generalNotes:form.get('generalNotes'),markedDamageAreas:String(form.get('markedDamageAreas')||'').split(/\r?\n/).map(value=>value.trim()).filter(Boolean),customerAcknowledged:form.get('customerAcknowledged')==='on'});
    if(mode==='condition_decline')return submit(`/api/reservations/${reservation.id}/pickup-condition/decline`,'POST',{affirmativeDecline:form.get('affirmativeDecline')==='on',acknowledgment:'I affirmatively decline the offered pre-pickup condition inspection.'});
    return submit(`/api/reservations/${reservation.id}/deposit-decision`,'POST',{decision:mode==='retain'?'RETAIN_RECORDED':'RELEASE_RECORDED',amountCents:mode==='retain'?Number(form.get('amountDollars'))*100:0,reason:form.get('reason'),damageNotes:form.get('damageNotes')||undefined});
  }
  const title={edit:'Edit / reschedule',cancel:'Record cancellation',no_show:'Record no show',pickup:'Pickup inspection',return:'Return inspection',release:'Record deposit release decision',retain:'Record damage retain decision',sign_agreement:'Synthetic in-person agreement',condition_complete:'Pickup condition report',condition_decline:'Decline pickup condition report'}[mode]||'Owner action';
  return <form className="operation-form" onSubmit={handle}>
    <h4>{title}</h4>
    {mode==='edit'&&<><div className="two"><label>Pickup<input name="pickupAt" type="datetime-local" step="900" defaultValue={toArizonaInput(reservation.pickup_at)} required/></label><label>Return<input name="returnAt" type="datetime-local" step="900" defaultValue={toArizonaInput(reservation.return_at)} required/></label></div><div className="two"><label>Rental charge<input name="rentalChargeDollars" type="number" min="0" defaultValue={reservation.rental_charge_cents/100}/></label><label>Dolly days<input name="dollyDays" type="number" min="0" defaultValue={reservation.dolly_days}/></label></div><label>Owner notes<textarea name="notes" defaultValue={reservation.notes||''}/></label><label>Reason for change<input name="reason" required/></label></>}
    {['cancel','no_show'].includes(mode)&&<><p className="operation-note">No payment is processed. This records the approved refund and retention outcome only.</p><label>Owner decision notes<textarea name="notes" required/></label></>}
    {['pickup','return'].includes(mode)&&<><label>Condition notes<textarea name="conditionNotes" required/></label><label>Usage / trip notes<textarea name="usageTripNotes"/></label><label className="check"><input type="checkbox" name="damageFound"/> Damage found</label><label>Damage notes<textarea name="damageNotes"/></label><label>Photo metadata labels, one per line<textarea name="photoReferences" placeholder="Short labels only; no paths, URLs, or files"/></label><p className="operation-note">Hosted photo attachments are disabled. Secure photo storage is planned for a later phase.</p></>}
    {mode==='sign_agreement'&&<><p className="operation-note">Protected synthetic preview only. No link, email, text, payment, or legally final PDF is created.</p><label>Printed name<input name="printedName" required/></label><label className="check"><input type="checkbox" name="electronicRecordsConsent" required/> Consent to electronic records and signature</label><label className="check"><input type="checkbox" name="termsAcknowledged" required/> Agreement terms acknowledged</label><label className="check"><input type="checkbox" name="driverInsuranceAcknowledged" required/> Named renter/driver and insurance acknowledged</label><label className="check"><input type="checkbox" name="inspectionOpportunityAcknowledged" required/> Opportunity to inspect before possession acknowledged</label></>}
    {mode==='condition_complete'&&<><p className="operation-note">Customer-facing synthetic preview. Photo labels are metadata only; hosted uploads remain disabled.</p><div className="two"><label className="check"><input type="checkbox" name="lights"/>Lights reviewed</label><label className="check"><input type="checkbox" name="tires"/>Tires reviewed</label><label className="check"><input type="checkbox" name="hitch"/>Hitch reviewed</label><label className="check"><input type="checkbox" name="deck"/>Deck reviewed</label></div><label>General notes<textarea name="generalNotes"/></label><label>Marked damage areas, one per line<textarea name="markedDamageAreas"/></label><label className="check"><input type="checkbox" name="customerAcknowledged" required/> Customer acknowledges this condition report</label></>}
    {mode==='condition_decline'&&<><p className="operation-note">Decline records only the affirmative choice not to complete the offered inspection. It does not accept unknown defects or forfeit a deposit.</p><label className="check"><input type="checkbox" name="affirmativeDecline" required/> I affirmatively decline the offered pre-pickup condition inspection.</label></>}
    {mode==='release'&&<><p className="operation-note">Owner-recorded placeholder only. No payment authorization or release occurs.</p><label>Release reason<input name="reason" required defaultValue="Return inspection complete; release recorded"/></label></>}
    {mode==='retain'&&<><p className="operation-note">Requires a completed return inspection. No payment action occurs.</p><label>Amount to retain<input name="amountDollars" type="number" min="1" required/></label><label>Reason<input name="reason" required/></label><label>Damage notes<textarea name="damageNotes" required/></label></>}
    <div className="form-actions"><button type="button" className="secondary" onClick={close}>Close</button><button className="primary" disabled={busy}>{busy?'Saving...':'Record action'}</button></div>
  </form>;
}
