CREATE TABLE `booking_intents` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`idempotency_key` text NOT NULL,
	`trailer_id` integer NOT NULL,
	`status` text DEFAULT 'SUBMITTED' NOT NULL,
	`legal_name` text NOT NULL,
	`email` text NOT NULL,
	`phone` text NOT NULL,
	`age_25_confirmed` integer NOT NULL,
	`named_renter_only_towing` integer NOT NULL,
	`tow_vehicle_details` text NOT NULL,
	`hitch_ball_acknowledged` integer NOT NULL,
	`brake_controller_acknowledged` integer NOT NULL,
	`insurance_acknowledged` integer NOT NULL,
	`intended_use` text NOT NULL,
	`trip_type` text NOT NULL,
	`interstate_details` text,
	`interstate_approval_required` integer DEFAULT false NOT NULL,
	`fulfillment_type` text NOT NULL,
	`delivery_address` text,
	`delivery_approval_required` integer DEFAULT false NOT NULL,
	`pickup_at` text NOT NULL,
	`return_at` text NOT NULL,
	`dolly_requested` integer DEFAULT false NOT NULL,
	`rental_days` integer NOT NULL,
	`rental_charge_cents` integer NOT NULL,
	`dolly_charge_cents` integer NOT NULL,
	`security_deposit_cents` integer NOT NULL,
	`delivery_charge_cents` integer,
	`tax_cents` integer DEFAULT 0 NOT NULL,
	`estimated_due_before_delivery_cents` integer NOT NULL,
	`exceptions_json` text DEFAULT '[]' NOT NULL,
	`expires_at` text NOT NULL,
	`is_synthetic` integer DEFAULT true NOT NULL,
	`created_at` text DEFAULT (datetime('now')) NOT NULL,
	`updated_at` text DEFAULT (datetime('now')) NOT NULL,
	FOREIGN KEY (`trailer_id`) REFERENCES `trailers`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE UNIQUE INDEX `booking_intent_idempotency_idx` ON `booking_intents` (`idempotency_key`);