import { sql } from 'drizzle-orm';
import { integer, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';

const timestamps = { createdAt: text('created_at').notNull().default(sql`(datetime('now'))`), updatedAt: text('updated_at').notNull().default(sql`(datetime('now'))`) };

export const trailers = sqliteTable('trailers', {
  id: integer('id').primaryKey({ autoIncrement: true }), name: text('name').notNull(), unitCode: text('unit_code').notNull().unique(),
  publishedPayloadLbs: integer('published_payload_lbs').notNull(), plateVerified: integer('plate_verified', { mode: 'boolean' }).notNull().default(false), active: integer('active', { mode: 'boolean' }).notNull().default(true), ...timestamps,
});
export const customers = sqliteTable('customers', {
  id: integer('id').primaryKey({ autoIncrement: true }), firstName: text('first_name').notNull(), lastName: text('last_name').notNull(), email: text('email'), phone: text('phone'), dateOfBirth: text('date_of_birth'), ...timestamps,
});
export const reservations = sqliteTable('reservations', {
  id: integer('id').primaryKey({ autoIncrement: true }), confirmationCode: text('confirmation_code').notNull().unique(), trailerId: integer('trailer_id').notNull().references(() => trailers.id), customerId: integer('customer_id').references(() => customers.id),
  channel: text('channel', { enum: ['DIRECT', 'EXTERNAL'] }).notNull(), externalSource: text('external_source', { enum: ['BIG_RENTALS', 'NEIGHBORS_TRAILER', 'FACEBOOK_MARKETPLACE', 'OTHER'] }), externalReference: text('external_reference'), status: text('status').notNull(),
  pickupAt: text('pickup_at').notNull(), returnAt: text('return_at').notNull(), rentalChargeCents: integer('rental_charge_cents').notNull().default(0), dollyDays: integer('dolly_days').notNull().default(0),
  isSynthetic: integer('is_synthetic', { mode: 'boolean' }).notNull().default(false),
  renterAge: integer('renter_age'), namedRenterWillTow: integer('named_renter_will_tow', { mode: 'boolean' }).notNull().default(true), interstateUse: integer('interstate_use', { mode: 'boolean' }).notNull().default(false), interstateApproved: integer('interstate_approved', { mode: 'boolean' }).notNull().default(false), internationalUse: integer('international_use', { mode: 'boolean' }).notNull().default(false),
  deliveryRequested: integer('delivery_requested', { mode: 'boolean' }).notNull().default(false), deliveryDistanceMiles: integer('delivery_distance_miles'), deliveryApproved: integer('delivery_approved', { mode: 'boolean' }).notNull().default(false), notes: text('notes'), version: integer('version').notNull().default(1), ...timestamps,
});
export const availabilityBlocks = sqliteTable('availability_blocks', {
  id: integer('id').primaryKey({ autoIncrement: true }), trailerId: integer('trailer_id').notNull().references(() => trailers.id), startAt: text('start_at').notNull(), endAt: text('end_at').notNull(), reason: text('reason').notNull(), notes: text('notes'), isSynthetic: integer('is_synthetic', { mode: 'boolean' }).notNull().default(false), ...timestamps,
});
export const payments = sqliteTable('payments', {
  id: integer('id').primaryKey({ autoIncrement: true }), reservationId: integer('reservation_id').notNull().references(() => reservations.id), kind: text('kind', { enum: ['RENTAL_CHARGE', 'SECURITY_DEPOSIT_AUTHORIZATION', 'REFUND', 'FORFEITURE'] }).notNull(), status: text('status', { enum: ['PENDING', 'SUCCEEDED', 'FAILED', 'AUTHORIZED', 'RELEASED', 'REFUNDED'] }).notNull(), amountCents: integer('amount_cents').notNull(), processor: text('processor').notNull().default('DEVELOPMENT'), externalId: text('external_id'), ...timestamps,
});
export const paymentLedgerEntries = sqliteTable('payment_ledger_entries', {
  id: integer('id').primaryKey({ autoIncrement: true }), reservationId: integer('reservation_id').references(() => reservations.id), bookingIntentId: integer('booking_intent_id'),
  kind: text('kind').notNull(), status: text('status').notNull(), amountCents: integer('amount_cents').notNull(), currency: text('currency').notNull().default('usd'), provider: text('provider').notNull().default('MOCK'), providerPaymentId: text('provider_payment_id'), providerRefundId: text('provider_refund_id'), idempotencyKey: text('idempotency_key').notNull(), reason: text('reason'), inspectionId: integer('inspection_id'), breakdownJson: text('breakdown_json').notNull().default('{}'), isSynthetic: integer('is_synthetic', { mode: 'boolean' }).notNull().default(true), createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
}, table => [uniqueIndex('payment_ledger_idempotency_idx').on(table.idempotencyKey)]);
export const paymentWebhookEvents = sqliteTable('payment_webhook_events', {
  id: integer('id').primaryKey({ autoIncrement: true }), providerEventId: text('provider_event_id').notNull(), eventType: text('event_type').notNull(), providerPaymentId: text('provider_payment_id'), processingStatus: text('processing_status').notNull(), sanitizedStatus: text('sanitized_status').notNull(), payloadHash: text('payload_hash').notNull(), errorCategory: text('error_category'), providerCreatedAt: text('provider_created_at').notNull(), processedAt: text('processed_at'), isSynthetic: integer('is_synthetic', { mode: 'boolean' }).notNull().default(true), createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
}, table => [uniqueIndex('payment_webhook_event_idx').on(table.providerEventId)]);
export const auditEvents = sqliteTable('audit_events', {
  id: integer('id').primaryKey({ autoIncrement: true }), aggregateType: text('aggregate_type').notNull(), aggregateId: integer('aggregate_id').notNull(), action: text('action').notNull(), actor: text('actor').notNull().default('owner'), payloadJson: text('payload_json').notNull().default('{}'), createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
}, (table) => [uniqueIndex('audit_event_identity_idx').on(table.id, table.aggregateType)]);

export const conditionInspections = sqliteTable('condition_inspections', {
  id: integer('id').primaryKey({ autoIncrement: true }), reservationId: integer('reservation_id').notNull().references(() => reservations.id), type: text('type', { enum: ['PICKUP', 'RETURN'] }).notNull(), conditionNotes: text('condition_notes').notNull(), usageTripNotes: text('usage_trip_notes'), damageFound: integer('damage_found', { mode: 'boolean' }).notNull().default(false), damageNotes: text('damage_notes'), inspectedAt: text('inspected_at').notNull(), actor: text('actor').notNull().default('owner'), ...timestamps,
});
export const inspectionPhotos = sqliteTable('inspection_photos', {
  id: integer('id').primaryKey({ autoIncrement: true }), inspectionId: integer('inspection_id').notNull().references(() => conditionInspections.id), localReference: text('local_reference').notNull(), caption: text('caption'), createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
});
export const cancellationOutcomes = sqliteTable('cancellation_outcomes', {
  id: integer('id').primaryKey({ autoIncrement: true }), reservationId: integer('reservation_id').notNull().references(() => reservations.id).unique(), type: text('type', { enum: ['CANCELLATION', 'NO_SHOW'] }).notNull(), decidedAt: text('decided_at').notNull(), noticeHours: integer('notice_hours').notNull(), rentalRefundCents: integer('rental_refund_cents').notNull(), retainedCents: integer('retained_cents').notNull(), paymentAction: text('payment_action').notNull().default('NOT_EXECUTED'), notes: text('notes'), ...timestamps,
});
export const depositDecisions = sqliteTable('deposit_decisions', {
  id: integer('id').primaryKey({ autoIncrement: true }), reservationId: integer('reservation_id').notNull().references(() => reservations.id).unique(), decision: text('decision', { enum: ['RELEASE_RECORDED', 'RETAIN_RECORDED'] }).notNull(), amountCents: integer('amount_cents').notNull(), reason: text('reason').notNull(), damageNotes: text('damage_notes'), paymentAction: text('payment_action').notNull().default('NOT_EXECUTED'), decidedAt: text('decided_at').notNull(), actor: text('actor').notNull().default('owner'), ...timestamps,
});

export const bookingIntents = sqliteTable('booking_intents', {
  id: integer('id').primaryKey({ autoIncrement: true }), idempotencyKey: text('idempotency_key').notNull(), trailerId: integer('trailer_id').notNull().references(() => trailers.id), status: text('status', { enum: ['SUBMITTED','REVIEW_REQUIRED','EXPIRED','CONVERTED'] }).notNull().default('SUBMITTED'),
  legalName: text('legal_name').notNull(), email: text('email').notNull(), phone: text('phone').notNull(), age25Confirmed: integer('age_25_confirmed', { mode: 'boolean' }).notNull(), namedRenterOnlyTowing: integer('named_renter_only_towing', { mode: 'boolean' }).notNull(),
  towVehicleDetails: text('tow_vehicle_details').notNull(), hitchBallAcknowledged: integer('hitch_ball_acknowledged', { mode: 'boolean' }).notNull(), brakeControllerAcknowledged: integer('brake_controller_acknowledged', { mode: 'boolean' }).notNull(), insuranceAcknowledged: integer('insurance_acknowledged', { mode: 'boolean' }).notNull(), intendedUse: text('intended_use').notNull(),
  tripType: text('trip_type', { enum: ['IN_STATE','INTERSTATE'] }).notNull(), interstateDetails: text('interstate_details'), interstateApprovalRequired: integer('interstate_approval_required', { mode: 'boolean' }).notNull().default(false), fulfillmentType: text('fulfillment_type', { enum: ['PICKUP','DELIVERY'] }).notNull(), deliveryAddress: text('delivery_address'), deliveryApprovalRequired: integer('delivery_approval_required', { mode: 'boolean' }).notNull().default(false),
  pickupAt: text('pickup_at').notNull(), returnAt: text('return_at').notNull(), dollyRequested: integer('dolly_requested', { mode: 'boolean' }).notNull().default(false), rentalDays: integer('rental_days').notNull(), rentalChargeCents: integer('rental_charge_cents').notNull(), dollyChargeCents: integer('dolly_charge_cents').notNull(), securityDepositCents: integer('security_deposit_cents').notNull(), deliveryChargeCents: integer('delivery_charge_cents'), deliveryQuoteStatus: text('delivery_quote_status', { enum: ['NOT_REQUESTED','AVAILABLE','OUT_OF_AREA','ROUTING_UNAVAILABLE'] }).notNull().default('NOT_REQUESTED'), deliveryDistanceMeters: integer('delivery_distance_meters'), deliveryZone: text('delivery_zone', { enum: ['ZONE_1','ZONE_2','ZONE_3'] }), deliveryQuotedAt: text('delivery_quoted_at'), deliveryOverrideFeeCents: integer('delivery_override_fee_cents'), deliveryOverrideReason: text('delivery_override_reason'), deliveryOverrideAt: text('delivery_override_at'), deliveryOverrideActor: text('delivery_override_actor'), taxCents: integer('tax_cents').notNull().default(0), estimatedDueBeforeDeliveryCents: integer('estimated_due_before_delivery_cents').notNull(), estimatedTotalCents: integer('estimated_total_cents').notNull().default(0),
  exceptionsJson: text('exceptions_json').notNull().default('[]'), expiresAt: text('expires_at').notNull(), isSynthetic: integer('is_synthetic', { mode: 'boolean' }).notNull().default(true), ...timestamps,
}, (table) => [uniqueIndex('booking_intent_idempotency_idx').on(table.idempotencyKey)]);

export const bookingIntentConversions = sqliteTable('booking_intent_conversions', {
  id: integer('id').primaryKey({ autoIncrement: true }), intentId: integer('intent_id').notNull().references(() => bookingIntents.id).unique(), idempotencyKey: text('idempotency_key').notNull().unique(), reservationId: integer('reservation_id').notNull().references(() => reservations.id).unique(), agreementEvidenceJson: text('agreement_evidence_json').notNull(), approvalSnapshotJson: text('approval_snapshot_json').notNull(), quoteSnapshotJson: text('quote_snapshot_json').notNull(), convertedAt: text('converted_at').notNull(), actor: text('actor').notNull(), isSynthetic: integer('is_synthetic', { mode: 'boolean' }).notNull().default(true), createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
});

export const directCheckoutSessions = sqliteTable('direct_checkout_sessions', {
  id: integer('id').primaryKey({ autoIncrement: true }), intentId: integer('intent_id').notNull().references(() => bookingIntents.id).unique(), tokenHash: text('token_hash').notNull().unique(), tokenFingerprint: text('token_fingerprint').notNull(), csrfHash: text('csrf_hash').notNull(),
  state: text('state', { enum: ['QUOTE_READY','AGREEMENT_REQUIRED','AGREEMENT_SIGNED','PAYMENT_REQUIRED','PAYMENT_PENDING','PAYMENT_COLLECTED','CONFIRMATION_PENDING','COMPLETE','OWNER_REVIEW_REQUIRED','UNAVAILABLE','EXPIRED','ABANDONED','REVOKED'] }).notNull().default('QUOTE_READY'),
  quoteHash: text('quote_hash').notNull(), agreementEvidenceId: integer('agreement_evidence_id'), providerPaymentId: text('provider_payment_id'), reservationId: integer('reservation_id').references(() => reservations.id), communicationId: integer('communication_id').references(() => communicationRecords.id),
  expiresAt: text('expires_at').notNull(), revokedAt: text('revoked_at'), abandonedAt: text('abandoned_at'), completedAt: text('completed_at'), lastTransitionAt: text('last_transition_at').notNull(), version: integer('version').notNull().default(1), isSynthetic: integer('is_synthetic', { mode: 'boolean' }).notNull().default(true), ...timestamps,
});

export const directCheckoutAgreements = sqliteTable('direct_checkout_agreements', {
  id: integer('id').primaryKey({ autoIncrement: true }), sessionId: integer('session_id').notNull().references(() => directCheckoutSessions.id).unique(), templateId: integer('template_id').notNull().references(() => agreementTemplates.id), templateVersion: text('template_version').notNull(), templateHash: text('template_hash').notNull(), renterSnapshotJson: text('renter_snapshot_json').notNull(), intentSnapshotJson: text('intent_snapshot_json').notNull(), quoteSnapshotJson: text('quote_snapshot_json').notNull(), pickupInspectionChoice: text('pickup_inspection_choice', { enum: ['SEND_FORM','DECLINE_FORM'] }).notNull(), printedName: text('printed_name').notNull(), signedAt: text('signed_at').notNull(), evidenceJson: text('evidence_json').notNull(), isSynthetic: integer('is_synthetic', { mode: 'boolean' }).notNull().default(true), createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
});

export const deliveryQuoteUsage = sqliteTable('delivery_quote_usage', {
  id: integer('id').primaryKey({ autoIncrement: true }), actorHash: text('actor_hash').notNull(), windowStartedAt: text('window_started_at').notNull(), requestCount: integer('request_count').notNull().default(0), createdAt: text('created_at').notNull().default(sql`(datetime('now'))`), updatedAt: text('updated_at').notNull().default(sql`(datetime('now'))`),
}, table => [uniqueIndex('delivery_quote_usage_window_idx').on(table.actorHash, table.windowStartedAt)]);

export const agreementTemplates = sqliteTable('agreement_templates', {
  id: integer('id').primaryKey({ autoIncrement: true }), version: text('version').notNull().unique(), sourceManifestVersion: text('source_manifest_version').notNull(), contentJson: text('content_json').notNull(), contentHash: text('content_hash').notNull().unique(), legalReviewStatus: text('legal_review_status').notNull().default('ATTORNEY_REVIEW_REQUIRED'), isSynthetic: integer('is_synthetic', { mode: 'boolean' }).notNull().default(true), createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
});
export const attorneyApprovalRecords = sqliteTable('attorney_approval_records', {
  id: integer('id').primaryKey({ autoIncrement: true }), agreementVersion: text('agreement_version').notNull(), agreementSourceHash: text('agreement_source_hash').notNull(), attorneyReviewDate: text('attorney_review_date').notNull(), approvalReference: text('approval_reference').notNull(), recordedAt: text('recorded_at').notNull(), recordedBy: text('recorded_by').notNull(), createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
});
export const agreementInstances = sqliteTable('agreement_instances', {
  id: integer('id').primaryKey({ autoIncrement: true }), reservationId: integer('reservation_id').notNull().references(() => reservations.id), templateId: integer('template_id').notNull().references(() => agreementTemplates.id), status: text('status', { enum: ['NOT_SENT','OPENED','SIGNED','EXPIRED'] }).notNull().default('NOT_SENT'), templateVersion: text('template_version').notNull(), templateHash: text('template_hash').notNull(), renterSnapshotJson: text('renter_snapshot_json').notNull(), reservationSnapshotJson: text('reservation_snapshot_json').notNull(), quoteSnapshotJson: text('quote_snapshot_json').notNull(), renderedAt: text('rendered_at').notNull(), electronicConsentAt: text('electronic_consent_at'), termsAcknowledgedAt: text('terms_acknowledged_at'), driverInsuranceAcknowledgedAt: text('driver_insurance_acknowledged_at'), inspectionOpportunityAcknowledgedAt: text('inspection_opportunity_acknowledged_at'), pickupInspectionChoice: text('pickup_inspection_choice', { enum: ['SEND_FORM','DECLINE_FORM'] }), pickupInspectionChoiceAt: text('pickup_inspection_choice_at'), signedAt: text('signed_at'), printedName: text('printed_name'), signatureEvidenceJson: text('signature_evidence_json'), isSynthetic: integer('is_synthetic', { mode: 'boolean' }).notNull().default(true), ...timestamps,
});
export const agreementDocuments = sqliteTable('agreement_documents', {
  id: integer('id').primaryKey({ autoIncrement: true }), agreementId: integer('agreement_id').notNull().references(() => agreementInstances.id), documentHash: text('document_hash').notNull().unique(), rendererVersion: text('renderer_version').notNull(), templateVersion: text('template_version').notNull(), contentType: text('content_type').notNull().default('text/html'), contentText: text('content_text').notNull(), generatedAt: text('generated_at').notNull(), isSynthetic: integer('is_synthetic', { mode: 'boolean' }).notNull().default(true), createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
});
export const pickupConditionChoices = sqliteTable('pickup_condition_choices', {
  id: integer('id').primaryKey({ autoIncrement: true }), reservationId: integer('reservation_id').notNull().references(() => reservations.id).unique(), status: text('status', { enum: ['PENDING','COMPLETED','DECLINED'] }).notNull().default('PENDING'), checklistJson: text('checklist_json').notNull().default('{}'), generalNotes: text('general_notes'), markedDamageJson: text('marked_damage_json').notNull().default('[]'), customerAcknowledgedAt: text('customer_acknowledged_at'), declineAcknowledgment: text('decline_acknowledgment'), decidedAt: text('decided_at'), actor: text('actor').notNull().default('owner'), isSynthetic: integer('is_synthetic', { mode: 'boolean' }).notNull().default(true), ...timestamps,
});

export const secureLinks = sqliteTable('secure_links', {
  id: integer('id').primaryKey({ autoIncrement: true }), reservationId: integer('reservation_id').notNull().references(() => reservations.id), purpose: text('purpose', { enum: ['AGREEMENT_SIGNING','PICKUP_INSPECTION','RETURN_INSPECTION'] }).notNull(), tokenHash: text('token_hash').notNull().unique(), tokenFingerprint: text('token_fingerprint').notNull(), expiresAt: text('expires_at').notNull(), revokedAt: text('revoked_at'), usedAt: text('used_at'), useCount: integer('use_count').notNull().default(0), lastUsedAt: text('last_used_at'), createdBy: text('created_by').notNull(), isSynthetic: integer('is_synthetic', { mode: 'boolean' }).notNull().default(true), ...timestamps,
});

export const secureLinkAttempts = sqliteTable('secure_link_attempts', {
  id: integer('id').primaryKey({ autoIncrement: true }), actorHash: text('actor_hash').notNull(), windowStartedAt: text('window_started_at').notNull(), attemptCount: integer('attempt_count').notNull().default(0), ...timestamps,
}, table => [uniqueIndex('secure_link_attempt_window_idx').on(table.actorHash, table.windowStartedAt)]);

export const communicationRecords = sqliteTable('communication_records', {
  id: integer('id').primaryKey({ autoIncrement: true }), reservationId: integer('reservation_id').notNull().references(() => reservations.id), communicationType: text('communication_type', { enum: ['BOOKING_CONFIRMATION','RENTAL_CLOSEOUT'] }).notNull(), recipient: text('recipient').notNull(), templateKey: text('template_key').notNull(), templateVersion: text('template_version').notNull(), sourceTemplateHash: text('source_template_hash').notNull(), renderedContentHash: text('rendered_content_hash').notNull(), subjectText: text('subject_text').notNull(), bodyText: text('body_text').notNull(), bodyHtml: text('body_html').notNull().default(''), state: text('state', { enum: ['PREVIEW_READY','COPIED','SEND_UNAVAILABLE','QUEUED','SEND_FAILED','SENT_UNVERIFIED','DELIVERED'] }).notNull().default('PREVIEW_READY'), status: text('status').notNull().default('PREVIEWED'), idempotencyKey: text('idempotency_key').notNull(), renderedAt: text('rendered_at').notNull(), preparedAt: text('prepared_at').notNull(), copiedAt: text('copied_at'), attemptedAt: text('attempted_at'), sentAt: text('sent_at'), deliveredAt: text('delivered_at'), safeErrorClassification: text('safe_error_classification'), providerMessageId: text('provider_message_id'), actor: text('actor').notNull(), isSynthetic: integer('is_synthetic', { mode: 'boolean' }).notNull().default(true), createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
}, table => [uniqueIndex('communication_idempotency_idx').on(table.idempotencyKey)]);

export const gmailOauthStates = sqliteTable('gmail_oauth_states', {
  id: integer('id').primaryKey({ autoIncrement: true }), stateHash: text('state_hash').notNull(), verifierCiphertext: text('verifier_ciphertext').notNull(), verifierIv: text('verifier_iv').notNull(), keyVersion: text('key_version').notNull(), redirectUri: text('redirect_uri').notNull(), expiresAt: text('expires_at').notNull(), consumedAt: text('consumed_at'), createdBy: text('created_by').notNull(), isSynthetic: integer('is_synthetic', { mode: 'boolean' }).notNull().default(true), createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
}, table => [uniqueIndex('gmail_oauth_state_hash_idx').on(table.stateHash)]);
export const gmailConnections = sqliteTable('gmail_connections', {
  id: integer('id').primaryKey({ autoIncrement: true }), ownerEmail: text('owner_email').notNull(), senderEmail: text('sender_email').notNull(), googleSubjectHash: text('google_subject_hash').notNull(), encryptedTokenBundle: text('encrypted_token_bundle').notNull(), tokenIv: text('token_iv').notNull(), keyVersion: text('key_version').notNull(), grantedScope: text('granted_scope').notNull(), status: text('status', { enum: ['CONNECTED','EXPIRED','REVOKED','ERROR'] }).notNull(), authorizedAt: text('authorized_at').notNull(), tokenExpiresAt: text('token_expires_at').notNull(), disconnectedAt: text('disconnected_at'), safeErrorClassification: text('safe_error_classification'), isSynthetic: integer('is_synthetic', { mode: 'boolean' }).notNull().default(true), ...timestamps,
});
export const gmailDeliveryAttempts = sqliteTable('gmail_delivery_attempts', {
  id: integer('id').primaryKey({ autoIncrement: true }), communicationId: integer('communication_id').notNull().references(() => communicationRecords.id), attemptNumber: integer('attempt_number').notNull(), idempotencyKey: text('idempotency_key').notNull(), stableMessageId: text('stable_message_id').notNull(), state: text('state', { enum: ['SENDING','ACCEPTED_BY_GMAIL','FAILED','UNKNOWN'] }).notNull(), providerMessageId: text('provider_message_id'), safeErrorClassification: text('safe_error_classification'), attemptedAt: text('attempted_at').notNull(), completedAt: text('completed_at'), actor: text('actor').notNull(), isSynthetic: integer('is_synthetic', { mode: 'boolean' }).notNull().default(true), createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
}, table => [uniqueIndex('gmail_delivery_idempotency_idx').on(table.idempotencyKey),uniqueIndex('gmail_delivery_attempt_idx').on(table.communicationId,table.attemptNumber)]);
