import { z } from 'zod';
import { cancellationOutcome, canTransition, externalSources, operationalStatus, reservationStatuses, validateBookingWindow, type ReservationStatus } from '../shared/domain.js';
import { AuthorizationError, authorizeOwner, type AuthEnvironment, type OwnerIdentity, type TokenVerifier } from './auth.js';
import type { DatabasePort, SqlStatement, SqlValue } from './db/port.js';

export type ApiEnvironment = AuthEnvironment & { DB: DatabasePort };
export type ApiDependencies = { verifier?: TokenVerifier; now?: () => Date };
const json = (body: unknown, status = 200) => Response.json(body, { status, headers: { 'cache-control': 'no-store' } });
const iso = (date = new Date()) => date.toISOString();
const conflict = (error: unknown) => error instanceof Error && error.message.includes('TRAILER_SCHEDULE_CONFLICT');
const expectedMessages = ['Reservation not found.','Blackout not found.','Terminal reservations cannot be edited.','This reservation changed since it was opened. Refresh and try again.','A pickup inspection is required before check-out.','A return inspection is required first.','A deliberate deposit decision is required before completion.','Pickup inspection requires a confirmed reservation.','Return inspection requires a checked-out reservation.','Deposit decisions require Inspection Pending status.','A completed return inspection is required.','Damage retain requires amount, reason, and damage notes.','A release record must have a zero retained amount.'];
const failure = (error: unknown) => {
  if (conflict(error)) return json({ error: 'That trailer is already reserved or blocked during this time.' }, 409);
  const message = error instanceof Error ? error.message : '';
  const safe = expectedMessages.includes(message) || /^(Transition from .+ is not permitted\.|Cancellation is not permitted from .+\.|No-show is not permitted from .+\.)$/.test(message) || message === 'Pickup and return must use 30-minute increments.' || message.includes('Arizona time');
  return json({ error: safe ? message : 'The request could not be completed.' }, 400);
};
const audit = (identity: OwnerIdentity, type: string, id: number, action: string, payload: unknown = {}): SqlStatement => ({ sql: 'INSERT INTO audit_events(aggregate_type,aggregate_id,action,actor,payload_json) VALUES (?,?,?,?,?)', params: [type,id,action,identity.email,JSON.stringify(payload)] });
const reservation = (db: DatabasePort, id: number) => db.first('SELECT * FROM reservations WHERE id=?', [id]);

const manualBooking = z.object({ trailerId:z.coerce.number().int().positive(),customerName:z.string().trim().min(2),source:z.enum(externalSources),externalReference:z.string().trim().optional(),pickupAt:z.coerce.date(),returnAt:z.coerce.date(),rentalChargeCents:z.coerce.number().int().nonnegative().default(0),notes:z.string().trim().optional() });
const blackout = z.object({ trailerId:z.coerce.number().int().positive(),startAt:z.coerce.date(),endAt:z.coerce.date(),reason:z.string().trim().min(2),notes:z.string().trim().optional() });
const editReservation = z.object({ version:z.coerce.number().int().positive(),pickupAt:z.coerce.date(),returnAt:z.coerce.date(),notes:z.string().trim().optional(),externalReference:z.string().trim().optional(),rentalChargeCents:z.coerce.number().int().nonnegative(),dollyDays:z.coerce.number().int().nonnegative().default(0),reason:z.string().trim().min(2) });
const localPhotoReference = z.string().trim().min(1).max(120).refine(value=>! /^(?:[a-z][a-z0-9+.-]*:|[\\/]|\.\.?[\\/]|.*[\\/].*)/i.test(value),'URLs and filesystem paths are not accepted. Store a short metadata label only.');
const inspection = z.object({ conditionNotes:z.string().trim().min(2),usageTripNotes:z.string().trim().optional(),damageFound:z.boolean().default(false),damageNotes:z.string().trim().optional(),photoReferences:z.array(localPhotoReference).max(12).default([]) }).superRefine((value,context)=>{if(value.damageFound&&!value.damageNotes)context.addIssue({code:'custom',message:'Damage notes are required when damage is found.'})});
const body = async (request: Request) => { const length=Number(request.headers.get('content-length')||0);if(length>2_000_000)throw new Error('Request body is too large.');return request.json(); };

async function dashboard(db: DatabasePort, now: Date) {
  const rows=await db.all(`SELECT r.*,t.name trailer_name,trim(coalesce(c.first_name,'')||' '||coalesce(c.last_name,'')) customer_name FROM reservations r JOIN trailers t ON t.id=r.trailer_id LEFT JOIN customers c ON c.id=r.customer_id ORDER BY r.pickup_at`);
  return {reservations:rows.map(row=>({...row,operational_status:operationalStatus(row.status as ReservationStatus,new Date(row.pickup_at as string),new Date(row.return_at as string),now)})),blocks:await db.all('SELECT b.*,t.name trailer_name FROM availability_blocks b JOIN trailers t ON t.id=b.trailer_id ORDER BY start_at'),trailers:await db.all('SELECT * FROM trailers WHERE active=1 ORDER BY name')};
}

async function reservationDetail(db: DatabasePort, id: number, now: Date) {
  const row=await db.first(`SELECT r.*,t.name trailer_name,trim(coalesce(c.first_name,'')||' '||coalesce(c.last_name,'')) customer_name FROM reservations r JOIN trailers t ON t.id=r.trailer_id LEFT JOIN customers c ON c.id=r.customer_id WHERE r.id=?`,[id]);
  if(!row)return undefined;
  return {...row,operational_status:operationalStatus(row.status as ReservationStatus,new Date(row.pickup_at as string),new Date(row.return_at as string),now),inspections:await db.all('SELECT * FROM condition_inspections WHERE reservation_id=? ORDER BY inspected_at',[id]),photos:await db.all('SELECT p.* FROM inspection_photos p JOIN condition_inspections i ON i.id=p.inspection_id WHERE i.reservation_id=? ORDER BY p.id',[id]),cancellation_outcome:await db.first('SELECT * FROM cancellation_outcomes WHERE reservation_id=?',[id])||null,deposit_decision:await db.first('SELECT * FROM deposit_decisions WHERE reservation_id=?',[id])||null,audit_events:await db.all("SELECT * FROM audit_events WHERE aggregate_type='RESERVATION' AND aggregate_id=? ORDER BY id DESC",[id])};
}

export async function handleApiRequest(request: Request, environment: ApiEnvironment, dependencies: ApiDependencies = {}): Promise<Response> {
  let identity: OwnerIdentity;
  try { identity=await authorizeOwner(request,environment,dependencies.verifier); } catch(error){if(error instanceof AuthorizationError)return json({error:error.message},error.status);throw error;}
  const db=environment.DB;const url=new URL(request.url);const method=request.method.toUpperCase();const now=dependencies.now?.()||new Date();
  try {
    if(method==='GET'&&url.pathname==='/api/dashboard')return json(await dashboard(db,now));
    let match=url.pathname.match(/^\/api\/reservations\/(\d+)$/);
    if(method==='GET'&&match){const result=await reservationDetail(db,Number(match[1]),now);return result?json(result):json({error:'Reservation not found.'},404);}
    if(method==='POST'&&url.pathname==='/api/reservations/external'){
      const parsed=manualBooking.safeParse(await body(request));if(!parsed.success)return json({error:parsed.error.issues[0]?.message},400);const value=parsed.data;validateBookingWindow(value.pickupAt,value.returnAt);const names=value.customerName.split(/\s+/);const last=names.pop()??'';const first=names.join(' ');const code=`EXT-${crypto.randomUUID().replaceAll('-','').slice(0,12).toUpperCase()}`;
      await db.batch([{sql:'INSERT INTO customers(first_name,last_name) VALUES (?,?)',params:[first||last,first?last:'']},{sql:"INSERT INTO reservations(confirmation_code,trailer_id,customer_id,channel,external_source,external_reference,status,pickup_at,return_at,rental_charge_cents,notes) VALUES (?,?,last_insert_rowid(),'EXTERNAL',?,?,'PENDING_REVIEW',?,?,?,?)",params:[code,value.trailerId,value.source,value.externalReference||null,iso(value.pickupAt),iso(value.returnAt),value.rentalChargeCents,value.notes||null]},{sql:"INSERT INTO audit_events(aggregate_type,aggregate_id,action,actor,payload_json) SELECT 'RESERVATION',id,'EXTERNAL_BOOKING_CREATED',?,? FROM reservations WHERE confirmation_code=?",params:[identity.email,JSON.stringify({source:value.source}),code]}]);
      const created=await db.first('SELECT id FROM reservations WHERE confirmation_code=?',[code]);return json({id:Number(created?.id),confirmationCode:code},201);
    }
    if(method==='PATCH'&&match){const id=Number(match[1]);const parsed=editReservation.safeParse(await body(request));if(!parsed.success)return json({error:parsed.error.issues[0]?.message},400);const value=parsed.data;validateBookingWindow(value.pickupAt,value.returnAt);const before=await reservation(db,id);if(!before)throw new Error('Reservation not found.');if(['COMPLETED','CANCELLED','NO_SHOW'].includes(String(before.status)))throw new Error('Terminal reservations cannot be edited.');const after={...before,pickup_at:iso(value.pickupAt),return_at:iso(value.returnAt),notes:value.notes||null,external_reference:value.externalReference||null,rental_charge_cents:value.rentalChargeCents,dolly_days:value.dollyDays,version:value.version+1};const results=await db.batch([{sql:"UPDATE reservations SET pickup_at=?,return_at=?,notes=?,external_reference=?,rental_charge_cents=?,dolly_days=?,version=version+1,updated_at=datetime('now') WHERE id=? AND version=?",params:[after.pickup_at as string,after.return_at as string,after.notes as SqlValue,after.external_reference as SqlValue,value.rentalChargeCents,value.dollyDays,id,value.version]},{sql:"INSERT INTO audit_events(aggregate_type,aggregate_id,action,actor,payload_json) SELECT 'RESERVATION',?,'RESERVATION_EDITED',?,? WHERE changes()>0",params:[id,identity.email,JSON.stringify({reason:value.reason,before,after})]}]);if(!results[0]?.changes)throw new Error('This reservation changed since it was opened. Refresh and try again.');return json(await reservation(db,id));}

    match=url.pathname.match(/^\/api\/reservations\/(\d+)\/transition$/);
    if(method==='POST'&&match){const id=Number(match[1]);const parsed=z.object({to:z.enum(reservationStatuses),notes:z.string().trim().optional()}).safeParse(await body(request));if(!parsed.success)return json({error:parsed.error.issues[0]?.message},400);const row=await reservation(db,id);if(!row)throw new Error('Reservation not found.');const from=row.status as ReservationStatus;const to=parsed.data.to;if(!canTransition(from,to))throw new Error(`Transition from ${from} to ${to} is not permitted.`);if(to==='CHECKED_OUT'&&!await db.first("SELECT 1 present FROM condition_inspections WHERE reservation_id=? AND type='PICKUP'",[id]))throw new Error('A pickup inspection is required before check-out.');if(to==='INSPECTION_PENDING'&&!await db.first("SELECT 1 present FROM condition_inspections WHERE reservation_id=? AND type='RETURN'",[id]))throw new Error('A return inspection is required first.');if(to==='COMPLETED'&&!await db.first('SELECT 1 present FROM deposit_decisions WHERE reservation_id=?',[id]))throw new Error('A deliberate deposit decision is required before completion.');await db.batch([{sql:"UPDATE reservations SET status=?,version=version+1,updated_at=datetime('now') WHERE id=?",params:[to,id]},audit(identity,'RESERVATION',id,'STATUS_TRANSITIONED',{from,to,notes:parsed.data.notes||null})]);return json(await reservation(db,id));}

    match=url.pathname.match(/^\/api\/reservations\/(\d+)\/outcome$/);
    if(method==='POST'&&match){const id=Number(match[1]);const parsed=z.object({type:z.enum(['CANCELLATION','NO_SHOW']),notes:z.string().trim().min(2)}).safeParse(await body(request));if(!parsed.success)return json({error:parsed.error.issues[0]?.message},400);const row=await reservation(db,id);if(!row)throw new Error('Reservation not found.');const from=row.status as ReservationStatus;const to=parsed.data.type==='NO_SHOW'?'NO_SHOW':'CANCELLED';if(!canTransition(from,to))throw new Error(`${parsed.data.type==='NO_SHOW'?'No-show':'Cancellation'} is not permitted from ${from}.`);const decidedAt=now;const outcome=cancellationOutcome({pickupAt:new Date(row.pickup_at as string),decidedAt,rentalChargeCents:Number(row.rental_charge_cents),noShow:parsed.data.type==='NO_SHOW'});await db.batch([{sql:'INSERT INTO cancellation_outcomes(reservation_id,type,decided_at,notice_hours,rental_refund_cents,retained_cents,notes) VALUES (?,?,?,?,?,?,?)',params:[id,parsed.data.type,iso(decidedAt),Math.floor(outcome.noticeHours),outcome.rentalRefundCents,outcome.retainedCents,parsed.data.notes]},{sql:"UPDATE reservations SET status=?,version=version+1,updated_at=datetime('now') WHERE id=?",params:[to,id]},audit(identity,'RESERVATION',id,'CANCELLATION_OUTCOME_RECORDED',{...outcome,type:parsed.data.type,paymentAction:'NOT_EXECUTED'})]);return json(outcome,201);}

    match=url.pathname.match(/^\/api\/reservations\/(\d+)\/inspections\/(pickup|return)$/i);
    if(method==='POST'&&match){const id=Number(match[1]);const type=match[2].toUpperCase();const parsed=inspection.safeParse(await body(request));if(!parsed.success)return json({error:parsed.error.issues[0]?.message},400);const row=await reservation(db,id);if(!row)throw new Error('Reservation not found.');if(type==='PICKUP'&&row.status!=='CONFIRMED')throw new Error('Pickup inspection requires a confirmed reservation.');if(type==='RETURN'&&row.status!=='CHECKED_OUT')throw new Error('Return inspection requires a checked-out reservation.');const value=parsed.data;const to=type==='PICKUP'?'CHECKED_OUT':'INSPECTION_PENDING';const statements:SqlStatement[]=[{sql:'INSERT INTO condition_inspections(reservation_id,type,condition_notes,usage_trip_notes,damage_found,damage_notes,inspected_at,actor) VALUES (?,?,?,?,?,?,?,?)',params:[id,type,value.conditionNotes,value.usageTripNotes||null,value.damageFound?1:0,value.damageNotes||null,iso(now),identity.email]}];for(const reference of value.photoReferences)statements.push({sql:'INSERT INTO inspection_photos(inspection_id,local_reference,caption) SELECT id,?,? FROM condition_inspections WHERE reservation_id=? AND type=?',params:[reference,'Local metadata only; no hosted attachment',id,type]});statements.push({sql:"UPDATE reservations SET status=?,version=version+1,updated_at=datetime('now') WHERE id=?",params:[to,id]},audit(identity,'RESERVATION',id,`${type}_INSPECTION_RECORDED`,{photoMetadataCount:value.photoReferences.length,hostedPhotoUpload:false,damageFound:value.damageFound,statusTransition:to}));const results=await db.batch(statements);return json({id:results[0]?.lastRowId,status:to,hostedPhotoUpload:false},201);}

    match=url.pathname.match(/^\/api\/reservations\/(\d+)\/deposit-decision$/);
    if(method==='POST'&&match){const id=Number(match[1]);const parsed=z.object({decision:z.enum(['RELEASE_RECORDED','RETAIN_RECORDED']),amountCents:z.coerce.number().int().nonnegative(),reason:z.string().trim().min(2),damageNotes:z.string().trim().optional()}).safeParse(await body(request));if(!parsed.success)return json({error:parsed.error.issues[0]?.message},400);const row=await reservation(db,id);if(!row)throw new Error('Reservation not found.');if(row.status!=='INSPECTION_PENDING')throw new Error('Deposit decisions require Inspection Pending status.');if(!await db.first("SELECT 1 present FROM condition_inspections WHERE reservation_id=? AND type='RETURN'",[id]))throw new Error('A completed return inspection is required.');const value=parsed.data;if(value.decision==='RETAIN_RECORDED'&&(value.amountCents<=0||!value.damageNotes))throw new Error('Damage retain requires amount, reason, and damage notes.');if(value.decision==='RELEASE_RECORDED'&&value.amountCents!==0)throw new Error('A release record must have a zero retained amount.');const results=await db.batch([{sql:'INSERT INTO deposit_decisions(reservation_id,decision,amount_cents,reason,damage_notes,decided_at,actor) VALUES (?,?,?,?,?,?,?)',params:[id,value.decision,value.amountCents,value.reason,value.damageNotes||null,iso(now),identity.email]},audit(identity,'RESERVATION',id,'DEPOSIT_DECISION_RECORDED',{...value,paymentAction:'NOT_EXECUTED'})]);return json({id:results[0]?.lastRowId,paymentAction:'NOT_EXECUTED'},201);}

    if(method==='POST'&&url.pathname==='/api/availability-blocks'){const parsed=blackout.safeParse(await body(request));if(!parsed.success)return json({error:parsed.error.issues[0]?.message},400);const value=parsed.data;validateBookingWindow(value.startAt,value.endAt);const results=await db.batch([{sql:'INSERT INTO availability_blocks(trailer_id,start_at,end_at,reason,notes) VALUES (?,?,?,?,?)',params:[value.trailerId,iso(value.startAt),iso(value.endAt),value.reason,value.notes||null]},{sql:"INSERT INTO audit_events(aggregate_type,aggregate_id,action,actor,payload_json) VALUES ('BLACKOUT',last_insert_rowid(),'BLACKOUT_CREATED',?,?)",params:[identity.email,JSON.stringify({...value,startAt:iso(value.startAt),endAt:iso(value.endAt)})]}]);return json({id:results[0]?.lastRowId},201);}
    match=url.pathname.match(/^\/api\/availability-blocks\/(\d+)$/);
    if(method==='PATCH'&&match){const id=Number(match[1]);const parsed=blackout.safeParse(await body(request));if(!parsed.success)return json({error:parsed.error.issues[0]?.message},400);const value=parsed.data;validateBookingWindow(value.startAt,value.endAt);const before=await db.first('SELECT * FROM availability_blocks WHERE id=?',[id]);if(!before)throw new Error('Blackout not found.');const after={...before,trailer_id:value.trailerId,start_at:iso(value.startAt),end_at:iso(value.endAt),reason:value.reason,notes:value.notes||null};await db.batch([{sql:"UPDATE availability_blocks SET trailer_id=?,start_at=?,end_at=?,reason=?,notes=?,updated_at=datetime('now') WHERE id=?",params:[value.trailerId,after.start_at as string,after.end_at as string,value.reason,value.notes||null,id]},audit(identity,'BLACKOUT',id,'BLACKOUT_EDITED',{before,after})]);return json({id});}
    if(method==='DELETE'&&match){const id=Number(match[1]);const parsed=z.object({confirm:z.literal(true),reason:z.string().trim().min(2)}).safeParse(await body(request));if(!parsed.success)return json({error:'Confirmed deletion and a reason are required.'},400);const before=await db.first('SELECT * FROM availability_blocks WHERE id=?',[id]);if(!before)throw new Error('Blackout not found.');await db.batch([audit(identity,'BLACKOUT',id,'BLACKOUT_DELETED',{before,reason:parsed.data.reason}),{sql:'DELETE FROM availability_blocks WHERE id=?',params:[id]}]);return new Response(null,{status:204});}
    return json({error:'Not found.'},404);
  } catch(error){return failure(error);}
}
