import { calculateBookingQuote, SECURITY_DEPOSIT_CENTS } from '../shared/booking.js';
import type { DatabasePort, SqlStatement } from './db/port.js';

export type TrustedAgreementEvidence={agreementId:number;status:'SIGNED';signedAt:string;templateHash:string};
export type ConversionApproval={qualificationReviewed:true;interstateApproved:boolean;deliveryApproved:boolean;agreement:TrustedAgreementEvidence};
export type ConversionRequest={intentId:number;idempotencyKey:string;actor:string;approval:ConversionApproval;confirmationCode?:string};
export type ConversionResult={intentId:number;reservationId:number;confirmationCode:string;idempotent:boolean;status:'PENDING_REVIEW'};

function fail(message:string):never{throw new Error(message)}
const integer=(value:unknown)=>Number(value);

export async function convertSyntheticBookingIntent(db:DatabasePort,input:ConversionRequest,now=new Date()):Promise<ConversionResult>{
  if(!/^[-A-Za-z0-9_]{8,100}$/.test(input.idempotencyKey))fail('A valid conversion idempotency key is required.');
  const priorByKey=await db.first('SELECT intent_id,reservation_id FROM booking_intent_conversions WHERE idempotency_key=?',[input.idempotencyKey]);
  if(priorByKey&&Number(priorByKey.intent_id)!==input.intentId)fail('The conversion idempotency key belongs to another intent.');
  const existing=priorByKey||await db.first('SELECT intent_id,reservation_id,idempotency_key FROM booking_intent_conversions WHERE intent_id=?',[input.intentId]);
  if(existing){if(String(existing.idempotency_key||input.idempotencyKey)!==input.idempotencyKey)fail('This intent was already converted with a different idempotency key.');const reservation=await db.first('SELECT confirmation_code,status FROM reservations WHERE id=?',[integer(existing.reservation_id)]);if(!reservation)fail('Converted reservation could not be verified.');return{intentId:input.intentId,reservationId:integer(existing.reservation_id),confirmationCode:String(reservation.confirmation_code),idempotent:true,status:'PENDING_REVIEW'}}
  const intent=await db.first('SELECT * FROM booking_intents WHERE id=?',[input.intentId]);if(!intent)fail('Booking intent not found.');
  if(integer(intent.is_synthetic)!==1)fail('Only synthetic staging intents may use the conversion foundation.');
  if(!['SUBMITTED','REVIEW_REQUIRED'].includes(String(intent.status))||Date.parse(String(intent.expires_at))<=now.getTime())fail('The booking intent quote or review window has expired.');
  if(!input.approval.qualificationReviewed||[intent.age_25_confirmed,intent.named_renter_only_towing,intent.hitch_ball_acknowledged,intent.brake_controller_acknowledged,intent.insurance_acknowledged].some(value=>integer(value)!==1))fail('Qualification review is incomplete.');
  if(String(intent.trip_type)==='INTERSTATE'&&(!input.approval.interstateApproved||integer(intent.interstate_approval_required)!==1))fail('Interstate approval is required.');
  if(String(intent.fulfillment_type)==='DELIVERY'&&(!input.approval.deliveryApproved||integer(intent.delivery_approval_required)!==1||String(intent.delivery_quote_status)!=='AVAILABLE'||intent.delivery_charge_cents==null))fail('A valid owner-approved delivery quote is required.');
  if(input.approval.agreement.status!=='SIGNED'||!input.approval.agreement.signedAt||!/^[0-9a-f]{64}$/.test(input.approval.agreement.templateHash))fail('Captured signed-agreement evidence is required.');
  const pickup=new Date(String(intent.pickup_at)),returnAt=new Date(String(intent.return_at));const quote=calculateBookingQuote(pickup,returnAt,integer(intent.dolly_requested)===1);const deliveryFee=intent.delivery_charge_cents==null?0:integer(intent.delivery_charge_cents);const expectedTotal=quote.estimatedDueBeforeDeliveryCents+deliveryFee;
  if(quote.rentalDays!==integer(intent.rental_days)||quote.rentalChargeCents!==integer(intent.rental_charge_cents)||quote.dollyChargeCents!==integer(intent.dolly_charge_cents)||integer(intent.security_deposit_cents)!==SECURITY_DEPOSIT_CENTS||integer(intent.tax_cents)!==0||integer(intent.estimated_due_before_delivery_cents)!==quote.estimatedDueBeforeDeliveryCents||integer(intent.estimated_total_cents)!==expectedTotal)fail('The booking quote must be revalidated before conversion.');
  const unavailable=await db.first("SELECT 1 unavailable FROM reservations WHERE trailer_id=? AND status IN ('PENDING_REVIEW','CONFIRMED','CHECKED_OUT','INSPECTION_PENDING') AND ? < return_at AND ? > pickup_at UNION ALL SELECT 1 FROM availability_blocks WHERE trailer_id=? AND ? < end_at AND ? > start_at LIMIT 1",[integer(intent.trailer_id),String(intent.pickup_at),String(intent.return_at),integer(intent.trailer_id),String(intent.pickup_at),String(intent.return_at)]);if(unavailable)fail('Those dates are no longer available.');
  const names=String(intent.legal_name).trim().split(/\s+/);const last=names.pop()||'';const first=names.join(' ')||last;const code=input.confirmationCode||`SYN-${crypto.randomUUID().replaceAll('-','').slice(0,12).toUpperCase()}`;const convertedAt=now.toISOString();const agreementEvidence=JSON.stringify(input.approval.agreement);const approvals=JSON.stringify({qualificationReviewed:true,interstateApproved:input.approval.interstateApproved,deliveryApproved:input.approval.deliveryApproved,source:'TRUSTED_SERVER_EVIDENCE'});const quoteSnapshot=JSON.stringify({rentalChargeCents:quote.rentalChargeCents,dollyChargeCents:quote.dollyChargeCents,securityDepositCents:SECURITY_DEPOSIT_CENTS,deliveryChargeCents:deliveryFee,taxCents:0,estimatedTotalCents:expectedTotal,paymentAction:'NOT_EXECUTED'});
  const statements:SqlStatement[]=[
    {sql:'INSERT INTO customers(first_name,last_name,email,phone) VALUES (?,?,?,?)',params:[first,last,String(intent.email),String(intent.phone)]},
    {sql:`INSERT INTO reservations(confirmation_code,trailer_id,customer_id,channel,status,pickup_at,return_at,rental_charge_cents,dolly_days,is_synthetic,named_renter_will_tow,interstate_use,interstate_approved,international_use,delivery_requested,delivery_distance_miles,delivery_approved,notes) VALUES (?,?,last_insert_rowid(),'DIRECT','PENDING_REVIEW',?,?,?,?,1,1,?,?,0,?,?,?,'Synthetic conversion foundation; payment, communication, and customer confirmation not executed.')`,params:[code,integer(intent.trailer_id),String(intent.pickup_at),String(intent.return_at),quote.rentalChargeCents,integer(intent.dolly_requested)===1?quote.rentalDays:0,String(intent.trip_type)==='INTERSTATE'?1:0,input.approval.interstateApproved?1:0,String(intent.fulfillment_type)==='DELIVERY'?1:0,intent.delivery_distance_meters==null?null:Math.round(integer(intent.delivery_distance_meters)/1609.344),input.approval.deliveryApproved?1:0]},
    {sql:'INSERT INTO booking_intent_conversions(intent_id,idempotency_key,reservation_id,agreement_evidence_json,approval_snapshot_json,quote_snapshot_json,converted_at,actor,is_synthetic) VALUES (?,?,last_insert_rowid(),?,?,?,?,?,1)',params:[input.intentId,input.idempotencyKey,agreementEvidence,approvals,quoteSnapshot,convertedAt,input.actor]},
    {sql:"UPDATE booking_intents SET status='CONVERTED',updated_at=datetime('now') WHERE id=?",params:[input.intentId]},
    {sql:"INSERT INTO audit_events(aggregate_type,aggregate_id,action,actor,payload_json) VALUES ('BOOKING_INTENT',?,'BOOKING_INTENT_CONVERTED',?,?)",params:[input.intentId,input.actor,JSON.stringify({convertedAt,confirmationCode:code,agreementId:input.approval.agreement.agreementId,availabilityRevalidated:true,quoteRevalidated:true,synthetic:true,paymentAction:'NOT_EXECUTED',communicationAction:'NOT_EXECUTED'})]},
    {sql:"INSERT INTO audit_events(aggregate_type,aggregate_id,action,actor,payload_json) SELECT 'RESERVATION',reservation_id,'RESERVATION_CREATED_FROM_INTENT',?,? FROM booking_intent_conversions WHERE intent_id=?",params:[input.actor,JSON.stringify({intentId:input.intentId,status:'PENDING_REVIEW',synthetic:true,paymentAction:'NOT_EXECUTED'}),input.intentId]},
  ];
  await db.batch(statements);const converted=await db.first('SELECT reservation_id FROM booking_intent_conversions WHERE intent_id=?',[input.intentId]);if(!converted)fail('Conversion did not complete.');return{intentId:input.intentId,reservationId:integer(converted.reservation_id),confirmationCode:code,idempotent:false,status:'PENDING_REVIEW'};
}
