import express from 'express';
import { resolve } from 'node:path';
import { z } from 'zod';
import type Database from 'better-sqlite3';
import { migrate, openDatabase } from './db/database.js';
import { cancellationOutcome, canTransition, externalSources, operationalStatus, reservationStatuses, validateBookingWindow, type ReservationStatus } from '../shared/domain.js';

const db = openDatabase(process.env.DATABASE_URL || resolve('data/rental-os.db')); migrate(db);
const app = express(); app.use(express.json({limit:'2mb'}));
const iso=(date=new Date())=>date.toISOString(); const conflict=(error:unknown)=>error instanceof Error&&error.message.includes('TRAILER_SCHEDULE_CONFLICT');
const fail=(res:express.Response,error:unknown)=>res.status(conflict(error)?409:400).json({error:conflict(error)?'That trailer is already reserved or blocked during this time.':(error as Error).message});
const audit=(database:Database.Database,type:string,id:number,action:string,payload:unknown={})=>database.prepare('INSERT INTO audit_events(aggregate_type,aggregate_id,action,payload_json) VALUES (?,?,?,?)').run(type,id,action,JSON.stringify(payload));
const reservation=(id:number)=>db.prepare('SELECT * FROM reservations WHERE id=?').get(id) as Record<string,unknown>|undefined;

const manualBooking=z.object({trailerId:z.coerce.number().int().positive(),customerName:z.string().trim().min(2),source:z.enum(externalSources),externalReference:z.string().trim().optional(),pickupAt:z.coerce.date(),returnAt:z.coerce.date(),rentalChargeCents:z.coerce.number().int().nonnegative().default(0),notes:z.string().trim().optional()});
const blackout=z.object({trailerId:z.coerce.number().int().positive(),startAt:z.coerce.date(),endAt:z.coerce.date(),reason:z.string().trim().min(2),notes:z.string().trim().optional()});
const editReservation=z.object({version:z.coerce.number().int().positive(),pickupAt:z.coerce.date(),returnAt:z.coerce.date(),notes:z.string().trim().optional(),externalReference:z.string().trim().optional(),rentalChargeCents:z.coerce.number().int().nonnegative(),dollyDays:z.coerce.number().int().nonnegative().default(0),reason:z.string().trim().min(2)});
const inspection=z.object({conditionNotes:z.string().trim().min(2),usageTripNotes:z.string().trim().optional(),damageFound:z.boolean().default(false),damageNotes:z.string().trim().optional(),photoReferences:z.array(z.string().trim().min(1)).max(12).default([])}).superRefine((v,ctx)=>{if(v.damageFound&&!v.damageNotes)ctx.addIssue({code:'custom',message:'Damage notes are required when damage is found.'})});

app.get('/api/dashboard',(_req,res)=>{
 const rows=db.prepare(`SELECT r.*,t.name trailer_name,trim(coalesce(c.first_name,'')||' '||coalesce(c.last_name,'')) customer_name FROM reservations r JOIN trailers t ON t.id=r.trailer_id LEFT JOIN customers c ON c.id=r.customer_id ORDER BY r.pickup_at`).all() as Array<Record<string,unknown>>;
 const reservations=rows.map(r=>({...r,operational_status:operationalStatus(r.status as ReservationStatus,new Date(r.pickup_at as string),new Date(r.return_at as string))}));
 res.json({reservations,blocks:db.prepare('SELECT b.*,t.name trailer_name FROM availability_blocks b JOIN trailers t ON t.id=b.trailer_id ORDER BY start_at').all(),trailers:db.prepare('SELECT * FROM trailers WHERE active=1 ORDER BY name').all()});
});
app.get('/api/reservations/:id',(req,res)=>{const id=Number(req.params.id);const row=db.prepare(`SELECT r.*,t.name trailer_name,trim(coalesce(c.first_name,'')||' '||coalesce(c.last_name,'')) customer_name FROM reservations r JOIN trailers t ON t.id=r.trailer_id LEFT JOIN customers c ON c.id=r.customer_id WHERE r.id=?`).get(id) as Record<string,unknown>|undefined;if(!row)return res.status(404).json({error:'Reservation not found.'});res.json({...row,operational_status:operationalStatus(row.status as ReservationStatus,new Date(row.pickup_at as string),new Date(row.return_at as string)),inspections:db.prepare('SELECT * FROM condition_inspections WHERE reservation_id=? ORDER BY inspected_at').all(id),photos:db.prepare('SELECT p.* FROM inspection_photos p JOIN condition_inspections i ON i.id=p.inspection_id WHERE i.reservation_id=? ORDER BY p.id').all(id),cancellation_outcome:db.prepare('SELECT * FROM cancellation_outcomes WHERE reservation_id=?').get(id)||null,deposit_decision:db.prepare('SELECT * FROM deposit_decisions WHERE reservation_id=?').get(id)||null,audit_events:db.prepare("SELECT * FROM audit_events WHERE aggregate_type='RESERVATION' AND aggregate_id=? ORDER BY id DESC").all(id)});});

app.post('/api/reservations/external',(req,res)=>{const parsed=manualBooking.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:parsed.error.issues[0]?.message});const v=parsed.data;try{validateBookingWindow(v.pickupAt,v.returnAt);const result=db.transaction(()=>{const parts=v.customerName.split(/\s+/);const last=parts.pop()??'';const first=parts.join(' ');const customer=db.prepare('INSERT INTO customers(first_name,last_name) VALUES (?,?)').run(first||last,first?last:'');const code=`EXT-${Date.now().toString(36).toUpperCase()}`;const inserted=db.prepare("INSERT INTO reservations(confirmation_code,trailer_id,customer_id,channel,external_source,external_reference,status,pickup_at,return_at,rental_charge_cents,notes) VALUES (?,?,?,'EXTERNAL',?,?,'PENDING_REVIEW',?,?,?,?)").run(code,v.trailerId,customer.lastInsertRowid,v.source,v.externalReference||null,iso(v.pickupAt),iso(v.returnAt),v.rentalChargeCents,v.notes||null);audit(db,'RESERVATION',Number(inserted.lastInsertRowid),'EXTERNAL_BOOKING_CREATED',{source:v.source});return{id:Number(inserted.lastInsertRowid),confirmationCode:code}})();return res.status(201).json(result)}catch(error){return fail(res,error)}});

app.patch('/api/reservations/:id',(req,res)=>{const id=Number(req.params.id);const parsed=editReservation.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:parsed.error.issues[0]?.message});const v=parsed.data;try{validateBookingWindow(v.pickupAt,v.returnAt);const result=db.transaction(()=>{const before=reservation(id);if(!before)throw new Error('Reservation not found.');if(['COMPLETED','CANCELLED','NO_SHOW'].includes(String(before.status)))throw new Error('Terminal reservations cannot be edited.');const updated=db.prepare("UPDATE reservations SET pickup_at=?,return_at=?,notes=?,external_reference=?,rental_charge_cents=?,dolly_days=?,version=version+1,updated_at=datetime('now') WHERE id=? AND version=?").run(iso(v.pickupAt),iso(v.returnAt),v.notes||null,v.externalReference||null,v.rentalChargeCents,v.dollyDays,id,v.version);if(!updated.changes)throw new Error('This reservation changed since it was opened. Refresh and try again.');audit(db,'RESERVATION',id,'RESERVATION_EDITED',{reason:v.reason,before,after:reservation(id)});return reservation(id)})();return res.json(result)}catch(error){return fail(res,error)}});

app.post('/api/reservations/:id/transition',(req,res)=>{const id=Number(req.params.id);const parsed=z.object({to:z.enum(reservationStatuses),notes:z.string().trim().optional()}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:parsed.error.issues[0]?.message});try{const result=db.transaction(()=>{const row=reservation(id);if(!row)throw new Error('Reservation not found.');const from=row.status as ReservationStatus;const to=parsed.data.to;if(!canTransition(from,to))throw new Error(`Transition from ${from} to ${to} is not permitted.`);if(to==='CHECKED_OUT'&&!db.prepare("SELECT 1 FROM condition_inspections WHERE reservation_id=? AND type='PICKUP'").get(id))throw new Error('A pickup inspection is required before check-out.');if(to==='INSPECTION_PENDING'&&!db.prepare("SELECT 1 FROM condition_inspections WHERE reservation_id=? AND type='RETURN'").get(id))throw new Error('A return inspection is required first.');if(to==='COMPLETED'&&!db.prepare('SELECT 1 FROM deposit_decisions WHERE reservation_id=?').get(id))throw new Error('A deliberate deposit decision is required before completion.');db.prepare("UPDATE reservations SET status=?,version=version+1,updated_at=datetime('now') WHERE id=?").run(to,id);audit(db,'RESERVATION',id,'STATUS_TRANSITIONED',{from,to,notes:parsed.data.notes||null});return reservation(id)})();return res.json(result)}catch(error){return fail(res,error)}});

app.post('/api/reservations/:id/outcome',(req,res)=>{const id=Number(req.params.id);const parsed=z.object({type:z.enum(['CANCELLATION','NO_SHOW']),notes:z.string().trim().min(2)}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:parsed.error.issues[0]?.message});try{const result=db.transaction(()=>{const row=reservation(id);if(!row)throw new Error('Reservation not found.');const from=row.status as ReservationStatus;const to=parsed.data.type==='NO_SHOW'?'NO_SHOW':'CANCELLED';if(!canTransition(from,to))throw new Error(`${parsed.data.type==='NO_SHOW'?'No-show':'Cancellation'} is not permitted from ${from}.`);const decidedAt=new Date();const outcome=cancellationOutcome({pickupAt:new Date(row.pickup_at as string),decidedAt,rentalChargeCents:Number(row.rental_charge_cents),noShow:parsed.data.type==='NO_SHOW'});db.prepare('INSERT INTO cancellation_outcomes(reservation_id,type,decided_at,notice_hours,rental_refund_cents,retained_cents,notes) VALUES (?,?,?,?,?,?,?)').run(id,parsed.data.type,iso(decidedAt),Math.floor(outcome.noticeHours),outcome.rentalRefundCents,outcome.retainedCents,parsed.data.notes);db.prepare("UPDATE reservations SET status=?,version=version+1,updated_at=datetime('now') WHERE id=?").run(to,id);audit(db,'RESERVATION',id,'CANCELLATION_OUTCOME_RECORDED',{...outcome,type:parsed.data.type,paymentAction:'NOT_EXECUTED'});return outcome})();return res.status(201).json(result)}catch(error){return fail(res,error)}});

app.post('/api/reservations/:id/inspections/:type',(req,res)=>{const id=Number(req.params.id);const type=String(req.params.type).toUpperCase();if(!['PICKUP','RETURN'].includes(type))return res.status(400).json({error:'Inspection type must be pickup or return.'});const parsed=inspection.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:parsed.error.issues[0]?.message});try{const result=db.transaction(()=>{const row=reservation(id);if(!row)throw new Error('Reservation not found.');if(type==='PICKUP'&&row.status!=='CONFIRMED')throw new Error('Pickup inspection requires a confirmed reservation.');if(type==='RETURN'&&row.status!=='CHECKED_OUT')throw new Error('Return inspection requires a checked-out reservation.');const v=parsed.data;const inserted=db.prepare('INSERT INTO condition_inspections(reservation_id,type,condition_notes,usage_trip_notes,damage_found,damage_notes,inspected_at) VALUES (?,?,?,?,?,?,?)').run(id,type,v.conditionNotes,v.usageTripNotes||null,v.damageFound?1:0,v.damageNotes||null,iso());for(const ref of v.photoReferences)db.prepare('INSERT INTO inspection_photos(inspection_id,local_reference) VALUES (?,?)').run(inserted.lastInsertRowid,ref);const to=type==='PICKUP'?'CHECKED_OUT':'INSPECTION_PENDING';db.prepare("UPDATE reservations SET status=?,version=version+1,updated_at=datetime('now') WHERE id=?").run(to,id);audit(db,'RESERVATION',id,`${type}_INSPECTION_RECORDED`,{inspectionId:Number(inserted.lastInsertRowid),photoCount:v.photoReferences.length,damageFound:v.damageFound,statusTransition:to});return{id:Number(inserted.lastInsertRowid),status:to}})();return res.status(201).json(result)}catch(error){return fail(res,error)}});

app.post('/api/reservations/:id/deposit-decision',(req,res)=>{const id=Number(req.params.id);const parsed=z.object({decision:z.enum(['RELEASE_RECORDED','RETAIN_RECORDED']),amountCents:z.coerce.number().int().nonnegative(),reason:z.string().trim().min(2),damageNotes:z.string().trim().optional()}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:parsed.error.issues[0]?.message});try{const result=db.transaction(()=>{const row=reservation(id);if(!row)throw new Error('Reservation not found.');if(row.status!=='INSPECTION_PENDING')throw new Error('Deposit decisions require Inspection Pending status.');if(!db.prepare("SELECT 1 FROM condition_inspections WHERE reservation_id=? AND type='RETURN'").get(id))throw new Error('A completed return inspection is required.');const v=parsed.data;if(v.decision==='RETAIN_RECORDED'&&(v.amountCents<=0||!v.damageNotes))throw new Error('Damage retain requires amount, reason, and damage notes.');if(v.decision==='RELEASE_RECORDED'&&v.amountCents!==0)throw new Error('A release record must have a zero retained amount.');const inserted=db.prepare('INSERT INTO deposit_decisions(reservation_id,decision,amount_cents,reason,damage_notes,decided_at) VALUES (?,?,?,?,?,?)').run(id,v.decision,v.amountCents,v.reason,v.damageNotes||null,iso());audit(db,'RESERVATION',id,'DEPOSIT_DECISION_RECORDED',{...v,paymentAction:'NOT_EXECUTED'});return{id:Number(inserted.lastInsertRowid),paymentAction:'NOT_EXECUTED'}})();return res.status(201).json(result)}catch(error){return fail(res,error)}});

app.post('/api/availability-blocks',(req,res)=>{const parsed=blackout.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:parsed.error.issues[0]?.message});const v=parsed.data;try{validateBookingWindow(v.startAt,v.endAt);const result=db.transaction(()=>{const inserted=db.prepare('INSERT INTO availability_blocks(trailer_id,start_at,end_at,reason,notes) VALUES (?,?,?,?,?)').run(v.trailerId,iso(v.startAt),iso(v.endAt),v.reason,v.notes||null);audit(db,'BLACKOUT',Number(inserted.lastInsertRowid),'BLACKOUT_CREATED',v);return{id:Number(inserted.lastInsertRowid)}})();return res.status(201).json(result)}catch(error){return fail(res,error)}});
app.patch('/api/availability-blocks/:id',(req,res)=>{const id=Number(req.params.id);const parsed=blackout.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:parsed.error.issues[0]?.message});const v=parsed.data;try{validateBookingWindow(v.startAt,v.endAt);const result=db.transaction(()=>{const before=db.prepare('SELECT * FROM availability_blocks WHERE id=?').get(id);if(!before)throw new Error('Blackout not found.');db.prepare("UPDATE availability_blocks SET trailer_id=?,start_at=?,end_at=?,reason=?,notes=?,updated_at=datetime('now') WHERE id=?").run(v.trailerId,iso(v.startAt),iso(v.endAt),v.reason,v.notes||null,id);audit(db,'BLACKOUT',id,'BLACKOUT_EDITED',{before,after:db.prepare('SELECT * FROM availability_blocks WHERE id=?').get(id)});return{id}})();return res.json(result)}catch(error){return fail(res,error)}});
app.delete('/api/availability-blocks/:id',(req,res)=>{const id=Number(req.params.id);const parsed=z.object({confirm:z.literal(true),reason:z.string().trim().min(2)}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'Confirmed deletion and a reason are required.'});try{db.transaction(()=>{const before=db.prepare('SELECT * FROM availability_blocks WHERE id=?').get(id);if(!before)throw new Error('Blackout not found.');audit(db,'BLACKOUT',id,'BLACKOUT_DELETED',{before,reason:parsed.data.reason});db.prepare('DELETE FROM availability_blocks WHERE id=?').run(id)})();return res.status(204).end()}catch(error){return fail(res,error)}});

if(process.env.NODE_ENV==='production'){app.use(express.static(resolve('dist')));app.get('*splat',(_req,res)=>res.sendFile(resolve('dist/index.html')))}
const port=Number(process.env.PORT||4174);app.listen(port,'127.0.0.1',()=>console.log(`Rental OS local server: http://127.0.0.1:${port}`));
