import {agreementClausesFromMarkdown,renderCanonicalAgreementVariables} from './agreement.js';

export const AGREEMENT_PDF_RENDERER_VERSION='agreement-pdf-v1';
const cp1252:Record<string,number>={'€':128,'‚':130,'ƒ':131,'„':132,'…':133,'†':134,'‡':135,'ˆ':136,'‰':137,'Š':138,'‹':139,'Œ':140,'Ž':142,'‘':145,'’':146,'“':147,'”':148,'•':149,'–':150,'—':151,'˜':152,'™':153,'š':154,'›':155,'œ':156,'ž':158,'Ÿ':159};
const pdfString=(value:string)=>{let out='';for(const char of value){const code=cp1252[char]??char.charCodeAt(0);if(char==='('||char===')'||char==='\\')out+=`\\${char}`;else if(code<32||code>126)out+=`\\${code.toString(8).padStart(3,'0')}`;else out+=char}return out};
const clean=(value:unknown)=>String(value??'').replace(/\*\*|`/g,'').replace(/\s+/g,' ').trim();
const wrap=(text:string,width=94)=>{const words=clean(text).split(' ');const lines:string[]=[];let line='';for(const word of words){if(!word)continue;if((line+' '+word).trim().length>width&&line){lines.push(line);line=word}else line=(line+' '+word).trim()}if(line)lines.push(line);return lines};
const parse=(value:unknown):Record<string,unknown>=>{try{return JSON.parse(String(value||'{}'))}catch{return{}}};
const field=(label:string,value:unknown)=>wrap(`${label}: ${value??'Not recorded'}`).map(text=>({text}));
export type PdfInput={agreement:Record<string,unknown>;template:Record<string,unknown>;pickupCondition:Record<string,unknown>|null};
export function renderAgreementPdf(input:PdfInput){
 const a=input.agreement,legal=parse(input.template.content_json),renter=parse(a.renter_snapshot_json),reservation=parse(a.reservation_snapshot_json),quote=parse(a.quote_snapshot_json),evidence=parse(a.signature_evidence_json);const sourceMarkdown=String(legal.canonicalMarkdown||'');const markdown=renderCanonicalAgreementVariables(sourceMarkdown,{renterName:renter.legalName||renter.name,renterEmail:renter.email,renterPhone:renter.phone,agreementVersion:a.template_version,bookingId:reservation.confirmationCode||reservation.bookingId||reservation.reservationId,signature:'Drawn signature recorded in the executed-signature evidence below',signedAt:a.signed_at});
 if(!sourceMarkdown||String(a.template_version)!==String(legal.sourceVersion))throw new Error('CANONICAL_AGREEMENT_SOURCE_MISMATCH');
 const lines:{text:string;bold?:boolean;gap?:number}[]=[{text:'TRAILER BROS LLC RENTAL AGREEMENT',bold:true,gap:8},{text:`Agreement version: ${a.template_version}`},{text:`Source hash: ${a.template_hash}`},{text:'Owner draft - attorney review pending',bold:true,gap:8},{text:'BOOKING SUMMARY',bold:true,gap:4},...field('Renter',renter.legalName||renter.name),...field('Email',renter.email),...field('Phone',renter.phone),...field('Authorized drivers',renter.authorizedDrivers||renter.legalName||renter.name),...field('Equipment',reservation.equipmentDescription||reservation.trailerName),...field('Equipment identifier',reservation.unitCode||reservation.equipmentIdentifier||reservation.trailerId),...field('Rental start',reservation.pickupAt),...field('Rental return',reservation.returnAt),...field('Fulfillment',reservation.fulfillment||reservation.fulfillmentType),...field('Delivery address',reservation.deliveryAddress),...field('Raw one-way road miles',quote.rawRoadMiles),...field('Rounded billable miles',quote.billableMiles),...field('Delivery rate',quote.deliveryChargeCents?'$2.50 per one-way road mile':'Not applicable'),...field('Base rent cents',quote.rentalChargeCents||quote.rentalCents),...field('Dolly/add-ons cents',quote.dollyChargeCents||quote.dollyCents),...field('Delivery cents',quote.deliveryChargeCents||quote.deliveryCents),...field('Tax cents',quote.taxCents),...field('Security deposit cents',quote.securityDepositCents||quote.depositCents),...field('Total cents',quote.totalCents||quote.estimatedTotalCents),{text:'AGREEMENT TERMS',bold:true,gap:6}];
 for(const clause of agreementClausesFromMarkdown(markdown)){lines.push({text:clause.heading,bold:true,gap:3});for(const p of clause.paragraphs)for(const line of wrap(p))lines.push({text:line});for(const b of clause.bullets)for(const [i,line] of wrap(b,90).entries())lines.push({text:`${i?'  ':'- '}${line}`});lines.push({text:'',gap:3})}
 lines.push({text:'ELECTRONIC ACCEPTANCE AND SIGNATURE EVIDENCE',bold:true,gap:4},...field('Printed legal name',a.printed_name),...field('Signed at',a.signed_at),...field('Electronic consent at',a.electronic_consent_at),...field('Required acknowledgments at',a.terms_acknowledged_at),...field('Pickup-condition choice',a.pickup_inspection_choice),...field('Signature evidence hash',(evidence.signature as Record<string,unknown>|undefined)?.hash||evidence.hash||'Recorded'));
 const pages:{content:string}[]=[];let ops:string[]=[];let y=748;const finish=()=>{if(ops.length){pages.push({content:ops.join('\n')});ops=[];y=748}};for(const line of lines){const gap=line.gap||0;if(y-gap<54)finish();y-=gap;if(!line.text){y-=5;continue}if(y<54)finish();ops.push(`BT /${line.bold?'F2':'F1'} ${line.bold?'11':'9.2'} Tf 54 ${y} Td (${pdfString(line.text)}) Tj ET`);y-=line.bold?15:12}
 const points=(evidence.signature as {points?:unknown} | undefined)?.points;if(Array.isArray(points)&&points.length>=3){if(y<190)finish();else y-=18;ops.push(`BT /F2 15 Tf 54 ${y} Td (EXECUTED SIGNATURE EVIDENCE) Tj ET`);y-=24;for(const summary of [`Agreement: ${a.template_version}`,`Renter: ${a.printed_name}`,`Signed at: ${a.signed_at}`,`Pickup-condition choice: ${a.pickup_inspection_choice}`]){ops.push(`BT /F1 10 Tf 54 ${y} Td (${pdfString(summary)}) Tj ET`);y-=15}y-=16;ops.push(`BT /F2 10 Tf 54 ${y} Td (Drawn signature) Tj ET`);y-=92;let pen=false;for(const point of points){if(!Array.isArray(point)||point.length<2){pen=false;continue}const x=60+Math.max(0,Math.min(1,Number(point[0])))*460;const py=y+20+Math.max(0,Math.min(1,1-Number(point[1])))*65;ops.push(`${x.toFixed(2)} ${py.toFixed(2)} ${pen?'l':'m'}`);pen=true}ops.push('S');y-=12}finish();
 const objects:string[]=[];const add=(body:string)=>{objects.push(body);return objects.length};const font1=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>');const font2=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>');const pageRefs:number[]=[];const contentRefs:number[]=[];for(const page of pages)contentRefs.push(add(`<< /Length ${page.content.length} >>\nstream\n${page.content}\nendstream`));const pagesRef=objects.length+pages.length+1;for(let i=0;i<pages.length;i++)pageRefs.push(add(`<< /Type /Page /Parent ${pagesRef} 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 ${font1} 0 R /F2 ${font2} 0 R >> >> /Contents ${contentRefs[i]} 0 R >>`));add(`<< /Type /Pages /Kids [${pageRefs.map(ref=>`${ref} 0 R`).join(' ')}] /Count ${pageRefs.length} >>`);const catalog=add(`<< /Type /Catalog /Pages ${pagesRef} 0 R >>`);let pdf='%PDF-1.4\n%\xE2\xE3\xCF\xD3\n';const offsets=[0];objects.forEach((object,index)=>{offsets.push(pdf.length);pdf+=`${index+1} 0 obj\n${object}\nendobj\n`});const xref=pdf.length;pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(offset=>`${String(offset).padStart(10,'0')} 00000 n `).join('\n')}\ntrailer\n<< /Size ${objects.length+1} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`;
 return {bytes:Uint8Array.from(pdf,character=>character.charCodeAt(0)&255),pageCount:pages.length};
}
export function bytesToBase64(bytes:Uint8Array){let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary)}
export function base64ToBytes(value:string){const binary=atob(value);return Uint8Array.from(binary,character=>character.charCodeAt(0))}
export async function agreementPdfHash(bytes:Uint8Array){const digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(value=>value.toString(16).padStart(2,'0')).join('')}
