export const AGREEMENT_RENDERER_VERSION='agreement-print-html-v1';

const esc=(value:unknown)=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));
const stable=(value:unknown):string=>value&&typeof value==='object'&&!Array.isArray(value)?`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${JSON.stringify(key)}:${stable(item)}`).join(',')}}`:Array.isArray(value)?`[${value.map(stable).join(',')}]`:JSON.stringify(value);

export type AgreementRenderInput={agreement:Record<string,unknown>;template:Record<string,unknown>;pickupCondition:Record<string,unknown>|null};
export function renderAgreementDocument(input:AgreementRenderInput){
  const a=input.agreement; const legal=JSON.parse(String(input.template.content_json||'{}')); const renter=JSON.parse(String(a.renter_snapshot_json||'{}')); const reservation=JSON.parse(String(a.reservation_snapshot_json||'{}')); const quote=JSON.parse(String(a.quote_snapshot_json||'{}')); const signature=JSON.parse(String(a.signature_evidence_json||'{}'));
  const model={rendererVersion:AGREEMENT_RENDERER_VERSION,templateVersion:a.template_version,templateHash:a.template_hash,legalReviewStatus:input.template.legal_review_status,renter,reservation,quote,acknowledgments:{electronicConsentAt:a.electronic_consent_at,termsAcknowledgedAt:a.terms_acknowledged_at,driverInsuranceAcknowledgedAt:a.driver_insurance_acknowledged_at,inspectionOpportunityAcknowledgedAt:a.inspection_opportunity_acknowledged_at},signature:{signedAt:a.signed_at,printedName:a.printed_name,evidence:signature},pickupCondition:input.pickupCondition,legal};
  const html=`<!doctype html><html><head><meta charset="utf-8"><title>Trailer Bros Rental Agreement</title><style>body{font:14px/1.5 system-ui;max-width:800px;margin:40px auto;color:#111}h1,h2{margin:.5em 0}section{break-inside:avoid;border-top:1px solid #ccc;padding:12px 0}pre{white-space:pre-wrap}.flag{font-weight:700;color:#8a3b00}</style></head><body><h1>Trailer Bros Rental Agreement</h1><p class="flag">${esc(input.template.legal_review_status)}</p><section><h2>Reservation</h2><pre>${esc(stable(reservation))}</pre></section><section><h2>Renter</h2><pre>${esc(stable(renter))}</pre></section><section><h2>Quote snapshot</h2><pre>${esc(stable(quote))}</pre></section><section><h2>Terms and acknowledgments</h2><pre>${esc(stable({legal,acknowledgments:model.acknowledgments,pickupCondition:input.pickupCondition}))}</pre></section><section><h2>Signature evidence</h2><pre>${esc(stable(model.signature))}</pre></section><footer>Renderer ${esc(AGREEMENT_RENDERER_VERSION)} · Template ${esc(a.template_version)}</footer></body></html>`;
  return {html,model};
}
export async function agreementDocumentHash(content:string){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(content));return [...new Uint8Array(bytes)].map(value=>value.toString(16).padStart(2,'0')).join('');}
