import { arizonaDayKey, parseArizonaDateTime } from './arizonaTime.js';

export const bookedStatuses = ['PENDING_REVIEW','CONFIRMED','CHECKED_OUT','INSPECTION_PENDING','COMPLETED'] as const;
export const confirmedRevenueStatuses = ['CONFIRMED','CHECKED_OUT','INSPECTION_PENDING','COMPLETED'] as const;
const sourceNames:Record<string,string>={DIRECT:'Direct',BIG_RENTALS:'Big Rentals',NEIGHBORS_TRAILER:'Neighbors Trailer',FACEBOOK_MARKETPLACE:'Facebook Marketplace',OTHER:'Other'};
const weekdays=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];

export type AnalyticsReservation={id:number;trailer_id:number;status:string;pickup_at:string;return_at:string;rental_charge_cents:number;channel:string;external_source?:string|null;delivery_requested:number;dolly_days:number;is_synthetic:number};
export type AnalyticsBlock={id:number;trailer_id:number;start_at:string;end_at:string;is_synthetic:number};
export type AnalyticsRange={startDate:string;endDate:string;startAt:string;endAtExclusive:string;days:number};
export type AnalyticsSummary={reservationRequests:number;activeCompletedRentals:number;bookedRevenueCents:number;confirmedRevenueCents:number;cancellations:number;noShows:number;averageRentalHours:number|null;occupiedHours:number;capacityHours:number;utilizationRate:number|null;deliveryCount:number;deliveryRate:number|null;dollyCount:number;dollyRate:number|null};
export type TrendPoint={key:string;bookingCount:number;bookedRevenueCents:number};
export type SourcePoint={source:string;bookingCount:number;bookedRevenueCents:number;cancelledOrNoShow:number};
export type Insight={id:string;title:string;detail:string;threshold:string;tone:'neutral'|'positive'|'warning'};
export type AnalyticsReport={range:AnalyticsRange;comparisonRange:AnalyticsRange;includeSynthetic:boolean;current:AnalyticsSummary;previous:AnalyticsSummary;weeklyTrend:TrendPoint[];monthlyTrend:TrendPoint[];dayOfWeek:{day:string;bookingCount:number}[];sources:SourcePoint[];upcomingAvailability:{startDate:string;endDate:string;horizonDays:number;availableHours:number;fullyOpenTrailerDays:number};insights:Insight[];unavailableFinancialMetrics:string[]};

export function addArizonaDays(day:string,amount:number){const [year,month,date]=day.split('-').map(Number);const value=new Date(Date.UTC(year,month-1,date+amount));return`${value.getUTCFullYear()}-${String(value.getUTCMonth()+1).padStart(2,'0')}-${String(value.getUTCDate()).padStart(2,'0')}`}
const isCalendarDay=(day:string)=>/^\d{4}-\d{2}-\d{2}$/.test(day)&&addArizonaDays(day,0)===day;
export function analyticsRange(startDate:string,endDate:string):AnalyticsRange{if(!isCalendarDay(startDate)||!isCalendarDay(endDate))throw new Error('Analytics dates must be valid calendar dates.');const startAt=parseArizonaDateTime(`${startDate}T00:00`).toISOString();const endAtExclusive=parseArizonaDateTime(`${addArizonaDays(endDate,1)}T00:00`).toISOString();const days=Math.round((Date.parse(endAtExclusive)-Date.parse(startAt))/86_400_000);if(days<1)throw new Error('Analytics end date must be on or after the start date.');if(days>731)throw new Error('Analytics ranges cannot exceed 731 days.');return{startDate,endDate,startAt,endAtExclusive,days}}
export function defaultAnalyticsRange(now:Date){const endDate=arizonaDayKey(now);return analyticsRange(addArizonaDays(endDate,-89),endDate)}
export function comparisonRange(range:AnalyticsRange){const endDate=addArizonaDays(range.startDate,-1);return analyticsRange(addArizonaDays(endDate,1-range.days),endDate)}

const round=(value:number,digits=1)=>Number(value.toFixed(digits));
const overlapHours=(start:string,end:string,windowStart:string,windowEnd:string)=>Math.max(0,(Math.min(Date.parse(end),Date.parse(windowEnd))-Math.max(Date.parse(start),Date.parse(windowStart)))/3_600_000);
const inPickupRange=(reservation:AnalyticsReservation,range:AnalyticsRange)=>Date.parse(reservation.pickup_at)>=Date.parse(range.startAt)&&Date.parse(reservation.pickup_at)<Date.parse(range.endAtExclusive);
const isBooked=(reservation:AnalyticsReservation)=>bookedStatuses.includes(reservation.status as typeof bookedStatuses[number]);
const sourceOf=(reservation:AnalyticsReservation)=>sourceNames[reservation.channel==='DIRECT'?'DIRECT':reservation.external_source||'OTHER']||'Other';
const weekKey=(day:string)=>{const [y,m,d]=day.split('-').map(Number);const date=new Date(Date.UTC(y,m-1,d));const mondayOffset=(date.getUTCDay()+6)%7;return addArizonaDays(day,-mondayOffset)};

function operatingTotals(reservations:AnalyticsReservation[],blocks:AnalyticsBlock[],trailerIds:number[],range:AnalyticsRange){let capacityHours=0,occupiedHours=0,fullyOpenTrailerDays=0;for(let offset=0;offset<range.days;offset++){const day=addArizonaDays(range.startDate,offset);const open=parseArizonaDateTime(`${day}T06:00`).toISOString();const close=parseArizonaDateTime(`${day}T22:00`).toISOString();for(const trailerId of trailerIds){const blocked=blocks.filter(block=>block.trailer_id===trailerId).reduce((sum,block)=>sum+overlapHours(block.start_at,block.end_at,open,close),0);const occupied=reservations.filter(reservation=>reservation.trailer_id===trailerId&&isBooked(reservation)).reduce((sum,reservation)=>sum+overlapHours(reservation.pickup_at,reservation.return_at,open,close),0);capacityHours+=Math.max(0,16-blocked);occupiedHours+=occupied;if(blocked===0&&occupied===0)fullyOpenTrailerDays++}}return{capacityHours:round(capacityHours),occupiedHours:round(occupiedHours),fullyOpenTrailerDays}}

function summary(reservations:AnalyticsReservation[],blocks:AnalyticsBlock[],trailerIds:number[],range:AnalyticsRange):AnalyticsSummary{const pickups=reservations.filter(reservation=>inPickupRange(reservation,range));const booked=pickups.filter(isBooked);const activeCompleted=pickups.filter(reservation=>confirmedRevenueStatuses.includes(reservation.status as typeof confirmedRevenueStatuses[number]));const operating=operatingTotals(reservations,blocks,trailerIds,range);const totalDuration=booked.reduce((sum,reservation)=>sum+(Date.parse(reservation.return_at)-Date.parse(reservation.pickup_at))/3_600_000,0);const deliveryCount=booked.filter(reservation=>Boolean(reservation.delivery_requested)).length;const dollyCount=booked.filter(reservation=>reservation.dolly_days>0).length;return{reservationRequests:pickups.length,activeCompletedRentals:activeCompleted.length,bookedRevenueCents:booked.reduce((sum,reservation)=>sum+Number(reservation.rental_charge_cents),0),confirmedRevenueCents:activeCompleted.reduce((sum,reservation)=>sum+Number(reservation.rental_charge_cents),0),cancellations:pickups.filter(reservation=>reservation.status==='CANCELLED').length,noShows:pickups.filter(reservation=>reservation.status==='NO_SHOW').length,averageRentalHours:booked.length?round(totalDuration/booked.length):null,occupiedHours:operating.occupiedHours,capacityHours:operating.capacityHours,utilizationRate:operating.capacityHours?round(operating.occupiedHours/operating.capacityHours*100):null,deliveryCount,deliveryRate:booked.length?round(deliveryCount/booked.length*100):null,dollyCount,dollyRate:booked.length?round(dollyCount/booked.length*100):null}}

function trends(reservations:AnalyticsReservation[],range:AnalyticsRange,keyOf:(day:string)=>string){const map=new Map<string,TrendPoint>();for(const reservation of reservations.filter(item=>inPickupRange(item,range))){const key=keyOf(arizonaDayKey(reservation.pickup_at));const point=map.get(key)||{key,bookingCount:0,bookedRevenueCents:0};point.bookingCount++;if(isBooked(reservation))point.bookedRevenueCents+=Number(reservation.rental_charge_cents);map.set(key,point)}return[...map.values()].sort((a,b)=>a.key.localeCompare(b.key))}

function insights(current:AnalyticsSummary,sources:SourcePoint[],dayOfWeek:{day:string;bookingCount:number}[],availableTrailerDays:number):Insight[]{if(current.reservationRequests<3)return[{id:'insufficient-data',title:'More data needed',detail:`${current.reservationRequests} reservation request${current.reservationRequests===1?'':'s'} in this range; at least 3 are required for performance insights.`,threshold:'Rule: fewer than 3 reservation requests',tone:'neutral'}];const result:Insight[]=[];const topSource=[...sources].sort((a,b)=>b.bookingCount-a.bookingCount)[0];if(current.reservationRequests>=4&&topSource&&topSource.bookingCount/current.reservationRequests>=.5)result.push({id:'source-concentration',title:'Lead source concentration',detail:`${topSource.source} supplied ${topSource.bookingCount} of ${current.reservationRequests} reservation requests (${round(topSource.bookingCount/current.reservationRequests*100)}%).`,threshold:'Rule: leading source ≥ 50% with at least 4 reservation requests',tone:'neutral'});const adverse=current.cancellations+current.noShows;if(current.reservationRequests>=5&&adverse/current.reservationRequests>=.15)result.push({id:'cancellation-watch',title:'Cancellation outcome watch',detail:`${adverse} of ${current.reservationRequests} reservation requests (${round(adverse/current.reservationRequests*100)}%) ended cancelled or no-show.`,threshold:'Rule: adverse outcomes ≥ 15% with at least 5 reservation requests',tone:'warning'});const topDay=[...dayOfWeek].sort((a,b)=>b.bookingCount-a.bookingCount)[0];if(current.reservationRequests>=5&&topDay&&topDay.bookingCount/current.reservationRequests>=.3)result.push({id:'high-demand-day',title:'Requested pickup-day concentration',detail:`${topDay.day} accounts for ${topDay.bookingCount} of ${current.reservationRequests} requested pickups (${round(topDay.bookingCount/current.reservationRequests*100)}%).`,threshold:'Rule: one weekday ≥ 30% with at least 5 reservation requests',tone:'positive'});if(availableTrailerDays>=14&&current.utilizationRate!==null&&current.utilizationRate<35)result.push({id:'utilization-opportunity',title:'Available capacity',detail:`Utilization is ${current.utilizationRate}% across ${round(availableTrailerDays)} available trailer-days.`,threshold:'Rule: utilization < 35% with at least 14 available trailer-days',tone:'neutral'});const active=current.reservationRequests-adverse;if(active>=5&&current.dollyRate!==null&&current.dollyRate<20)result.push({id:'dolly-opportunity',title:'Low dolly uptake',detail:`${current.dollyCount} of ${active} non-cancelled/no-show bookings (${current.dollyRate}%) include a dolly.`,threshold:'Rule: dolly uptake < 20% with at least 5 non-cancelled/no-show bookings',tone:'neutral'});return result}

export function calculateAnalytics(input:{reservations:AnalyticsReservation[];blocks:AnalyticsBlock[];activeTrailerIds:number[];range:AnalyticsRange;now:Date;includeSynthetic?:boolean}):AnalyticsReport{const includeSynthetic=Boolean(input.includeSynthetic);const reservations=input.reservations.filter(item=>includeSynthetic||!item.is_synthetic);const blocks=input.blocks.filter(item=>includeSynthetic||!item.is_synthetic);const previousRange=comparisonRange(input.range);const current=summary(reservations,blocks,input.activeTrailerIds,input.range);const previous=summary(reservations,blocks,input.activeTrailerIds,previousRange);const pickupRows=reservations.filter(item=>inPickupRange(item,input.range));const sourceMap=new Map<string,SourcePoint>();for(const reservation of pickupRows){const source=sourceOf(reservation);const point=sourceMap.get(source)||{source,bookingCount:0,bookedRevenueCents:0,cancelledOrNoShow:0};point.bookingCount++;if(isBooked(reservation))point.bookedRevenueCents+=Number(reservation.rental_charge_cents);if(['CANCELLED','NO_SHOW'].includes(reservation.status))point.cancelledOrNoShow++;sourceMap.set(source,point)}const dayOfWeek=weekdays.map(day=>({day,bookingCount:0}));for(const reservation of pickupRows)dayOfWeek[new Date(`${arizonaDayKey(reservation.pickup_at)}T00:00:00Z`).getUTCDay()].bookingCount++;const horizonStart=arizonaDayKey(input.now);const horizon=analyticsRange(horizonStart,addArizonaDays(horizonStart,29));const upcoming=operatingTotals(reservations,blocks,input.activeTrailerIds,horizon);const availableHours=round(Math.max(0,upcoming.capacityHours-upcoming.occupiedHours));const availableTrailerDays=current.capacityHours/16;const sources=[...sourceMap.values()].sort((a,b)=>b.bookingCount-a.bookingCount||a.source.localeCompare(b.source));return{range:input.range,comparisonRange:previousRange,includeSynthetic,current,previous,weeklyTrend:trends(reservations,input.range,weekKey),monthlyTrend:trends(reservations,input.range,day=>day.slice(0,7)),dayOfWeek,sources,upcomingAvailability:{startDate:horizon.startDate,endDate:horizon.endDate,horizonDays:30,availableHours,fullyOpenTrailerDays:upcoming.fullyOpenTrailerDays},insights:insights(current,sources,dayOfWeek,availableTrailerDays),unavailableFinancialMetrics:['Collected revenue','Payment fees','Executed refunds','Net revenue']}}
