export const COMMUNICATION_TEMPLATE_VERSION='customer-email-v2-attorney-review';
export const communicationTemplateKeys=['BOOKING_CONFIRMATION','RENTAL_CLOSEOUT'] as const;
export type CommunicationTemplateKey=typeof communicationTemplateKeys[number];
export type InspectionChoice='SEND_FORM'|'DECLINE_FORM';
export type CommunicationContext={customerName?:string|null;confirmationCode:string;pickupAt:string;returnAt:string;trailerName:string;fulfillment:string;deliverySummary?:string|null;rentalCents:number;dollyCents:number;deliveryCents:number;depositCents:number;totalCents:number;inspectionChoice:InspectionChoice;agreementLinkPlaceholder?:string;inspectionLinkPlaceholder?:string;depositDecision?:'RELEASE_RECORDED'|'RETAIN_RECORDED'|null;depositAmountCents?:number;refundCompleted?:boolean;supportEmailLabel?:string;voiceContactPlaceholder?:string};
export type RenderedCommunication={templateKey:CommunicationTemplateKey;templateVersion:string;subject:string;body:string;plainText:string;html:string};

const fallback=(value:string|null|undefined,replacement:string)=>value?.trim()||replacement;
const az=(value:string)=>new Intl.DateTimeFormat('en-US',{timeZone:'America/Phoenix',dateStyle:'medium',timeStyle:'short'}).format(new Date(value));
const money=(value:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(value/100);
const escapeHtml=(value:string)=>value.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const row=(label:string,value:string)=>`<tr><td style="padding:8px 12px;color:#5d6470;font-size:14px;vertical-align:top;border-bottom:1px solid #e6e8eb">${escapeHtml(label)}</td><td style="padding:8px 12px;color:#17191c;font-size:14px;font-weight:700;text-align:right;vertical-align:top;border-bottom:1px solid #e6e8eb">${escapeHtml(value)}</td></tr>`;
const section=(title:string,content:string)=>`<tr><td style="padding:22px 24px 6px"><h2 style="margin:0;color:#17191c;font:700 18px Arial,sans-serif">${escapeHtml(title)}</h2></td></tr><tr><td style="padding:8px 24px 18px">${content}</td></tr>`;
const shell=(preheader:string,title:string,kicker:string,content:string,support:string,voice:string)=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(title)}</title></head><body style="margin:0;background:#f2f3f5;color:#17191c;font-family:Arial,Helvetica,sans-serif"><div style="display:none;max-height:0;overflow:hidden;opacity:0">${escapeHtml(preheader)}</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="background:#f2f3f5"><tr><td align="center" style="padding:24px 12px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="max-width:620px;background:#ffffff;border:1px solid #dfe2e6;border-radius:14px;overflow:hidden"><tr><td style="padding:18px 24px;background:#17191c;border-top:4px solid #f36b21"><table role="presentation" width="100%"><tr><td><div style="color:#ffffff;font:bold 20px Arial,sans-serif;letter-spacing:.6px">TRAILER <span style="color:#f36b21">BROS</span></div><div style="margin-top:4px;color:#c8cbd0;font:12px Arial,sans-serif;letter-spacing:1.4px">UTILITY TRAILER RENTALS</div></td><td align="right" style="color:#f36b21;font:bold 12px Arial,sans-serif">${escapeHtml(kicker)}</td></tr></table></td></tr>${content}<tr><td style="padding:20px 24px;background:#f7f7f8;border-top:1px solid #e6e8eb"><p style="margin:0 0 6px;color:#34383e;font:14px/1.5 Arial,sans-serif"><strong>Questions?</strong> ${escapeHtml(support)} or ${escapeHtml(voice)}.</p><p style="margin:0;color:#70757d;font:12px/1.5 Arial,sans-serif">Trailer Bros · Arizona owner-operated trailer rentals</p></td></tr></table></td></tr></table></body></html>`;

export const communicationTemplateManifest={version:COMMUNICATION_TEMPLATE_VERSION,legalReviewStatus:'ARIZONA_ATTORNEY_REVIEW_REQUIRED',senderRequirement:'Trailer Bros Gmail sender identity must be configured outside source control.',voiceRequirement:'Google Voice contact must be configured outside source control; no number is hardcoded.',types:communicationTemplateKeys,formats:['text/plain','text/html'],externalAssets:false,tracking:false};

export function renderCommunication(key:CommunicationTemplateKey,context:CommunicationContext):RenderedCommunication{
  const name=fallback(context.customerName,'Trailer Bros customer');const support=context.supportEmailLabel||'Trailer Bros support email';const voice=context.voiceContactPlaceholder||'[Trailer Bros Google Voice contact configured at send time]';
  if(key==='BOOKING_CONFIRMATION'){
    const agreement=context.agreementLinkPlaceholder||'[secure agreement receipt link generated at send time]';const inspectionLink=context.inspectionLinkPlaceholder||'[secure pickup-inspection link generated at send time]';
    const inspectionText=context.inspectionChoice==='SEND_FORM'?`Pickup-condition inspection: Complete the secure form before using the trailer: ${inspectionLink}`:'Pickup-condition inspection: You chose to decline the offered pickup-condition inspection form. No inspection link is included.';
    const plainText=`Hi ${name},\n\nYour Trailer Bros reservation is confirmed.\n\nRESERVATION\nConfirmation: ${context.confirmationCode}\nTrailer: ${context.trailerName}\nPickup: ${az(context.pickupAt)} Arizona time\nReturn: ${az(context.returnAt)} Arizona time\nFulfillment: ${context.fulfillment}${context.deliverySummary?` — ${context.deliverySummary}`:''}\n\nPAYMENT SUMMARY\nRental: ${money(context.rentalCents)}\nDolly: ${money(context.dollyCents)}\nApproved delivery: ${money(context.deliveryCents)}\nRefundable security deposit: ${money(context.depositCents)}\nTotal collected: ${money(context.totalCents)}\nNo separate Arizona tax line.\n\nNEXT STEPS\nSigned agreement receipt: ${agreement}\n${inspectionText}\n\nQuestions: ${support} or ${voice}.`;
    const details=`<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border:1px solid #e6e8eb;border-radius:10px;overflow:hidden">${row('Confirmation',context.confirmationCode)}${row('Trailer',context.trailerName)}${row('Pickup',`${az(context.pickupAt)} Arizona time`)}${row('Return',`${az(context.returnAt)} Arizona time`)}${row('Fulfillment',`${context.fulfillment}${context.deliverySummary?` — ${context.deliverySummary}`:''}`)}</table>`;
    const payment=`<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border:1px solid #e6e8eb;border-radius:10px;overflow:hidden">${row('Rental',money(context.rentalCents))}${row('Dolly',money(context.dollyCents))}${row('Approved delivery',money(context.deliveryCents))}${row('Refundable security deposit',money(context.depositCents))}${row('Total collected',money(context.totalCents))}</table><p style="margin:10px 0 0;color:#70757d;font:12px/1.5 Arial,sans-serif">No separate Arizona tax line.</p>`;
    const inspectionHtml=context.inspectionChoice==='SEND_FORM'?`<p style="margin:12px 0 0;color:#34383e;font:14px/1.6 Arial,sans-serif"><strong>Pickup-condition inspection:</strong> Complete the secure form before using the trailer: ${escapeHtml(inspectionLink)}</p>`:`<p style="margin:12px 0 0;color:#34383e;font:14px/1.6 Arial,sans-serif"><strong>Pickup-condition inspection:</strong> You chose to decline the offered form. No inspection link is included.</p>`;
    const html=shell(`Reservation ${context.confirmationCode} is confirmed.`,`Trailer Bros booking confirmed — ${context.confirmationCode}`,'BOOKING CONFIRMED',`<tr><td style="padding:28px 24px 8px"><h1 style="margin:0;color:#17191c;font:700 26px/1.2 Arial,sans-serif">Your reservation is confirmed</h1><p style="margin:10px 0 0;color:#4b5057;font:15px/1.6 Arial,sans-serif">Hi ${escapeHtml(name)}, your Trailer Bros reservation is ready. Keep this email for your rental details and next steps.</p></td></tr>${section('Reservation details',details)}${section('Payment summary',payment)}${section('Next steps',`<p style="margin:0;color:#34383e;font:14px/1.6 Arial,sans-serif"><strong>Signed agreement receipt:</strong> ${escapeHtml(agreement)}</p>${inspectionHtml}`)}`,support,voice);
    return{templateKey:key,templateVersion:COMMUNICATION_TEMPLATE_VERSION,subject:`Trailer Bros booking confirmed — ${context.confirmationCode}`,body:plainText,plainText,html};
  }
  const retained=context.depositDecision==='RETAIN_RECORDED';const deposit=retained?`The owner recorded ${money(context.depositAmountCents||0)} for damage-related deposit review. This remains an owner-reviewed account outcome; contact Trailer Bros with questions.`:context.refundCompleted?'The authoritative payment ledger records the $100 refundable security-deposit refund as completed.':'The owner recorded a deposit release decision. The payment ledger does not yet record the refund as completed, so this email does not claim that funds were refunded.';
  const plainText=`Hi ${name},\n\nThank you for renting from Trailer Bros. Your rental is returned and the owner-recorded return inspection is complete.\n\nRENTAL CLOSEOUT\nConfirmation: ${context.confirmationCode}\nTrailer: ${context.trailerName}\nReturn: ${az(context.returnAt)} Arizona time\nStatus: Returned / inspection complete\n\nDEPOSIT OUTCOME\n${deposit}\n\nQuestions: ${support} or ${voice}.`;
  const details=`<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border:1px solid #e6e8eb;border-radius:10px;overflow:hidden">${row('Confirmation',context.confirmationCode)}${row('Trailer',context.trailerName)}${row('Return',`${az(context.returnAt)} Arizona time`)}${row('Status','Returned / inspection complete')}</table>`;
  const html=shell(`Rental ${context.confirmationCode} closeout summary.`,`Trailer Bros rental closeout — ${context.confirmationCode}`,'RENTAL CLOSEOUT',`<tr><td style="padding:28px 24px 8px"><h1 style="margin:0;color:#17191c;font:700 26px/1.2 Arial,sans-serif">Rental return complete</h1><p style="margin:10px 0 0;color:#4b5057;font:15px/1.6 Arial,sans-serif">Hi ${escapeHtml(name)}, thank you for renting from Trailer Bros. Your return and owner-recorded inspection are complete.</p></td></tr>${section('Closeout details',details)}${section('Deposit outcome',`<div style="padding:14px;border-left:4px solid #f36b21;background:#fff7f2;color:#34383e;font:14px/1.6 Arial,sans-serif">${escapeHtml(deposit)}</div>`)}`,support,voice);
  return{templateKey:key,templateVersion:COMMUNICATION_TEMPLATE_VERSION,subject:`Trailer Bros rental closeout — ${context.confirmationCode}`,body:plainText,plainText,html};
}

export async function communicationHash(value:unknown){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(typeof value==='string'?value:JSON.stringify(value)));return Array.from(new Uint8Array(bytes)).map(item=>item.toString(16).padStart(2,'0')).join('')}
