export const COMMUNICATION_TEMPLATE_VERSION='direct-closeout-v1-attorney-review';
export const communicationTemplateKeys=['BOOKING_CONFIRMATION','RENTAL_CLOSEOUT'] as const;
export type CommunicationTemplateKey=typeof communicationTemplateKeys[number];
export type InspectionChoice='SEND_FORM'|'DECLINE_FORM';
export type CommunicationContext={customerName?:string|null;confirmationCode:string;pickupAt:string;returnAt:string;trailerName:string;fulfillment:string;deliverySummary?:string|null;rentalCents:number;dollyCents:number;deliveryCents:number;depositCents:number;totalCents:number;inspectionChoice:InspectionChoice;agreementLinkPlaceholder?:string;inspectionLinkPlaceholder?:string;depositDecision?:'RELEASE_RECORDED'|'RETAIN_RECORDED'|null;depositAmountCents?:number;refundCompleted?:boolean;supportEmailLabel?:string;voiceContactPlaceholder?:string};
const fallback=(value:string|null|undefined,replacement:string)=>value?.trim()||replacement;
const az=(value:string)=>new Intl.DateTimeFormat('en-US',{timeZone:'America/Phoenix',dateStyle:'medium',timeStyle:'short'}).format(new Date(value));
const money=(value:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(value/100);
export const communicationTemplateManifest={version:COMMUNICATION_TEMPLATE_VERSION,legalReviewStatus:'ARIZONA_ATTORNEY_REVIEW_REQUIRED',senderRequirement:'Trailer Bros Gmail sender identity must be configured outside source control.',voiceRequirement:'Google Voice contact must be configured outside source control; no number is hardcoded.',types:communicationTemplateKeys};
export function renderCommunication(key:CommunicationTemplateKey,context:CommunicationContext){const name=fallback(context.customerName,'Trailer Bros customer');const support=context.supportEmailLabel||'Trailer Bros support email';const voice=context.voiceContactPlaceholder||'[Trailer Bros Google Voice contact configured at send time]';if(key==='BOOKING_CONFIRMATION'){const inspection=context.inspectionChoice==='SEND_FORM'?`\n\nPickup-condition inspection: Complete the secure form before using the trailer: ${context.inspectionLinkPlaceholder||'[secure pickup-inspection link generated at send time]'}`:'\n\nPickup-condition inspection: You explicitly chose to decline the offered pickup-condition inspection form. No inspection link is included.';return{templateKey:key,templateVersion:COMMUNICATION_TEMPLATE_VERSION,subject:`Trailer Bros booking confirmed — ${context.confirmationCode}`,body:`Hi ${name},\n\nYour Trailer Bros reservation is confirmed.\n\nTrailer: ${context.trailerName}\nPickup: ${az(context.pickupAt)} Arizona time\nReturn: ${az(context.returnAt)} Arizona time\nFulfillment: ${context.fulfillment}${context.deliverySummary?` — ${context.deliverySummary}`:''}\n\nPayment summary\nRental: ${money(context.rentalCents)}\nDolly: ${money(context.dollyCents)}\nApproved delivery: ${money(context.deliveryCents)}\nRefundable security deposit: ${money(context.depositCents)}\nTotal collected: ${money(context.totalCents)}\nNo separate Arizona tax line.\n\nSigned agreement receipt: ${context.agreementLinkPlaceholder||'[secure agreement link generated at send time]'}${inspection}\n\nQuestions: ${support} or ${voice}.`}}const retained=context.depositDecision==='RETAIN_RECORDED';const deposit=retained?`The owner recorded a deposit retention of ${money(context.depositAmountCents||0)}. This notice is a factual account summary, not legal advice. Contact Trailer Bros for review.`:context.refundCompleted?'The authoritative payment ledger records the $100 security-deposit refund as completed.':'The owner recorded a deposit release decision. The payment ledger does not yet record the refund as completed, so this message does not claim completion.';return{templateKey:key,templateVersion:COMMUNICATION_TEMPLATE_VERSION,subject:`Trailer Bros rental closeout — ${context.confirmationCode}`,body:`Hi ${name},\n\nThank you for renting from Trailer Bros. Your trailer return was recorded for ${az(context.returnAt)} Arizona time and the owner completed the return inspection.\n\nDeposit outcome: ${deposit}\n\nQuestions: ${support} or ${voice}.`}}
export async function communicationHash(value:unknown){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(typeof value==='string'?value:JSON.stringify(value)));return Array.from(new Uint8Array(bytes)).map(item=>item.toString(16).padStart(2,'0')).join('')}
