import { arizonaDayKey, parseArizonaDateTime, toArizonaInput } from './arizonaTime.js';

export type CopilotIntent='CREATE_BLACKOUT'|'CREATE_EXTERNAL_BOOKING'|'READ_ATTENTION'|'READ_REQUIREMENTS'|'READ_SCHEDULE'|'READ_ANALYTICS'|'UNKNOWN';
export type CopilotDraft={intent:CopilotIntent;mode:'READ_ONLY'|'CONFIRMATION_REQUIRED'|'UNSUPPORTED';summary:string;pickupAt?:string;returnAt?:string;source?:'BIG_RENTALS'|'NEIGHBORS_TRAILER'|'FACEBOOK_MARKETPLACE'|'OTHER';fulfillment?:'CUSTOMER_PICKUP'|'DELIVERY_REVIEW';missing:string[];warnings:string[]};

const weekdays=['sunday','monday','tuesday','wednesday','thursday','friday','saturday'];
function nextWeekday(name:string,now:Date){const target=weekdays.indexOf(name.toLowerCase());if(target<0)return null;const today=new Date(`${arizonaDayKey(now)}T12:00:00Z`);let delta=(target-today.getUTCDay()+7)%7;if(delta===0)delta=7;today.setUTCDate(today.getUTCDate()+delta);return today.toISOString().slice(0,10)}
function time(value:string){const match=value.trim().match(/^(\d{1,2})(?::(\d{2}))?\s*(am|pm)$/i);if(!match)return null;let hour=Number(match[1]);const minute=Number(match[2]||0);if(hour<1||hour>12||minute%15!==0||minute>45)return null;if(match[3].toLowerCase()==='pm'&&hour!==12)hour+=12;if(match[3].toLowerCase()==='am'&&hour===12)hour=0;return`${String(hour).padStart(2,'0')}:${String(minute).padStart(2,'0')}`}
function extractWindow(command:string,now:Date){const expression=/(sunday|monday|tuesday|wednesday|thursday|friday|saturday)\s+(?:at\s+)?(\d{1,2}(?::\d{2})?\s*(?:am|pm))\s+(?:through|to|until|-)\s+(sunday|monday|tuesday|wednesday|thursday|friday|saturday)\s+(?:at\s+)?(\d{1,2}(?::\d{2})?\s*(?:am|pm))/i.exec(command);if(!expression)return{};const startDay=nextWeekday(expression[1],now);let endDay=nextWeekday(expression[3],now);const startTime=time(expression[2]);const endTime=time(expression[4]);if(!startDay||!endDay||!startTime||!endTime)return{};if(endDay<=startDay){const date=new Date(`${endDay}T12:00:00Z`);date.setUTCDate(date.getUTCDate()+7);endDay=date.toISOString().slice(0,10)}return{pickupAt:toArizonaInput(parseArizonaDateTime(`${startDay}T${startTime}`)),returnAt:toArizonaInput(parseArizonaDateTime(`${endDay}T${endTime}`))}}
function source(command:string):CopilotDraft['source']{if(/marketplace|facebook/i.test(command))return'FACEBOOK_MARKETPLACE';if(/big rentals/i.test(command))return'BIG_RENTALS';if(/neighbors trailer/i.test(command))return'NEIGHBORS_TRAILER';return'OTHER'}

export function interpretOwnerCommand(command:string,now=new Date()):CopilotDraft{const text=command.trim();const lower=text.toLowerCase();if(!text)return{intent:'UNKNOWN',mode:'UNSUPPORTED',summary:'Enter an owner request to prepare a draft.',missing:['command'],warnings:[]};if(/what needs my attention|attention today|needs attention today/.test(lower))return{intent:'READ_ATTENTION',mode:'READ_ONLY',summary:'Show the current owner attention queue.',missing:[],warnings:[]};if(/still need an agreement|need.*pickup inspection|agreement or pickup inspection/.test(lower))return{intent:'READ_REQUIREMENTS',mode:'READ_ONLY',summary:'Show bookings with unsigned agreements or incomplete pickup inspections.',missing:[],warnings:[]};if(/business summary|summary for this month|monthly summary/.test(lower))return{intent:'READ_ANALYTICS',mode:'READ_ONLY',summary:'Show this month’s deterministic business summary.',missing:[],warnings:['Synthetic records are excluded by default.']};if(/upcoming|schedule/.test(lower)&&!/create|block|book/.test(lower))return{intent:'READ_SCHEDULE',mode:'READ_ONLY',summary:'Show the upcoming authoritative schedule.',missing:[],warnings:[]};if(/\bblock\b/.test(lower)){const window=extractWindow(text,now);return{intent:'CREATE_BLACKOUT',mode:'CONFIRMATION_REQUIRED',summary:'Prepare an owner availability block.',...window,source:source(text),fulfillment:'CUSTOMER_PICKUP',missing:[...(!window.pickupAt?['start date/time']:[]),...(!window.returnAt?['end date/time']:[])],warnings:['This draft does not change availability until the owner confirms it.']}}if(/external booking|create.*booking|marketplace rental/.test(lower)){const window=extractWindow(text,now);return{intent:'CREATE_EXTERNAL_BOOKING',mode:'CONFIRMATION_REQUIRED',summary:'Prepare an external booking in Pending Review.',...window,source:source(text),fulfillment:!/no delivery/i.test(text)&&/delivery/i.test(text)?'DELIVERY_REVIEW':'CUSTOMER_PICKUP',missing:[...(!window.pickupAt?['pickup date/time']:[]),...(!window.returnAt?['return date/time']:[]),'customer full name'],warnings:['A confirmed owner action uses the authoritative overlap and lifecycle rules.','Payment and agreement state cannot be inferred or bypassed.']}}return{intent:'UNKNOWN',mode:'UNSUPPORTED',summary:'This request is outside the deterministic command set.',missing:[],warnings:['No action was prepared. Try one of the supported examples.']}}

export function windowsOverlap(start:string,end:string,otherStart:string,otherEnd:string){return Date.parse(parseArizonaDateTime(start).toISOString())<Date.parse(parseArizonaDateTime(otherEnd).toISOString())&&Date.parse(parseArizonaDateTime(end).toISOString())>Date.parse(parseArizonaDateTime(otherStart).toISOString())}
